### ISSUE TITLE
404 for working image

### ISSUE THREAD

**Issue by Enalmada** [andrieslouw/imagesweserv#100]
This image link from wayback machine works....

`https://web.archive.org/web/20161028222242im_/http://safetyforall.com/wp-content/uploads/2016/08/img-people.jpg`

But when encoding it...
`https://images.weserv.nl/?url=ssl%3A%2F%2Fweb.archive.org%2Fweb%2F20161028222242im_%2Fhttp%3A%2F%2Fsafetyforall.com%2Fwp-content%2Fuploads%2F2016%2F08%2Fimg-people.jpg`

...it returns some strange error.
`Error 404: Server couldn't parse the ?url= that you were looking for, error it got: The requested URL returned error: 503 Service Unavailable`

**Comment by andrieslouw** [comment]
The 503 error has been fixed, it had to do with our Squid setup. Related commit https://github.com/andrieslouw/imagesweserv/commit/57c8b7095370dec34ee5623ec6aaa7eb71aaf513

In addition, web.archive.org was blocked by our filtering policy. I've adjusted the policy for web.archive.org. It will take a few hours for all changes to propagate around our network.

**Comment by andrieslouw** [comment]
Your image works now: https://images.weserv.nl/?url=ssl:web.archive.org%2Fweb%2F20161028222242im_%2Fhttp%3A%2F%2Fsafetyforall.com%2Fwp-content%2Fuploads%2F2016%2F08%2Fimg-people.jpg

**Comment by Enalmada** [comment]
Thank you very much for doing this!
