### ISSUE TITLE
Error redirect defaults to http ?

### ISSUE THREAD

**Issue by uplg** [andrieslouw/imagesweserv#104]
I can't have the "error_redirect" parameter working in HTTPS, defaulting to http and can't enforce (breaks the error image..)

**Comment by kleisauke** [comment]
To force the `errorredirect` parameter (note the missing `_`) to fetch over HTTPS you can prefix the hostname with `ssl:`. See:

```
https://images.weserv.nl/?url=example.org/noimage.jpg&errorredirect=ssl:upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg
```

The documentation for the `errorredirect` parameter needs to be clarified. Thanks for opening this issue.

**Comment by uplg** [comment]
Thanks for quick reply ! 👍 Good work
