### ISSUE TITLE
Getting VipsOperation errors

### ISSUE THREAD

**Issue by digihiveinc** [andrieslouw/imagesweserv#105]
libvips returning various errors on some operations including
400 Bad Request - VipsOperation: class "smartcrop" not found
400 Bad Request - magickload_buffer: no property named `dpi'

while other work fine

**Comment by kleisauke** [comment]
It looks like you're trying to install images.weserv.nl on your own server.

Smart crop is added in libvips 8.5, so you need to install libvips >= 8.5 ([libvips 8.5.8](https://github.com/jcupitt/libvips/releases/tag/v8.5.8) is recommended) on your server. The [php-vips extension](https://github.com/jcupitt/php-vips-ext) >= 1.0.7 (which can be found on [PECL](https://pecl.php.net/package/vips)) is also needed.

We also provide a Docker image (with the necessary dependencies), this simplifies the process of getting up and running images.weserv.nl fairly quickly. You can follow the install instructions [here](https://github.com/andrieslouw/imagesweserv/blob/3.x/DOCKER.md).

**Comment by digihiveinc** [comment]
Thank you so much. Yes. We are trying to install on our own server.
With your help we are half way through :)

We installed vips 8.5.8 with php-vips 1.0.7, and that fixed the issue with the 400 Bad Request - VipsOperation: class "smartcrop" not found
but it did not fix the issue with the 400 Bad Request - magickload_buffer: no property named `dpi'

We are getting
[root@* imgcdn.*.com]# vips -v
vips-8.5.8-Wed Sep 6 08:23:55 CDT 2017

[root@* imgcdn.*.com]# pecl install vips
pecl/vips is already installed and is the same as the released version 1.0.7

And we can't use docker, because it will create a separate web server in a virtual machine, which will conflict with current websites running on the server.

Any suggestions with 400 Bad Request - magickload_buffer: no property named `dpi' error?

Thank you

**Comment by andrieslouw** [comment]
Could have something to do with your version of ImageMagick, could you show us what version you're running?

**Comment by digihiveinc** [comment]
imagick module version | 3.4.3
-- | --
imagick classes | Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version | ImageMagick 6.9.9-11 Q16 x86_64 2017-09-04 http://www.imagemagick.org
Imagick using ImageMagick library version | ImageMagick 6.9.9-11 Q16 x86_64 2017-09-04 http://www.imagemagick.org


imagick module | enabled
-- | --
imagick module version | 3.4.3
imagick classes | Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version | ImageMagick 6.9.9-11 Q16 x86_64 2017-09-04 http://www.imagemagick.org
Imagick using ImageMagick library version | ImageMagick 6.9.9-11 Q16 x86_64 2017-09-04 http://www.imagemagick.org
ImageMagick copyright | © 1999-2017 ImageMagick Studio LLC
ImageMagick release date | 2017-09-04
ImageMagick number of supported formats: | 238
ImageMagick supported formats | 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV

**Comment by andrieslouw** [comment]
@kleisauke : Is this related to https://github.com/jcupitt/libvips/issues/523 ?

**Comment by andrieslouw** [comment]
@dihihive : Would you be willing to share any information about what you're trying to do in general? Like which image formats you're inputting, and the operations that you want to execute? Are you loading PDF's for example? The magickloader should only be executed on "exotic" image formats, so it probably has something to do with (the version of) another library.

**Comment by digihiveinc** [comment]
The error in question discussed at [jcupitt/libvips#523](https://github.com/jcupitt/libvips/issues/523)  is related to rendering PDF.

But we are not trying to do anything exotic.

The error appears when shape filter is applied //imgcdn.*.com/?url=ssl:imgcdn.*s.com/img/image.jpg&w=300&h=300&t=square&shape=circle

**Comment by digihiveinc** [comment]
so it is is just a standard JPEG image manipulation with shape filter applied to it: [http://take.ms/dfPAi](http://take.ms/dfPAi)

**Comment by kleisauke** [comment]
Did you build libvips with `librsvg`? I see:
```
SVG import with librsvg-2.0:        yes
```
<sup>(at the summary of `./configure`)</sup>

When cropping an image to a cirlce (`shape=circle`), the [Shape manipulator](https://github.com/andrieslouw/imagesweserv/blob/57c8b7095370dec34ee5623ec6aaa7eb71aaf513/src/Manipulators/Shape.php#L246-L249) makes a mask image with `librsvg` ([`vips_svgload_buffer`](https://github.com/jcupitt/libvips/blob/a8fb38fb6a841ae143173f73c8453dfa56fad85c/libvips/foreign/svgload.c)). If `librsvg` is not present, libvips will try to load SVGs via imagemagick instead ([`magickload_buffer`](https://github.com/jcupitt/libvips/blob/0d9bf6a81ec82e06fb0cf0bea51f18d0dc56497a/libvips/foreign/magickload.c)) which doesn't have the `dpi` option (it's called `density` there).

It is recommended to install `librsvg` which should be faster and more safe than ImageMagick when loading SVG images.

**Comment by digihiveinc** [comment]
Great. Thank you. That fixed it!
