### ISSUE TITLE
RGBA support

### ISSUE THREAD

**Issue by bogdanripa** [andrieslouw/imagesweserv#107]
I am trying to convert a JPG to a PNG and add transparency:

https://images.weserv.nl/?url=........jpg&w=90&h=90&t=square&shape=circle&output=png

The problem I have is that the output is RGB, and I need RGBA... Is there any way to force it? I tried adding a "&bg=00112233" parameter but without any luck...

Thanks!

**Comment by kleisauke** [comment]
The `&shape=` and `&t=letterbox` operations defaults to a transparent background (see [this](https://images.weserv.nl/?url=ory.weserv.nl/lichtenstein.jpg&w=300&h=300&t=square&shape=circle&output=png) and [this](https://images.weserv.nl/?url=ory.weserv.nl/lichtenstein.jpg&w=300&h=300&t=letterbox&output=png)). So I'm not sure what problems you're experiencing. Are you trying to replace a color with transparency?

The background operation `&bg=` needs hexadecimal RGB or ARGB values, which can be formatted as:
- 3 digit RGB: `RGB`
- 4 digit ARGB (alpha): `ARGB` 
- 6 digit RGB: `RRGGBB`
- 8 digit ARGB (alpha): `AARRGGBB`

That first pair of letters, the AA, represent the alpha channel. You must convert your decimal opacity values to a hexadecimal value. [Here's a table](https://jsfiddle.net/owc8m6xh/embedded/result/) of percentages to hexadecimal values (from 100% to 0% alpha). For example, 50% white you'd use `80FFFFFF`.

**Comment by bogdanripa** [comment]
Thanks!
