### ISSUE TITLE
When cache get cleared?

### ISSUE THREAD

**Issue by petrk94** [andrieslouw/imagesweserv#108]
Hello,

I have a image what has changed, but its showing still the old one.
After changing the value parameter in the URL of one digit, its loading the new image, so this is a caching case.
I would like to know when the cache get updated?
Thanks

**Comment by andrieslouw** [comment]
The image will be deleted eventually, but there are a lot of different caches. I expect it to be deleted between 14 and 31 days, depending on the amount of requests an image gets. Images that are getting (almost) no requests will be deleted sooner.

The server will only initiate a refresh when all caches have expired, and only when the image is still being requested by end users.

This is also stated in our wiki; https://github.com/andrieslouw/imagesweserv/wiki/Caching-of-resized-images-(server-side-caching)

**Comment by petrk94** [comment]
ah ok, exist a url parameter to specify the caching time or disable the cache?
I need just the image proxy for cropping the image automatically, no caching at all^^.
Because the image should been updated as soon it get changed.

thanks

**Comment by andrieslouw** [comment]
Unfortunately there isn't such parameter. We also don't plan adding it, to prevent people abusing it.
If needed you could use the source code from GitHub to set-up your own proxy. The cache is only something that is added on images.weserv.nl; it isn't included in the source code.

**Comment by petrk94** [comment]
ah I understand,
Thats a little sad, because this feature were pretty nice, to avoid abusing it, it could be possible to allow only specific maximum caching time.
Self hosting is for me currently not a option due only few people take a look on the image.
Thanks anyway for your help :)
