### ISSUE TITLE
Image not generating

### ISSUE THREAD

**Issue by finesofttech** [andrieslouw/imagesweserv#110]
Thanks for the nice scripts!!

Could some one help me, why my image not generating 

here is my actual image URL which is working perfectly

http://www.zabrabox.com/assets/images/camera/canon/Canon%20EOS%201300D%2018MP%20Digital%20SLR%20Camera%20(Black)%20with%2018-55mm%20ISII%20Lens,%2016GB%20Card%20and%20Carry%20Case/81+NUSxTjpL._SL1500_.jpg

And here is images.weserv.nl URL which is not working

https://images.weserv.nl/?url=www.zabrabox.com/assets/images/camera/canon/Canon%20EOS%201300D%2018MP%20Digital%20SLR%20Camera%20(Black)%20with%2018-55mm%20ISII%20Lens,%2016GB%20Card%20and%20Carry%20Case/81+NUSxTjpL._SL1500_.jpg&h=240&w=230

**Comment by kleisauke** [comment]
You'll need to encode the URL, try this:
https://images.weserv.nl/?url=www.zabrabox.com%2Fassets%2Fimages%2Fcamera%2Fcanon%2FCanon%2520EOS%25201300D%252018MP%2520Digital%2520SLR%2520Camera%2520(Black)%2520with%252018-55mm%2520ISII%2520Lens%2C%252016GB%2520Card%2520and%2520Carry%2520Case%2F81%2BNUSxTjpL._SL1500_.jpg

**Comment by finesofttech** [comment]
Thanks @kleisauke for very quick response.
