### ISSUE TITLE
Force http

### ISSUE THREAD

**Issue by marcselman** [andrieslouw/imagesweserv#111]
Hi,

I have some images I want to serve over http instead of https.
But when I call the http url of weserv it automatically redirects to https:

http://images.weserv.nl/?url=cdn.wwva.nl%2FWebshops%2FLive%2Fbenderooy%2FProducts%2FImages%2FLarge%2F13068_benderooy_3192347_1.jpg

Is there a way I can force http?

**Comment by andrieslouw** [comment]
For added security we use HSTS to let modern browsers know that they can and should use HTTPS, we don't send any redirect headers ourselves, this is being done by your browser. It prevents any opportunistic MITM attacks. See: https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
