### ISSUE TITLE
no-op resize bug when w param before url in querystring

### ISSUE THREAD

**Issue by john-alden** [andrieslouw/imagesweserv#114]
When url before w in querystring - this works correctly:
https://images.weserv.nl/?url=%2F%2Fwww.dropbox.com%2Fs%2Fzw9htv4c5k2hv45%2Fdtc.jpg%3Fdl%3D0%26raw%3D1&w=344

When w before url in querystring:
https://images.weserv.nl/?w=344&url=%2F%2Fwww.dropbox.com%2Fs%2Fzw9htv4c5k2hv45%2Fdtc.jpg%3Fdl%3D0%26raw%3D1
Source image = 344x344 px
Image is resized to 320x320px
However it works correctly when w is any value other than the source image width (e.g. 345 or 343)

**Comment by andrieslouw** [comment]
It seems the second link was different in cache. Maybe the origin changed from 320px to 344px?

**Comment by john-alden** [comment]
Yep - that'll be it.  Sorry for red herring. Thanks for investigating.
