### ISSUE TITLE
DPI support

### ISSUE THREAD

**Issue by hongkongkiwi** [andrieslouw/imagesweserv#115]
Is it possible to support DPI?

I'm trying to resize some icons to a specific DPI (144 output, 72 input) and it seems this option is missing.

**Comment by kleisauke** [comment]
Hello Andy,

This option was indeed missing, so I just added a new device pixel ratio parameter (`&dpr=`) in commit https://github.com/andrieslouw/imagesweserv/commit/5335a0cad98803eda6dd4fdfe27f9fbbd464a594 and PR https://github.com/andrieslouw/imagesweserv/pull/113.

The new parameter makes it possible to display images at the correct pixel density on a variety of devices such as Apple devices with Retina Displays and Android devices. You must specify either a width, a height, or both for this parameter to work.

If you want, you can test it on our test environment:
https://t0.nl/?url=ory.weserv.nl/lichtenstein.jpg&h=72&dpr=2

It will be implemented on the production server when libvips 8.6 is out (due this week). Thanks for reporting!

**Comment by kleisauke** [comment]
Implemented, see https://images.weserv.nl/#dpr
