### ISSUE TITLE
support HTTPS

### ISSUE THREAD

**Issue by vvavepacket** [andrieslouw/imagesweserv#116]
Hi,

How do we make it support HTTPS just like the one you are sharing? Which file/s should we edit? Thank you!

**Comment by vvavepacket** [comment]
found the fix. we need to do modification in nginx.conf file

**Comment by andrieslouw** [comment]
Easiest way would be putting CloudFlare in front of it: https://www.cloudflare.com/ssl/

And if you want to self-manage things, I would suggest using Let’s Encrypt: https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/

We use both, so Nginx+Let's Encrypt with CloudFlare in front.
