### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by Knight1** [andrieslouw/imagesweserv#121]
Hey,

i want to use it for redirecting http to https. But i would need a privacy policy for the EU regulations. 
Can you say what you log and how long? Or better you make a simple one on the website 👍 

Cheers
Tobias

**Comment by andrieslouw** [comment]
The logging we keep is minimal (to ensure performance and the end-user's privacy), but I'll make a privacy policy page dedicated to this information.

**Comment by andrieslouw** [comment]
Commits: https://github.com/andrieslouw/imagesweserv/commit/44e710f518dc4db11885e93db895130b75107a26, https://github.com/andrieslouw/imagesweserv/commit/dfede997f1e7c80a2ab79d40c1351cf179b99941.

**Comment by andrieslouw** [comment]
@Knight1 : Policy is online now, please let us know if anything is still missing 😄
