### ISSUE TITLE
Specify filename

### ISSUE THREAD

**Issue by rudin** [andrieslouw/imagesweserv#122]
I've noticed that when downloading an image it always has a default filename 'image.jpg'.
It would be great if you could add a parameter 'filename' to specify the name returned in the Content-Disposition header i.e. Content-Disposition: filename="filename.jpg" and when not specified use the filename of the file that has been loaded.

**Comment by andrieslouw** [comment]
There are some concerns to address, but we will consider introducing this option. Only way I see is by introducing a limit on the character set and the length of the filename provided. The difficulty is explained here: http://en.wikipedia.org/wiki/Filename

**Comment by rudin** [comment]
I can also imagine a limit would be required and even some normalisation (limiting/converting the character set).

**Comment by kleisauke** [comment]
Implemented, see https://images.weserv.nl/#filename. Please help by testing it.

Let me know if you run into any problems, thanks!
