### ISSUE TITLE
Cloudflare - Access Denied

### ISSUE THREAD

**Issue by bberak** [andrieslouw/imagesweserv#124]
Hi there,

First of all - huge thanks for creating this service - it's amazingly useful..

A few colleagues and I recently started receiving the following notifications when using images.weserv.nl:

```
Error 1006 Ray ID: 3fbb9e790382850e • 2018-03-15 02:41:05 UTC
Access denied
What happened?
The owner of this website (weserv.nl) has banned your IP address (203.174.xxx.xxx).
```

We work in the same building and share the same IP, so perhaps Cloudflare was being particularly cautious.

In any case, I was wondering if there is an ability to whitelist domains/hosts to lower the chance of these access denied errors - especially seeing as weserv doubles as a CDN/image cache.

Of course our last option would be to clone the project and deploy our own instance - but I thought I'd check with you guys first :)

Cheers!

**Comment by andrieslouw** [comment]
Please see https://github.com/andrieslouw/imagesweserv/issues/83

If needed, we could make an exception for your IP-address, but I would like to know a rough estimation of usage, to check if our servers will be able to cope.

**Comment by bberak** [comment]
Thanks for the quick reply @andrieslouw!

We have an Instagram style website that loads 24-72 thumbnails per page (and there are lots of pages). 

We generate thumbnails in a JIT fashion rather than in batches - and since the requests are coming from our users' browsers - I don't really have a specific IP or IP-range to provide.

I look forward to hearing from you - although I anticipate that there is probably nothing you can do here since weserv is a free public service (and you've graciously provided the source code too).

Cheers!

**Comment by andrieslouw** [comment]
@bberak : What we can do is whitelist the IP-address of your office, so testing & development from your side would be unhindered and unlimited. Let me know if this would help you.

Unfortunately we're uncomfortable with removing the restriction of 700 images per 3 minutes per IP-address for all users/visitors of our public service, if your users would stay below this figure (~4 images/second) it could work.

You're always free to use the source-code, and we're always willing to assist in code and/or infrastructure related questions. I hope [our BSD 3-clause license](https://github.com/andrieslouw/imagesweserv/blob/3.x/LICENSE.md) provides you with all the freedom you'd need in your product/application.

**Comment by bberak** [comment]
Thanks @andrieslouw, that totally makes sense.

BSD-3 should work just great - we'll look to roll out our dedicated weserv service asap. If you could whitelist our office IP in the interim - that would indeed be a huge help (203.174.191.226).

Thanks so much for the assistance, and source code :), really appreciate it.

Kind Regards.

**Comment by andrieslouw** [comment]
@bberak : Whitelisted as requested, have fun!

**Comment by bberak** [comment]
Epic, huge thanks @andrieslouw!
