### ISSUE TITLE
InMotionHosting unreachable (gabrieldiggs.com)

### ISSUE THREAD

**Issue by galaxy-nomad** [andrieslouw/imagesweserv#125]
Hello I subscribe to the RSS feed http://www.gabrieldiggs.com/feed/ on an RSS aggregator called Start.me Of the 9 RSS feeds I subscribe to the Gabriel Diggs page won't show it's RSS thumbnail images. I checked the console for errors and sure enough I get:

https://images.weserv.nl/?t=squaredown&a=attention&dpr=2&il=1&q=85&page=0&w=83&h=83&url=www.gabrieldiggs.com%2Fwordpress%2Fwp-content%2Fuploads%2Ftheoath-610x610.jpg
 
[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (images.weserv.nl, line 0)

So I decoded the link and punched the full decoded url into my web browser:

https://images.weserv.nl/?t=squaredown&a=attention&dpr=2&il=1&q=85&page=0&w=83&h=83&url=www.gabrieldiggs.com/wordpress/wp-content/uploads/theoath-610x610.jpg

That returns an error as well this time 503 I think.

Next I extracted just the image part of the URL:

www.gabrieldiggs.com/wordpress/wp-content/uploads/theoath-610x610.jpg 

When I punch that into my browser the image loads just fine. Do you have any clue as to the issue with the WordPress RSS feed and why those images will not import correctly with imagesweserv?

**Comment by andrieslouw** [comment]
It looks like gabrieldiggs.com is unreachable for our servers, looks like there is some blocking on their side. From our datacentre gabrieldiggs.com (23.235.208.13) is completely unreachable, I'm investigating if this could be a transit problem.

**Comment by andrieslouw** [comment]
Ran several tests from different locations: InMotionHosting is definitely blocking our IP-ranges, thus gabrieldiggs.com is unreachable. I'm able to reach some other servers in the same IP-range (23.235.208.xx), thus the blocking is on a server level (not router nor transit).

**Comment by galaxy-nomad** [comment]
Awesome, thanks so much for looking into this!

**Comment by galaxy-nomad** [comment]
Do you happen to know your IP range that is being blocked?

**Comment by andrieslouw** [comment]
Mainly 195.154.0.0/16 it seems (AS12876).

**Comment by galaxy-nomad** [comment]
Thanks it was an issue with the gabrieldiggs.com server as you said. Inmotionhosting seems to have unblocked your IP because the images are showing now!👍🏻 Woohoo. All the best to you!😀
