### ISSUE TITLE
Manage cyrilic and arabic caracters

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#13]
# Manage cyrilic and arabic caracters [15427689] #

**Submitted by Anonymous on 27-7-2016 0:00:00**  
**1 votes on UserVoice prior to migration**  

Hello,
The service works fine except when I try to use cyrilic and arabic caracters
ex: https://images.weserv.nl/?url=%2F%2Ftalkalang-avatars.s3-eu-west-1.amazonaws.com%2FzzcmNEhWHMgCSFKBF%2F%D0%9A%D0%B2%D0%B0%D0%B4%D1%80%D0%B0%D1%82.png

## Response ##
**by Andries Louw Wolthuizen on 28-7-2016 0:00:00**

Will do, may take some time to fix all the issues, thanks for reporting this issue!

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/15427689)**

**Comment by andrieslouw** [comment]
Fixed in current version.
