### ISSUE TITLE
Run docker image results in php-fpm error

### ISSUE THREAD

**Issue by michelalbers** [andrieslouw/imagesweserv#133]
I tried your docker tutorial on 3.x branch and ended up with the following error inside logs/supervisor/php-fpm.log:

    ERROR: unable to bind listening socket for address '/var/run/php-fpm/php-fpm.sock': No such file or directory (2)

**Comment by andrieslouw** [comment]
Will look into this, thanks for reporting!

**Comment by kleisauke** [comment]
Fixed with https://github.com/andrieslouw/imagesweserv/commit/f2bf0d94e0a48b115e3f7ba9b171ba93d3913ab1.

Let me know if you run into any problems, thanks!
