### ISSUE TITLE
Memory run out

### ISSUE THREAD

**Issue by msheep** [andrieslouw/imagesweserv#135]
Hi,

I recently deployed a image server for my company. I found the `fastcgi_temp` folder is getting bigger and bigger quickly. It raised about 1GB in one night.  After about one month running, the server is crashed because memory is out. I used the micro instance on AWS. Is there any possible solution?

Thank you!
Jing

**Comment by andrieslouw** [comment]
Hi Jing, Can you see what the filenames are that are being build up in that directory? Do they start with `imo_*` or `magick-*` ? I've never experienced a growing fastcgi_temp dir, but it can be that the server has too less memory for [fastcgi_buffering](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_buffering); it can be turned off with: `fastcgi_buffering off;` in the nginx config file.

**Comment by andrieslouw** [comment]
Took a further look; the micro instance may be a bit limited in memory indeed, but I do understand the user case as it's within the free tier of AWS. Would like to hear your comments on working with `fastcgi_buffering off;`.

**Comment by msheep** [comment]
Sorry, it is my fault, the folder which is growing fast should be fastcgi_cache, not fastcgi_temp. I have turned off fastcgi_buffering to see whether it works.

**Comment by andrieslouw** [comment]
If it's the fastcgi_cache folder: please remove all config rules starting with `fastcgi_cache` and `fastcgi_cache_*`, or change the location of `fastcgi_cache_path` to something different than /dev/shm. In the default configuration up to 5 GB of RAM (/dev/shm is a RAM disk) is reserved for caching, and you will need all RAM for resizing.

**Comment by andrieslouw** [comment]
For [API 4](https://github.com/weserv/images/issues/141) we switched to Lua, and added more information about the cache settings: https://github.com/weserv/images/blob/18cf64151ba30a7c1638bed73a6ca91266534a5b/config/nginx/conf.d/imagesweserv.conf#L1-L3

You might want to try our 4.x branch, especially if you're running on systems with low amounts of RAM. In our experience the [4.x branch (Lua)](https://github.com/weserv/images/tree/4.x) uses ~60% less RAM when compared with the [3.x branch (PHP)](https://github.com/weserv/images/tree/3.x).

Let us know if you run into trouble, as it has been some time there was activity on this ticket, I'll close it for now :smiley:
