### ISSUE TITLE
Letterbox background issue

### ISSUE THREAD

**Issue by ogessel** [andrieslouw/imagesweserv#137]
Hi guys,

I'm having an issue.

See: http://prntscr.com/jyokzp 

This is the image I am processing.
https://images.weserv.nl/?url=production-eu01-omodaschoenenbv.demandware.net/dw/image/v2/BCCT_PRD/on/demandware.static/-/Sites-omoda-master/default/dw257aebd2/21/P37921/80171_2_02.png&output=jpg&w=1200&h=800&bg=white&t=letterbox

So now the size, the format and quality are okay but it fills the image with black background instead of white.

Is there a way to combine these functions as to get a 1200 x 800 image with white background all over?

Thanks in advance.

Olaf van Gessel

**Comment by andrieslouw** [comment]
@kleisauke is working on this as we speak, the problem has been located, he will try to push a fix today!
Nice job in finding this issue, as it's quite specific 👍

**Comment by ogessel** [comment]
Lol, thx. It was not my intention ;-) Groet, Olaf

**Comment by kleisauke** [comment]
Fix (2e9b847) has been rolled out to production.

Cache has been invalidated for the [particular image](https://images.weserv.nl/?url=production-eu01-omodaschoenenbv.demandware.net/dw/image/v2/BCCT_PRD/on/demandware.static/-/Sites-omoda-master/default/dw257aebd2/21/P37921/80171_2_02.png&output=jpg&w=1200&h=800&bg=white&t=letterbox). If you want, you can send us an [email](mailto:admin@weserv.nl) with the images that are affected by this bug and need to be purged from cache.

Thanks for reporting!

**Comment by ogessel** [comment]
Top!

 

Dank voor de snelle actie, super 😊

 

Groet,

Olaf

**Comment by ogessel** [comment]
Goedemorgen Andries!

We hebben een probleem met afbeeldingen van een website.

Gaat om deze url www.bstn.com/files/image/id/67765/fixed/1/w/1000/h/1000/n/67765.jpg

Zoals je ziet doet de url het wel maar niet via WeServ. Enig idee?

Groet,
Olaf

**Comment by andrieslouw** [comment]
Servers receive HTTP 403:
```
   Der Zugriff auf den Shop wurde automatisch eingeschränkt, da die maximale Anzahl von aktiven Shop Usern bereits erreicht
   wurde. Sobald die aktiven Shop User ihren Checkout abgeschlossen haben, lässt der Server automatisch neue Zugriffe auf den
   Onlineshop zu. Wir bitten dich daher, den Shop zu einem späteren Zeitpunkt erneut zu besuchen.

   Danke für dein Verständnis - BSTN salutes you!

   Unfortunately our online shop has reached the maximum number of active shop users. As soon as active shop users complete their
   checkout, the server will grant access to new shop users. We kindly ask you to visit the website at a later date.

   Thanks for your understanding - BSTN salutes you!
```

**Comment by ogessel** [comment]
Hoi Andries,

Dank voor de toelichting.

Maar hoe kan het dan dat de gewone url en de site het wel doen? https://www.bstn.com/files/image/id/67765/fixed/1/w/1000/h/1000/n/67765.jpg en https://www.bstn.com/nl

Blijkbaar sluit ie WeServ uit maar andere browsers/IP’s niet?

Ik heb dit soort meldingen wel eerder gezien van webshops (Nike vooral), maar meestal is dat omdat ze vinden dat een partij te vaak een query doet en is jullie IP/url geband. 

Cookies weggooien kan nog wel eens helpen maar dat is geen duurzame oplossing natuurlijk. Met andere headers e.d. is eea soms wel op te lossen heb ik begrepen.

Maar goed, ik ga er dus vanuit dat dit niet gaat werken via WeServ?

Groet,
Olaf

**Comment by ogessel** [comment]
PS: ik zal ook aan BSTN vragen of ze jullie kunnen whitelisten.

Groet,
Olaf

**Comment by andrieslouw** [comment]
_Dag Olaf, even in het Engels, zodat ook anderen iets hebben aan de info;_

By default our proxy ignores all cookies, it doesn't send referrers, ignores robots.txt, uses an identifiable user-agent ([ImageFetcher](https://udger.com/resources/ua-list/bot-detail?bot=ImageFetcher)) and always origins from the same IP-address (`195.154.84.31` / `2001:bc8:2bd3:100::`).

For this particular case I checked if BSTN will reply by using a different user-agent, or accepting cookies/referrers. Unfortunately it looks like there is a ban/traffic-rule on the origin IP-address.

**Comment by ogessel** [comment]
Hoi Andries,

 

Thanks.

 

Ik ga ze vragen om jullie IP te whitelisten.

 

Groet,

Olaf

 

 

Van: Andries Louw Wolthuizen <notifications@github.com> 
Verzonden: dinsdag 27 november 2018 12:07
Aan: weserv/images <images@noreply.github.com>
CC: ogessel <olafvangessel@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [weserv/images] Letterbox background issue (#137)

 

Dag Olaf, even in het Engels, zodat ook anderen iets hebben aan de info;

By default our proxy ignores all cookies, it doesn't send referrers, ignores robots.txt, uses an identifiable user-agent (ImageFetcher <https://udger.com/resources/ua-list/bot-detail?bot=ImageFetcher> ) and always origins from the same IP-address (195.154.84.31 / 2001:bc8:2bd3:100::).

For this particular case I checked if BSTN will reply by using a different user-agent, or accepting cookies/referrers. Unfortunately it looks like there is a ban/traffic-rule on the origin IP-address.
