### ISSUE TITLE
Question of using https://images.weserv.nl/ 

### ISSUE THREAD

**Issue by mohanrao** [andrieslouw/imagesweserv#139]
Hi,

I am not sure this is right place to ask the question of https://images.weserv.nl/ usage or not. 

But i want to understand using the https://images.weserv.nl/ in any commercial product related licensing or any terms.

From the documentation it seems there is no issue in using https://images.weserv.nl/ in commercial product.

**Comment by andrieslouw** [comment]
Hi mohanroa,

There is indeed no issue using https://images.weserv.nl/ in production and/or commercial usage. You are also free to use the source code, and use it in your own products ([see our license](https://github.com/weserv/images/blob/3.x/LICENSE.md)).

Please also read [our wiki](https://github.com/weserv/images/wiki), many more questions are answered there.

**Comment by mohanrao** [comment]
Thank you for the quick reply @andrieslouw . Also can you please confirm the behaviour of https://images.weserv.nl/ when using it as below or not ?

if we use https://images.weserv.nl/ with a target url of an image with a set of parameters. images.weserv.nl will hit the target server only once for that unique url and set of parameter combinations am i correct?

**Comment by andrieslouw** [comment]
That is correct, the whole request-URI is hashed and used as a cache-key, caching will be between up till 30 days, but it depends on the amount of requests (images that are more often requested will stay longer in cache).
