### ISSUE TITLE
Error getting not 404 even thought url is working

### ISSUE THREAD

**Issue by mohanrao** [andrieslouw/imagesweserv#142]
Hi,

the following image is getting 404 

https://images.weserv.nl/?url=//www.dma.org/sites/default/files/styles/medium/public/images/4Crucero%20Del%20Norte.jpg?itok=oEbfSs4C&w=300&h=300&t=square&a=entropy

I believe may be at that time the site might be down. Is there anyway to clear the cache?

**Comment by andrieslouw** [comment]
We're looking into this issue, seems to be specific to [API 4](https://github.com/weserv/images/issues/141).

**Comment by mohanrao** [comment]
thank you @andrieslouw . Waiting for the reply when can we use the service again. 

Once again thanks for the quick reply!!!

**Comment by CryptAlchemy** [comment]
I can confirm that this issue is appearing for me, as well.

**Comment by andrieslouw** [comment]
Solved in https://github.com/weserv/images/commit/97cf7f7a8b72a8eeae6c6f26d0ea5757422804d3, please let us know if there are still any issues. The cache should refresh soon.
