### ISSUE TITLE
URL encoding change

### ISSUE THREAD

**Issue by noahbody-knows** [andrieslouw/imagesweserv#144]
Under the previous API, this URL loaded correctly:

```
https://images.weserv.nl/?url=ecx.images-amazon.com/images/I%2F51t3%252B%252B-n8WL.jpg
```

But under the new API, it must be changed to:

```
https://images.weserv.nl/?url=ecx.images-amazon.com/images/I/51t3%2B%2B-n8WL.jpg
```

In other words, URLs which already contained %-escapes previously had to have another layer of escaping to work correctly, and the server removed them, getting the original escaped URL.  Now, in v4, it appears as though the urls are taken as-is, but I'm not clear on how that's supposed to work in practice, since not escaping e.g. `&` in the URL would lead to breakage.

(Also, the new behavior is inconsistent with the documentation, which states that the `?url` is to be URL encoded.)

**Comment by andrieslouw** [comment]
Fix is being rolled out, indeed [API 4](https://github.com/weserv/images/issues/141) issue.

**Comment by andrieslouw** [comment]
Caches are refreshing, we're sorry, images should work again soon :smile:
