### ISSUE TITLE
Suddenly getting an error with Google Drive images

### ISSUE THREAD

**Issue by raRaRa** [andrieslouw/imagesweserv#145]
Hi,

I've been using images.weserv.nl to serve images from my Google Drive folder, which has been working great for about a year now, but now I suddenly get this error:
`Error 404: Server couldn't parse the ?url= that you were looking for, error it got: The requested URL returned error: 403`

Example image from my Google Drive folder:
https://drive.google.com/uc?id=1PSjfciCTXp4Bqajr9EcXWxMHuWz6P2hC&export=view

and here's the one I'm using with images.weserv.nl:
https://images.weserv.nl/?url=ssl:drive.google.com%2Fuc%3Fid%3D1PSjfciCTXp4Bqajr9EcXWxMHuWz6P2hC%26export%3Dview

Any help would be much appreciated. Thanks!

**Comment by raRaRa** [comment]
Seems to be related to https://github.com/weserv/images/issues/141 since it still works with API 3:
https://images.weserv.nl/?url=drive.google.com%2Fuc%3Fid%3D1PSjfciCTXp4Bqajr9EcXWxMHuWz6P2hC%26export%3Dview&api=3

@andrieslouw @kleisauke 

Thanks.

**Comment by andrieslouw** [comment]
Thanks for the report, and narrowing it down to API 4, we're looking into this issue!

**Comment by raRaRa** [comment]
Thanks for the quick response, much appreciated.

Any idea what could be causing this error for Google Drive links, is it related to the redirect or the link itself?

I'm wondering if I should fallback to API v3 until this has been fixed, is it safe to use v3?

Thanks!

**Comment by andrieslouw** [comment]
The problem has been found in our urlencoding, which is not exactly according to [rfc3986#section-2.2](https://tools.ietf.org/html/rfc3986#section-2.2) nor [rfc1738#section-2.2](https://tools.ietf.org/html/rfc1738#section-2.2). Fixes are being written, but there are lot's of edge cases. 

It looks like Google really likes to use the characters `$-_.+!*'(),` in the URL's they redirect to.

API 3 will still work for a while, but may end up to be redirected to API 4 in the future. It should not break anything though. I think the fix for API 4 will be in production today.

**Comment by raRaRa** [comment]
Thanks for the update!

**Comment by andrieslouw** [comment]
Fix written, and being tested in our staging-environment. If we pass all the special cases, it will be pushed to this repo and to production :smile:

**Comment by andrieslouw** [comment]
Fixed!

**Comment by raRaRa** [comment]
Where do I send PayPal donations to? :)

**Comment by andrieslouw** [comment]
https://github.com/weserv/images/wiki : 

> Since 2011 images.weserv.nl is privately funded, and used as a testbed for new techniques in resizing, recognition and processing. Operating costs of the image proxy are very low. To prevent conflicts of interest, we never accepted payments or donations in any form. (...)

But please subscribe to https://github.com/jcupitt/libvips/issues/592, I think it would be fair if donations go to libvips, as it does most of the heavy-lifting nowadays.
