### ISSUE TITLE
The proxy service is not running

### ISSUE THREAD

**Issue by ismailgorkemkara** [andrieslouw/imagesweserv#146]
Hi,

I think there's a problem with the server, it does not open non-cached pictures:
`Error 404: Server couldn't parse the ?url= that you were looking for, error it got: www.gorkemkara.com could not be resolved (2: Server failure)`

Example link:
https://images.weserv.nl/?url=www.gorkemkara.com/wp-content/themes/trendblog/images/logo.png

I also tried with other sites and images, the result is the same.

**Comment by andrieslouw** [comment]
Issue with the DNS resolver service, seems to have been solved by itself, currently investigating:

![unbound_munin_by_rcode-day](https://user-images.githubusercontent.com/11487455/43441173-30c0dc3c-949a-11e8-88fb-0f5a25a19934.png)

**Comment by andrieslouw** [comment]
Issue is unrelated to API 4, removing tag. Investigating if it was connectivity or error on the side of openDNS:
![unbound_munin_by_rcode-pinpoint 1532988010 1533018310](https://user-images.githubusercontent.com/11487455/43441790-4986394a-949c-11e8-899c-25b0ebf9010b.png)

**Comment by andrieslouw** [comment]
OpenDNS statistics confirm issue, but only with a subset of the requests, not all requests failed
![image](https://user-images.githubusercontent.com/11487455/43442788-54e30496-949f-11e8-8b6a-91272e0a0f95.png)

Starting time seems to be: **Jul 31 01:38**. End time seems to be: **Jul 31 05:35**.

**Comment by andrieslouw** [comment]
Configured Unbound DNS to fallback to [the DNS root servers](https://www.internic.net/domain/named.cache) when the servers of OpenDNS fail. This should fix the problem if OpenDNS goes down in the future. I'm sorry for any inconvenience caused, but it seems that connectivity to OpenDNS was lost for 4 hours.
