### ISSUE TITLE
Firebase Storage encoding issue

### ISSUE THREAD

**Issue by chrisbianca** [andrieslouw/imagesweserv#149]
It looks like there might be another encoding issue with the new API version 4 which is affecting users of our app.

Firebase Storage generates downloadUrls of the following format:

```
https://firebasestorage.googleapis.com/v0/b/my-project-id.appspot.com/o/users%2FrJw5TEzI7KWbwOceIk0buONCwqe2%2Fimages%2F1504025036252-tumblr_static_tumblr_static_cheese_205_1362800142.jpg?alt=media&token=b2e5b9f6-e211-4f2b-b42d-60d316c2db25
```

You'll notice that this is already a URL encoded version of a URL and needs to be supplied to Firebase exactly as it for it to be interpreted properly.

For reference, the unencoded URL is:

```
https://firebasestorage.googleapis.com/v0/b/my-project-id.appspot.com/o/users/rJw5TEzI7KWbwOceIk0buONCwqe2/images/1504025036252-tumblr_static_tumblr_static_cheese_205_1362800142.jpg?alt=media&token=b2e5b9f6-e211-4f2b-b42d-60d316c2db25
```

To make this work with weserv,  we URL encode the link and add the weserv prefix which gives the following and worked perfectly on v3:

```
https://images.weserv.nl/?url=ssl:firebasestorage.googleapis.com%2Fv0%2Fb%2Fmy-project-id.appspot.com%2Fo%2Fusers%252FrJw5TEzI7KWbwOceIk0buONCwqe2%252Fimages%252F1504025036252-tumblr_static_tumblr_static_cheese_205_1362800142.jpg%3Falt%3Dmedia%26token%3Db2e5b9f6-e211-4f2b-b42d-60d316c2db25
```

However, this now generates the following error: 

```
Error 404: Server couldn't parse the ?url= that you were looking for, error it got: The requested URL returned error: 400
```

Looking at the error responses from Firebase Storage, it implies that the URL being passed from weserv is not being correctly decoded anymore.

I have obfuscated my Firebase project ID for obvious reasons, but am happy to supply privately to whoever is investigating the issue if it helps.

**Comment by andrieslouw** [comment]
Indeed, [API 4](https://github.com/weserv/images/issues/141) strikes again, we already have a hunch of what the problem is this time. Please bear with us as we fix this, and again, we're sorry that these URL-bugs keep popping up.. (URL-encoding is really hard if you aren't using something like cURL, which we don't want to, as we're moving as close to native-C & Lua as we can get, because of performance).

**Comment by chrisbianca** [comment]
No problem, if there's anything I can do to help, please let me know

**Comment by andrieslouw** [comment]
As explained in our [Privacy Policy](https://github.com/weserv/images/blob/4.x/Privacy-Policy.md) we do keep 7 days of logs. We'll test some of your project URL's in our staging environment, so you may see some requests from `151.80.0.0/16 (AS16276)` as we're trying to fix/test the problem.

**Comment by chrisbianca** [comment]
Sure, thanks for the heads up

**Comment by andrieslouw** [comment]
Passed staging environment, pushed to repo. Fix is being rolled out, caches are refreshing, keep us updated if the issue persists! :smile:

**Comment by chrisbianca** [comment]
Everything looks to be working again now - thank you for getting this fixed so quickly!

**Comment by RichardSieg** [comment]
The issue seemed to pop up again #199
