### ISSUE TITLE
can you add support in webp from jpg?

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#15]
# can you add support in webp from jpg? [15966898] #

**Submitted by gal on 8-9-2016 0:00:00**  
**1 votes on UserVoice prior to migration**  

## Response ##
**by Andries Louw Wolthuizen on 11-10-2016 0:00:00**

This is planned. Related to: https://github.com/andrieslouw/imagesweserv/issues/68

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/15966898)**

**Comment by andrieslouw** [comment]
See https://github.com/andrieslouw/imagesweserv/issues/68

**Comment by andrieslouw** [comment]
See https://github.com/andrieslouw/imagesweserv/issues/62

**Comment by andrieslouw** [comment]
See https://github.com/andrieslouw/imagesweserv/issues/68 for follow up.
