### ISSUE TITLE
HTTP/2.0 (SPDY) URL does not seem to work (Connection: Upgrade, close)

### ISSUE THREAD

**Issue by marcselman** [andrieslouw/imagesweserv#150]
I have the following image URL:

`https://www.paardenwagentje.nl/images/fotos/115/Foto 25-04-18 15 25 30.jpg`
`https://www.paardenwagentje.nl/images/fotos/115/Foto%2025-04-18%2015%2025%2030.jpg`

I understand it's not pretty with those spaces, but it'snot my image.

If I try to use `images.weserv.nl` I use the following URL:
`https://images.weserv.nl/?url=www.paardenwagentje.nl%2Fimages%2Ffotos%2F115%2FFoto%2025-04-18%2015%2025%2030.jpg&w=75&h=65`
But it does not work.
And if I escape the already escaped `%20` as `%2520` it also does not work.
`https://images.weserv.nl/?url=www.paardenwagentje.nl%2Fimages%2Ffotos%2F115%2FFoto%252025-04-18%252015%252025%252030.jpg&w=75&h=65`

Do you have any idea how I can use this URL with `images.weserv.nl`?

Thanks.

**Comment by andrieslouw** [comment]
We're looking into this, something is wrong, but we're unsure what..

**Comment by andrieslouw** [comment]
Error found in https://github.com/pintsized/lua-resty-http/blob/master/lib/resty/http.lua#L683-L695

No support for `Connection: Upgrade, close` (HTTP/2.0, SPDY) in `lua-resty-http`, will try to patch.

**Comment by andrieslouw** [comment]
Patch written by @kleisauke , testing in staging environment, will push to production if tests pass.

**Comment by andrieslouw** [comment]
Thanks for the report, it works now, you can use:
`https://images.weserv.nl/?url=www.paardenwagentje.nl%2Fimages%2Ffotos%2F115%2FFoto%2025-04-18%2015%2025%2030.jpg&w=75&h=65`

Example: https://images.weserv.nl/?url=www.paardenwagentje.nl%2Fimages%2Ffotos%2F115%2FFoto%2025-04-18%2015%2025%2030.jpg&w=75&h=65

Caches will clear, will keep this ticket open as we're going to push the patch upstream tonight.

**Comment by kleisauke** [comment]
Patch has been proposed upstream.

**Comment by marcselman** [comment]
Thank you guys for the quick response!
Love you work!

Bedankt ;)

**Comment by andrieslouw** [comment]
Geen probleem :smile: Commit is merged upstream, closing issue.
