### ISSUE TITLE
Error getting 410 

### ISSUE THREAD

**Issue by mohanrao** [andrieslouw/imagesweserv#152]
https://images.weserv.nl/?url=http://sammonsartcenter.org/wp-content/uploads/2018/07/Jodi-Crawford-Wright-845x321.jpg&w=300&h=300&t=square&a=entropy

**Comment by andrieslouw** [comment]
The link you've provided seems to work perfect. Are you sure you're getting an error for this specific link?

Error 410 is reserved for filtered domains or DNS-errors, you can check the status of domains here: https://community.opendns.com/domaintagging/

**Comment by mohanrao** [comment]
yes.. it is working fine now. sometime back it was giving 410. I have the snapshot.

**Comment by andrieslouw** [comment]
Will check the logfiles tomorrow, to see what went wrong, could be a temporary DNS error, thanks for the report!

**Comment by andrieslouw** [comment]
I can see the 410 you've got around `[10/Aug/2018:22:21:54 +0200]`, but I'm not able to find the reason for it. DNS failed, but I'm unsure where exactly (could be connectivity, slow response, packet lost, etc). 

Let us know if this happens again, so I can do a bit more digging.
