### ISSUE TITLE
Production use

### ISSUE THREAD

**Issue by osrec** [andrieslouw/imagesweserv#153]
Hi there! 

Thanks for the great service :)

We were hoping to use your image proxy in production. Is this allowed? Are there any limits on bandwidth? 

Also, how long do you cache images for - do they get refreshed if the image at the source URL is updated?

**Comment by andrieslouw** [comment]
Hi osrec,

There is indeed no issue using https://images.weserv.nl/ in production and/or commercial usage. You are also free to use the source code, and use it in your own products ([see our license](https://github.com/weserv/images/blob/4.x/LICENSE.md)).

Regarding bandwidth; we do ~100TB outbound per month currently, I'm not sure about your application, but if this number would not, let's say, double it should be fine. Caching will be between up till 30 days, but it depends on the amount of requests (images that are more often requested will stay longer in cache). There is no check to see if an image has been updated, it's just a simple LRU-cache.

Please also read [our wiki](https://github.com/weserv/images/wiki), many more questions are answered there.

**Comment by osrec** [comment]
Great, thank you for the (very) quick response :)

Btw, we will hardly make a dent in your bandwidth!
