### ISSUE TITLE
Wrong size for ico pictures

### ISSUE THREAD

**Issue by ScriptArtist** [andrieslouw/imagesweserv#154]
As example picture 32x32: 
https://accounts.google.com/favicon.ico

If open thought images.weserv.nl, picture will change size to 16x16px
https://images.weserv.nl/?url=https://accounts.google.com/favicon.ico

**Comment by wei** [comment]
Multi-size ico file : ) [Changelog](https://github.com/weserv/images/search?q=%22multi-size+ICO+file%22&unscoped_q=%22multi-size+ICO+file%22)

https://images.weserv.nl/?url=https://accounts.google.com/favicon.ico&page=1
![](https://images.weserv.nl/?url=https://accounts.google.com/favicon.ico&page=1)
https://images.weserv.nl/?url=https://accounts.google.com/favicon.ico&page=2
![](https://images.weserv.nl/?url=https://accounts.google.com/favicon.ico&page=2)

**Comment by andrieslouw** [comment]
That favicon is a so-called mutiresolution favicon, see https://en.wikipedia.org/wiki/Favicon.

By default, we take the first occuring favicon, which is the smallest, this also happens here: https://images.weserv.nl/?url=images.weserv.nl/favicon.ico

**Comment by andrieslouw** [comment]
And indeed, please see https://images.weserv.nl/#page on how to get the bigger sizes.

**Comment by ScriptArtist** [comment]
Thanks!

But how to get biggest resolution icon? (or the same as in the browser response https://www.google.com/favicon.ico)

Only way i see now is brute force pages and check resolution of icons.

**Comment by andrieslouw** [comment]
Need to check our implementation, but I think it needs to be added..
@kleisauke: could this be extended into something to get the last page/biggest resolution?

**Comment by juantxo-g** [comment]
I also hava an issue with a favicon file.

My url: https://images.weserv.nl/?w=16&h=16&errorredirect=https://st1.okgift.eu/v1/images/def-favicon.jpg&url=www.pullandbear.com%2Ffavicon.ico

also with: 

https://images.weserv.nl/?w=16&h=16&errorredirect=https://st1.okgift.eu/v1/images/def-favicon.jpg&url=https%3A%2F%2Fwww.pullandbear.com%2Ffavicon.ico

Url https://www.pullandbear.com/favicon.ico works ok.

I get a 404 status code and a text: "Error 404: Server couldn't parse the ?url= that you were looking for, error it got: Invalid or unsupported image format. Is it a valid image?"

It is supposed that when using errorredirect parameter and an error occurs, the other image was returned, not an error code and a text.

Am I right?

**Comment by kleisauke** [comment]
Regarding this issue; perhaps we should add a special value to the `&page=` parameter (for e.g. `&page=-1` and `&page=-2`) to get the biggest/smallest page, because I think that a stand-alone parameter will cause confusion.

@juantxo-g I forgot to mention; the `&errorredirect=` parameter works now for all errors (include API errors) with https://github.com/weserv/images/commit/ebd66a5c308d87f1cfac339b7e76b60745052147.

**Comment by juantxo-g** [comment]
I get now an Error 520 (from Cloudflare) when accesing: 

https://images.weserv.nl/?w=16&h=16&t=square&a=attention&url=https%3A%2F%2Fwww.amazon.es%2Ffavicon.ico&errorredirect=https://cdn.okgift.es/v2/images/def-favicon.jpg

**Comment by andrieslouw** [comment]
@juantxo-g : Sorry, this took us a while to figure out, but it should be solved now! ImageMagick had some strange issues since updating CentOS to the latest version, fixed it by restarting all services & reloading all configs on our servers.

**Comment by andrieslouw** [comment]
For future updates, please see: https://github.com/weserv/images/issues/170
