### ISSUE TITLE
Browser cache doesn't work, expected to return HTTP 301

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#16]
# Browser cache doesn't work, expected to return HTTP 301 [16591651] #

**Submitted by Binyamin on 10-10-2016 0:00:00**  
**1 votes on UserVoice prior to migration**  

https://images.weserv.nl/?url=rbx.weserv.nl/lichtenstein.jpg is never cached by browser, it always returns HTTP 200, while when cached expected to return HTTP 301. You can test/check it in https://redbot.org/?uri=https://images.weserv.nl/?url=rbx.weserv.nl/lichtenstein.jpg
Related issue in https://github.com/andrieslouw/imagesweserv/issues/66

## Response ##
**by Andries Louw Wolthuizen on 11-10-2016 0:00:00**

Please check your response codes: 301 is Permanent Redirect, you are probably referring to 304 Not Modified.
Please carefully read: https://github.com/andrieslouw/imagesweserv/wiki/Browser-cache-control-headers-(client-side-caching)
Because the idea you’re proposing is really a bad idea, and will increase traffic. Test your browser, you’ll see that it will cache images from images.weserv.nl just fine! The headers you’re referring too are actually a flawed concept to start with.

#### Comment by Binyamin on 12-10-2016 21:07:00 ####
Sorry, I meant 304 and not 301.
https://images.weserv.nl/?url=rbx.weserv.nl/lichtenstein.jpg never returns 304.

#### Comment by Andries Louw Wolthuizen (Webmaster, Images.weserv.nl - Image cache & resize proxy) on 12-10-2016 23:07:00 ####
I know it never returns 304, that's part of the design, have you read the knowledgebase article I linked? Please do so. Carefully. Because there are good reasons to never use last-modified, to never use 304 and never use Etags. The images are cached without those headers by any modern (post IE6) browser. We use Cache-Control, which will and is working perfect. Please read the knowledgebase article.

#### Comment by Binyamin on 12-10-2016 23:21:00 ####
@Andries, I read your link few times - unfortunately its isn't how https://images.weserv.nl/?url=rbx.weserv.nl/lichtenstein.jpg currently works (perhaps is a bug).
Double checked, it always returns "Cache-Control:max-age=0", while your documentation mentions Cache-Control "max-age=2678400". It means the browser cache is always avoided.
Interesting that has "Date:Wed, 12 Oct 2016 21:17:17 GMT" and "Expires:Sat, 12 Nov 2016 21:17:17 GMT" and it still doesn't affect the browser cache. Check DEV Tools, the Network expected to show "from disk/memory cache".

#### Comment by Andries Louw Wolthuizen (Webmaster, Images.weserv.nl - Image cache & resize proxy) on 13-10-2016 7:23:00 ####
That's strange, and would mean that the headers you see are different from these ones: https://redbot.org/?uri=https%3A%2F%2Fimages.weserv.nl%2F%3Furl%3Drbx.weserv.nl%2Flichtenstein.jpg
Just curious; what is your test setup? Which browser and debug-tools are you using?

#### Comment by Binyamin on 13-10-2016 7:53:00 ####
Sorry, I just noticed "Cache-Control:public, max-age=2678400" in "Response Headers", while in "Request Headers" is still stuck with "Cache-Control:max-age=0", and browsers (latest Chrome, etc.) doesn't ever tries to cache it, but instead makes a server call on every request/refresh.
Are you sure "Last-Modified" must be dropped and with it the new request will allays call the origin server instead of immediate respond from cache (I think browser is expected to compare cached file headers in order to decide if return from cache or make a call to server)?

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/16591651)**

**Comment by andrieslouw** [comment]
See https://github.com/andrieslouw/imagesweserv/issues/66
