### ISSUE TITLE
Join transformations

### ISSUE THREAD

**Issue by Krato** [andrieslouw/imagesweserv#163]
Hello, first thanks for your awesome work!

Is there any chance to join some image transformations? Imagine that I want to crop an image, rotate it and then crop it again. It is possible?

Thanks!

**Comment by andrieslouw** [comment]
It's not something that's on our roadmap, what would be the reason to do these operations in succession? Because rotating, and cropping afterwards would be the right way, I think? This is as it's handled nowadays.

**Comment by andrieslouw** [comment]
Please re-open this issue with some examples, closing it for now, as I cannot come up with good examples myself.
