### ISSUE TITLE
Bandwidth statistics

### ISSUE THREAD

**Issue by leongersen** [andrieslouw/imagesweserv#164]
I'm currently looking into switching to self-hosting this service, but I'd like to do a quick cost/benefit analysis before migrating. Is there a way to get some insights into the bandwidth used for a specific host (or, in my case, an S3 bucket)?

**Comment by andrieslouw** [comment]
Unfortunately, the access-logs of CloudFlare are not shared with us. Our own logs only keep 7 days of first-time requests, so images that are from cache will not show. I think the best way would be to rent a (virtual) server for a few hours/days, and try it. If your visitors are mostly from Europe: Scaleway.com has some nice offers to get you started.

If you can share the name of the S3 bucket I could give you our last 7 days of logs (minus identifying information such as IP's of course), in that case, please mail us: admin@weserv.nl

**Comment by leongersen** [comment]
Thanks for your answer. I figure I can get a guestimate for the first-time requests from looking at the bandwidth usage at AWS, so that part is covered. I added some sampling to the front-end of our application, and it looks like we'll be able to handle the required load. Guess I can plan migrating for next week!

On another note, thank you so much for this service! It has really helped me getting some sites up and running in no time. I've been following the development in this repo and picked up a bunch of new things I'm happy to have learned!
