### ISSUE TITLE
allow robots

### ISSUE THREAD

**Issue by darampatz** [andrieslouw/imagesweserv#165]
Hi,

I guess, weserv disallows robots to index images. Is there a way to allow googlebot to index the images we use?

Thank you in advance,

**Comment by andrieslouw** [comment]
Hi there,

Unfortunately we cannot do this on our service. Search engines keep asking for images that no one will be looking at, so our servers would be busy talking to other servers without any benefit.

There also have been issues with copyright claims and DMCA, which are time consuming. Keeping the images out of search results, saves us from responding to lawyers that are barely able to use Google (I'd rather see them jobless, and use our time productive).

You're free to use the source code provided here to host your own solution without any robots.txt :smiley:

**Comment by andrieslouw** [comment]
If there are still any questions left unanswered: let us know!

**Comment by ggglyke** [comment]
Hi,
Does this mean that if we use your service, it is impossible to index our images in search engines like google images ?

**Comment by sugoidesune** [comment]
@andrieslouw I would appreciate the possibility to add a flag to the images that either allows indexing or forwards the original url for indexing.

Cached Images that are allowed indexing could be limited to a cache-life of 1 Day removing any legal worries.
And i don't think search engine traffic would be a noticeable amount.

**Comment by andrieslouw** [comment]
You're free to use the source code provided here to host your own solution without any robots.txt.

We have tried it in the past, and will not do it again, it creates a lot of non-human traffic without any (big) benefits.
