### ISSUE TITLE
Error 404: The requested URL returned error: Operation timed out.

### ISSUE THREAD

**Issue by DaanEasyAds** [andrieslouw/imagesweserv#166]
Hi guys!

https://images.weserv.nl/?url=ssl:vendendo.nl%2Fwp-content%2Fuploads%2F2018%2F10%2F8718475577027_a_en_hd_1-2.jpg&w=75&h=65 is returning the following error: Error 404: Server couldn't parse the ?url= that you were looking for, error it got: The requested URL returned error: Operation timed out.

I've tried https://www.geoscreenshot.com, so it seems your IP isn't being blocked.

Do you see more than we do?

Thanks and enjoy the weekend!

Best,
Daan

**Comment by andrieslouw** [comment]
Will investigate! (Need to clear some other tasks first, so may take a while).

**Comment by andrieslouw** [comment]
The IP-adress of vendendo.nl (107.6.156.58) is unreachable from our network, I'm investigating whether this is a routing issue or otherwise..

**Comment by andrieslouw** [comment]
Looks like we're blocked, as other IP's in that segment (eg. .57 and .63) are reachable. Packets to .58 are being dropped, packets to other ampro#.fcomet.com servers are also dropped (ampro1, ampro2, ampro3, etc).

**Comment by andrieslouw** [comment]
Fastcomet (hoster of vendendo.nl) is trigger happy with regards to blocking IP's, quote from their FAQ:
> We are using a complex Firewall system on all our shared hosting servers. If you are still not able to access your account, your IP address could be blocked on the server due to many reasons.

There's not much I can do to help you further, I'm sorry..

**Comment by DaanEasyAds** [comment]
Thanks for checking Andries!
At least we can inform the user correctly now.

**Comment by DaanEasyAds** [comment]
@andrieslouw Fastcomet requested the range of IPs Weserv uses. Could you provide these? Thanks!

**Comment by andrieslouw** [comment]
All outgoing traffic is fixed to `195.154.84.31` (in range `195.154.0.0/16`) nowadays.

**Comment by andrieslouw** [comment]
Seems to work fine nowadays, let us know if there are still any issues!
