### ISSUE TITLE
Minimum server config

### ISSUE THREAD

**Issue by rezakho** [andrieslouw/imagesweserv#167]
What is the current server config for main project?
We want to know base server config for serving 1M request per day on our server.

**Comment by andrieslouw** [comment]
A single dedicated server, using Intel® Xeon® D-1531 (6 cores/12 threads), 32GB DDR4 ECC RAM, and some SSD storage (only needed for logfiles, and to store things between reboots) is capable of serving 4-5 million requests per **hour**, utilizing a single 1 Gbit/s connection. 1 million per **day** would need ~100 times less (if evenly spread out over the day). Please watch the RAM usage, even really small servers will need at least 1-2 GB to process images quick without out-of-memory situations. Main operations are CPU and RAM bound, so slow I/O (disks) would not be a problem, but virtualization will take the speed out of the CPU and RAM operations.

My advice: just try it on a server with a few x86-64 threads and 2GB RAM, and be prepared to upgrade if needed so. There are many great deals, to get some power in Europe I would recommend: Hetzner.de (Robot), OVH.fr (Kimsufi) or Online.net (Scaleway). The provided docker image should be easy to migrate if needed.

**Comment by rezakho** [comment]
That is helpful.
Thanks 👍

**Comment by andrieslouw** [comment]
I will close this issue for now, but if you have any questions left, let us know!
