### ISSUE TITLE
Tinypic.com images wont load

### ISSUE THREAD

**Issue by TCboxa** [andrieslouw/imagesweserv#171]
Error 410: Server couldn't parse the ?url= that you were looking for, because the hostname of the origin is unresolvable (DNS) or blocked by policy.

https://images.weserv.nl/?url=ssl:www.oi68.tinypic.com/2qcm3x5.jpg

Yet if using the link without the weserv image proxy the image loads http://oi68.tinypic.com/2qcm3x5.jpg

**Comment by wei** [comment]
Indeed it loads, but what you specified in the url `https://www.oi68.tinypic.com/2qcm3x5.jpg` does not load

**Comment by TCboxa** [comment]
Sorry, I tried it with www after using it without failed. I pasted the wrong link in the OP

https://images.weserv.nl/?url=ssl:oi68.tinypic.com/2qcm3x5.jpg

Doesn't work either.

**Comment by wei** [comment]
https://oi68.tinypic.com/2qcm3x5.jpg does not work. If it doesn't support https, you should remove `ssl:`

https://images.weserv.nl/?url=oi68.tinypic.com/2qcm3x5.jpg works fine

**Comment by TCboxa** [comment]
Ok I get it now lol sorry.
