### ISSUE TITLE
Broken image with an url with parameters

### ISSUE THREAD

**Issue by JulesChcn** [andrieslouw/imagesweserv#175]
Hi there,

I'm trying to display an image from an url which contains parameters (so a GET method), but no extension (like .jpg)

I succeeded by using a basic JavaScript snippet

```
src = 'http://www.ujuke.fr/PlayTheNextAPI/getSongPhoto.php?Key=myApiKey&SongGuid=a03c93dbe12b4db58f9ed6e734d7dd62&Type=2', 
// Where SongGuid is the image ID, and Type is the image size
                
img = document.createElement('img');
img.src = src;
```

and now I'd like to display it through your service.

Can't figure out a way to get the image, here is what I've tried:
`src="https://images.weserv.nl/?url=www.ujuke.fr/PlayTheNextAPI/getSongPhoto.php?Key=myApiKey&SongGuid=a03c93dbe12b4db58f9ed6e734d7dd62&Type=2"`

I tried to add the base64 encoding into the url, the webp output but.. still.

Thanks in advance

**Comment by JulesChcn** [comment]
It's the url encoding... Solved.

**Comment by andrieslouw** [comment]
Yes, the correct URL would be `https://images.weserv.nl/?url=ssl:www.ujuke.fr/PlayTheNextAPI/getSongPhoto.php%3FKey%3DmyApiKey%26SongGuid%3Da03c93dbe12b4db58f9ed6e734d7dd62%26Type%3D2`
