### ISSUE TITLE
Improve Docker image & deployment

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#180]
Things that should be done, in no order:
- [X] ~~Create an organization on Docker Hub.~~ 
  Done: https://hub.docker.com/u/weserv.
- [x] Copy the contents of this repository to the container instead of defining `/var/www/imagesweserv` as volume.
  - [x] Perhaps we could just clone the repo (?). For example:
  ```
  RUN git clone https://github.com/weserv/images.git /var/www/imagesweserv
  ```
- [x] Copy `/config/nginx/conf.d` to `/usr/local/openresty/nginx/conf/conf.d/` instead of defining that directory as volume.
- [x] Add `RUN make dev` to the Dockerfile to install the required LuaRocks dependencies.
- [x] Remove the heavy-weight   `supervisord`  approach and set the Docker entrypoint to:
  ```
  ENTRYPOINT ["nginx", "-g", "daemon off;"]
  ```
  - [x] This implies that Redis rate limiter is disabled in the Docker file. Is this the right solution?
- [x] Should we remove `/dev/shm` as a volume?
- [x] Publish the revamped Docker image to GitHub's Container Registry.
- [x] Test the image on the Google Cloud Platform. See: https://github.com/weserv/images/issues/179.

If someone knows more tasks, please feel free to add them in the comments.

**Comment by andrieslouw** [comment]
- [x] Double-check if the Docker image works out-of-the-box, see #182 .

**Comment by andrieslouw** [comment]
#204 is part of the work on the Docker deployment.

**Comment by kleisauke** [comment]
I know a number of people running the Docker image on Google Cloud Platform without any issues, I'll close.
