### ISSUE TITLE
Same images failed to process

### ISSUE THREAD

**Issue by stanpro** [andrieslouw/imagesweserv#185]
Have made test and found that with ratio 1-2 images out 10  from random sites failed to process for two reasons "Operation timed out" or "Invalid or unsupported image format. Is it a valid image?".

They moderate in size and visible in my location, any browser accepts them. I can't understand the reason of the failure.

Just two samples.

https://images.weserv.nl/?url=rnk-concept.ru/wp-content/uploads/2018/04/1_ed9b3e31-2-e1524208893661.jpg
Error 404: Server couldn't parse the ?url= that you were looking for, error it got: Invalid or unsupported image format. Is it a valid image?

https://images.weserv.nl/?url=www.bcasa.it/wp-content/uploads/2013/07/confronto_contideposito.jpg
Error 404: Server couldn't parse the ?url= that you were looking for, error it got: The requested URL returned error: Operation timed out.

**Comment by andrieslouw** [comment]
The first URL returns something different it seems, could be a block, will investigate further.
There seems to be a firewall between AS1267 (Wind) and AS52030 (Server Plan S.r.l. Italy) for the second URL; our servers are blocked by bcasa.it.

**Comment by andrieslouw** [comment]
The first URL replies with some kind of hotlink protection:
```
HTTP/1.1 200 OK
Server: nginx-reuseport/1.13.4
Date: Tue, 11 Jun 2019 19:11:27 GMT
Content-Type: text/html
Content-Length: 274
Last-Modified: Fri, 30 Oct 2015 22:27:54 GMT
Connection: keep-alive
Keep-Alive: timeout=30
ETag: "5633eeea-112"
Accept-Ranges: bytes

<html><head><script>function set_cookie(){var now = new Date();var time = now.getTi
me();time += 19360000 * 1000;now.setTime(time);document.cookie='beget=begetok'+'; e
xpires='+now.toGMTString()+'; path=/';}set_cookie();location.reload();;</script></h
ead><body></body></html>
```

Unfortunately, there is nothing we can do to process these kind of protections automatically.

**Comment by stanpro** [comment]
Any way thanks for your research.
