### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by raRaRa** [andrieslouw/imagesweserv#191]
Same issue as last time, Cloudflare error page with connection error to origin. Tagging @andrieslouw and @kleisauke

**Comment by raRaRa** [comment]
It seems to be working again for me now.

**Comment by andrieslouw** [comment]
Yup, same issue, it took a while for the server to be marked as faulty. Under review again, related to #190.

**Comment by andrieslouw** [comment]
The filesystem (XFS) was the issue again, this could be software, or one of the SSD's failing. Hardware replacement is possibly needed, will try to reimage the offending server first (ory.weserv.nl), but I want to wait on general availability of CentOS 8.0. I'll keep this issue open, untill it is fully fixed. Sorry for all the trouble, ory has worked flawlessly the past 2 years, but we may need to reconsider our policy on when to replace servers. Also, our monitoring and switching system takes time to catch these issues, we might have to take a look into that one also. Lot's of stuff to learn!

**Comment by andrieslouw** [comment]
We'll start some testing with CentOS 8 tomorrow. Will rollback to EXT4, because it looks like XFS is not the best choice in our case (many small files, with continuous read/write/deletions).

**Comment by andrieslouw** [comment]
We've almost finished a week of sharing the load between CentOS 7 & CentOS 8 servers. I'll migrate the load to the new servers, and will re-image the old servers. In the background we're writing down everything to make a new Docker-image.

**Comment by raRaRa** [comment]
That's great to hear! Thanks so much for the updates.

**Comment by andrieslouw** [comment]
Docker-image continues in #204. Our servers are running CentOS 8 now.
Let us know if there is anything else we can assist with.
