### ISSUE TITLE
Error 400 when rendering images from Samsung devices?

### ISSUE THREAD

**Issue by tkoenig** [andrieslouw/imagesweserv#194]
Here is an example image which brakes on images.weserv.com .
This worked, before, so I assume an libvips upgrade introduced this?

See also https://github.com/lovell/sharp/issues/1578 as a reference.

Might it be possible to explicitly set `failOnError: false` for libvips in this case too?

## Original Image
http://blobby.wsimg.com/go/0296993c-cade-4ae8-8a65-b3172f22a3a0/6e14af04-904c-4654-936e-2bd7e6e08dd8.jpg

## Cropping with weserv fails 

https://images.weserv.nl/?url=http://blobby.wsimg.com/go/0296993c-cade-4ae8-8a65-b3172f22a3a0/6e14af04-904c-4654-936e-2bd7e6e08dd8.jpg&w=600&h=600&t=square

**Comment by andrieslouw** [comment]
Related to https://github.com/lovell/sharp/issues/1578#issuecomment-474299429

**Comment by kleisauke** [comment]
Fix (dee4ff0) has been rolled out to production.

Cache has been invalidated for the [particular image](https://images.weserv.nl/?url=http://blobby.wsimg.com/go/0296993c-cade-4ae8-8a65-b3172f22a3a0/6e14af04-904c-4654-936e-2bd7e6e08dd8.jpg&w=600&h=600&t=square). If you want, you can send us an [email](mailto:admin@weserv.nl) with the images that are affected by this bug and need to be purged from cache.

Thanks for reporting!

**Comment by tkoenig** [comment]
@kleisauke thanks for the fix! 

I quickly checked and could not find any images with errors anymore, 
so everything is fine from my side.
