### ISSUE TITLE
Error loading image at a specific width.

### ISSUE THREAD

**Issue by iveptawebadmin** [andrieslouw/imagesweserv#198]
This URL with a width of 300 doesn't work.
https://images.weserv.nl/?url=www.islandviewpta.org/uploads/gratitude.jpeg&w=300

I get the following error message.
{"status":"error","code":404,"message":"The requested URL returned error: 404"}

If I change the width value to anything other than 300 it loads the image.  Seems the error only applies to that specific width value.

**Comment by RichardSieg** [comment]
We experience the same issue with some links. By the way: Your url is working currently.

**Comment by andrieslouw** [comment]
Sorry for the delay in response, but it looks like this was a temporary issue.

**Comment by iveptawebadmin** [comment]
It's happened before on other images too, but I'll close this case for now.
