### ISSUE TITLE
Firebase storage encoding, Part 2

### ISSUE THREAD

**Issue by RichardSieg** [andrieslouw/imagesweserv#199]
Did issue #149 pop up again? 

We tried
https://images.weserv.nl/?url=ssl:firebasestorage.googleapis.com%2Fv0%2Fb%2Four-project.appspot.com%2Fo%2Frichard.playground%2Fmedia%2Fcb78b0d9-becd-4652-af26-cedcb782e69f_how.png%3Falt%3Dmedia%26token%3D13f28840-1cc4-4f48-8272-b94fb91721df
and it gives the same error:
`{"status":"error","code":404,"message":"The requested URL returned error: 400"}`
Also the decoded version
https://images.weserv.nl/?url=https://firebasestorage.googleapis.com/v0/b/our-project.appspot.com/o/richard.playground/media/cb78b0d9-becd-4652-af26-cedcb782e69f_how.png?alt=media&token=13f28840-1cc4-4f48-8272-b94fb91721df

However, this kind of url is working:
https://images.weserv.nl/?url=https://firebasestorage.googleapis.com/v0/b/our-project.appspot.com/o/148F13EA9F828A3B6E9A32C562C54CF9.png?alt=media&token=8a1c2b91-d3f1-4ef1-a7a7-8c1c4915eb88

So the issue seems to be related to the in-between slashes.

**Comment by RichardSieg** [comment]
Okay, I figured it out! We were decoding the weird firebase url syntax as an in-between step. But what's working is to just encode the url as it is. Thanks anyway and thanks for that awesome project!

**Comment by humazed** [comment]
Facing the same issue here

Not working URL:
https://images.weserv.nl/?url=https://firebasestorage.googleapis.com/v0/b/seet-1557536766251.appspot.com/o/events_images%2F1599267688%2Fimage_picker_C15E8F90-A2FC-485D-A428-8F347F54C013-10120-0000065CFB916281.jpg_3b22ebb0-9381-11ea-9e09-599546df3bdd_1599267688?alt=media&token=1e3e8b71-4f1e-44ea-857f-f427b13d79a1

working URL:
https://firebasestorage.googleapis.com/v0/b/seet-1557536766251.appspot.com/o/events_images%2F1599267688%2Fimage_picker_C15E8F90-A2FC-485D-A428-8F347F54C013-10120-0000065CFB916281.jpg_3b22ebb0-9381-11ea-9e09-599546df3bdd_1599267688?alt=media&token=1e3e8b71-4f1e-44ea-857f-f427b13d79a1

**Comment by kleisauke** [comment]
@humazed URI's (`?url=…`) must be given percent-coded. Try this:
https://images.weserv.nl/?url=https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Fseet-1557536766251.appspot.com%2Fo%2Fevents_images%252F1599267688%252Fimage_picker_C15E8F90-A2FC-485D-A428-8F347F54C013-10120-0000065CFB916281.jpg_3b22ebb0-9381-11ea-9e09-599546df3bdd_1599267688%3Falt%3Dmedia%26token%3D1e3e8b71-4f1e-44ea-857f-f427b13d79a1

If you're still having problems, please open a new issue.
