### ISSUE TITLE
Issue getting images from online store cdn

### ISSUE THREAD

**Issue by danrin** [andrieslouw/imagesweserv#201]
We've been trying to diagnose this issue but with no luck, maybe you can help us determine the cause? we try to request this:
https://images.weserv.nl/?url=ssl:asset.mijnwebwinkel.nl%2Fwinkel%2Faltijdverf%2Fimages%2Ffull%2Fa2023807fa4233945ba8a23b019b84829d9cc25d

which throws a 403. but requested through a browser the url correctly redirects to 

https://cdn.myonlinestore.eu/947ff06e-6be1-11e9-a722-44a8421b9960/image/cache/full/a2023807fa4233945ba8a23b019b84829d9cc25d.jpg

Is it simply weserv that is being blocked?

**Comment by andrieslouw** [comment]
Will need to investigate what's happening here.

**Comment by danrin** [comment]
Any news on this? If it turns out to be purely something on the myonlinestore.eu (mijnwebwinkel.nl) side i'd like to know too, it should help to narrow it down on their side as well.

**Comment by andrieslouw** [comment]
It is not something we get on other domains. From what I could see, the servers are able to reach the resources from the console. We're looking into our code, and checking if it has something to do with the user-agent we use, or maybe the code that follows redirects.

**Comment by andrieslouw** [comment]
The problem also occurs when we go directly to the URL, so redirect is not part of the problem (it seems). The problem doesn't occur always, sometimes we get `403 Forbidden`, sometimes we get `200 OK` when requesting the final image. Problem is not reproducible in our development environment (same code, different servers). Connection between origin and our servers is fine. This one is hard to pin down, it could be some blocking mechanism (rate-limit on the origin maybe?).

**Comment by danrin** [comment]
Rate limiting might be the culprit, but it seems to inconsistant for that, I suspect one of the nodes in their cdn is not playing nice. Thanks or your help on this, this cerainly helps narrowing it down. I will update this item as soon as i find the cause.

**Comment by kleisauke** [comment]
It seems that `cdn.myonlinestore.eu` is blocking one of our IPv4 addresses (`195.154.84.31` - `ory.weserv.nl`) that we use for outgoing traffic.

```bash
$ curl --ipv4 \
    --user-agent "Mozilla/5.0 (compatible; ImageFetcher/9.0; +http://images.weserv.nl/)" \
    --connect-timeout 5 \
    --max-time 10 \
    --max-redirs 10 \
    --location "https://cdn.myonlinestore.eu/947ff06e-6be1-11e9-a722-44a8421b9960/image/cache/full/a2023807fa4233945ba8a23b019b84829d9cc25d.jpg"
```

Results in ```error code: 1008```. See:
https://support.cloudflare.com/hc/en-us/articles/360029779472-Troubleshooting-Cloudflare-1XXX-errors#error100610071008

Our IPv6 addresses don't seem to be blocked (which explains why this issue doesn't always occur).

**Comment by danrin** [comment]
Great find, I will update myonlinstore on the issue! Thanks again for both your help in diagnosing this.

**Comment by danrin** [comment]
And indeed, it was a firewall setting issue on myonlinestore's end, thanks for the support in figuring this one out.
