### ISSUE TITLE
Chrome warning about weserv cookie

### ISSUE THREAD

**Issue by ebaynaud** [andrieslouw/imagesweserv#202]
A cookie associated with a cross-site resource at http://weserv.nl/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by andrieslouw** [comment]
Will look into this, probably an error on Cloudflare's side.

**Comment by andrieslouw** [comment]
CloudFlare is working on solving this, see: https://community.cloudflare.com/t/google-chrome-warning-about-cloudflare-cookie/123192/69

**Comment by andrieslouw** [comment]
This has been solved by Cloudflare 4 days ago, `SameSite=Lax` has been added.
