### ISSUE TITLE
Publish Docker image on GitHub Container Registry

### ISSUE THREAD

**Issue by andrieslouw** [andrieslouw/imagesweserv#204]
Update:
Almost all tasks are now resolved in #180. It will now be easier to use the Docker image on the Google Cloud Platform.

I will soon publish the revamped Docker image on [Docker Hub](https://hub.docker.com/u/weserv).

_Originally posted by @kleisauke in https://github.com/weserv/images/issues/179#issuecomment-531743246_

**Comment by oliverpool** [comment]
FYI I am experimenting with a Dockerfile and github actions (and container registry) in https://github.com/oliverpool/weserv-images-docker/blob/main/Dockerfile

Current status:
- [x] get the docker build and published to the registry (https://github.com/users/oliverpool/packages/container/package/weserv-images)
- [x] remove the build stuff using multistage container (the final image should just contain nginx and its linked dependencies)

**Comment by oliverpool** [comment]
I now have a working multistage Dockerfile : https://github.com/oliverpool/weserv-images-docker/blob/main/Dockerfile

Example usage (9192 being the port of the host):
```
docker run -it -p 9192:9190 -e PORT=9190 ghcr.io/oliverpool/weserv-images:latest 
```

Should I make a PR with it? (I currently use this image deploy on Google Cloud Run without any issue)

**Comment by raRaRa** [comment]
I would love to see some tutorial or small guide on how to get images.weserv running with Google Cloud Run!

**Comment by oliverpool** [comment]
@raRaRa simply go to the Console > Cloud Run > New Service and make a deployment based on the following Dockerfile (the `FROM` image is hosted on github: https://github.com/oliverpool/weserv-images-docker)
```Dockerfile
FROM ghcr.io/oliverpool/weserv-images:1750feeda44d8765ea0139ec9029b6d501d62292

ENTRYPOINT ["nginx", "-g", "daemon off;"]
```
**Container port must be set to 80** in the Cloud Console (no env variable).

**Comment by Sewdn** [comment]
@andrieslouw is this the advised way of installing weserv image server on Google Cloud?
There is no official docker image on [DockerHub](https://hub.docker.com/u/weserv) yet, right?

**Comment by andrieslouw** [comment]
There is no official image yet, because it needs to be maintained also. We may want to integrate this into our CI or something, tips and tricks are welcome. To make it work today would not be the biggest issue, but keeping it working (and testing and verifying this) is more of an issue.

**Comment by oliverpool** [comment]
@andrieslouw if you want, I can try to integrate my change into your `docker` folder (using multistage and `FROM ./Dockerfile`).

I could also port my workflow to publish it to the github registry automatically and add some documentation about the "alpha-not-maintained" status of it.

(I think making it very easy for everyone to deploy could help reduce the load on you server).

**Comment by kleisauke** [comment]
Given that [Docker Hub introduced rate limiting on pulls](https://www.docker.com/increase-rate-limits), it makes more sense to use a alternative container registry that doesn’t expose such a limit. Although marked as beta, [GitHub's Container Registry](https://docs.github.com/en/packages/guides/about-github-container-registry) is a good candidate.

Commit https://github.com/weserv/images/commit/c10cd05a025ad67168b0470ec3bb8fdb83e9c6a0 add supports for this in our CI. This means that with every commit or tag, the Docker image is built and published on GitHub's Container Registry. You can test this as follows:
```dockerfile
FROM ghcr.io/weserv/images:5.x

# Update RPM packages
RUN dnf update -y

# Overwrite default nginx config
# For example, change DNS settings:
# https://github.com/weserv/images/issues/206#issuecomment-567015037
# Or default user agent:
# https://github.com/weserv/images/issues/223#issuecomment-616219620
# etc, etc:
# https://github.com/weserv/images/tree/5.x/ngx_conf
COPY imagesweserv.conf /etc/nginx
```

```bash
$ docker build -t weserv/images .
$ docker run -d -p 80:80 --shm-size=1gb --name=imagesweserv weserv/images
```

Or by simply running:
```bash
$ docker run -d -p 80:80 --shm-size=1gb --name=imagesweserv ghcr.io/weserv/images:5.x
```

I'm happy to accept PRs to make the Docker image smaller. Keep in mind that just copying the library dependencies and executables via a multi-stage build won't work with DNF (CentOS/RHEL/Fedora default package manager), so I'm a bit reluctant for such an approach.

**Comment by oliverpool** [comment]
I guess this issue can now be closed ?

(image is available on registry and [README](https://github.com/weserv/images/blob/5.x/docker/README.md) has been updated)

**Comment by kleisauke** [comment]
Yes, it can be closed. Thank you all!
