### ISSUE TITLE
Where exactly is the resize images being stored in Docker?

### ISSUE THREAD

**Issue by amitjoseph** [andrieslouw/imagesweserv#205]
I'm running a docker to host the service and I was just wondering where exactly is the resized images/ cache being stored in server-side. Do I need to allocate more memory for a larger use-case?

**Comment by andrieslouw** [comment]
It is defined on the `proxy_cache` line in the NGINX-config:
https://github.com/weserv/images/blob/e72b8fde66558f502437c016bab7e15c0117a49b/ngx_conf/imagesweserv.conf#L3

**Comment by amitjoseph** [comment]
Alright thank you :)
