### ISSUE TITLE
Errors are cached for a long period

### ISSUE THREAD

**Issue by nerg4l** [andrieslouw/imagesweserv#207]
Hello,

First of all I want to say that I really like your service. 3 days ago we started to use it for serving Gravatar images and it made it faster and more reliable.

But here is the problem. When Gravatar responses with `503 Service Unavailable` then this service will respond with `404 Not Found` -  `The requested URL returned error: 503` message and it serves the same 404 for 3 days now in some cases.

If a new parameter is added, accessed from a different device is used or from a different zone with VPN the image served "normally" so it might be a Cloudflare configuration issue I am not sure at the current state.

Probably not helpful at all but here is an example:

https://www.gravatar.com/avatar/82a206ae2834d1f3ce0affb688ab83d1?s=100&d=wavatar

https://images.weserv.nl/?url=www.gravatar.com%2Favatar%2F82a206ae2834d1f3ce0affb688ab83d1%3Fs%3D100%26d%3Dwavatar

```json
{"status":"error","code":404,"message":"The requested URL returned error: 503"}
```

**Comment by andrieslouw** [comment]
I'm aware that there is some caching on 404's, but only for a short amount of time (eg. 15 minutes). It could be that the browser caches this response longer, or it may be that Cloudflare is holding longer on the cached response than anticipated. Will look into this, to check if there is some official statement on this behaviour. In the meantime you could play with the `&maxage=` setting: https://images.weserv.nl/docs/format.html#cache-control

**Comment by andrieslouw** [comment]
When I look at the response for https://images.weserv.nl/?url=weserv.nl/doesnotexist.jpg

I don't see any clear indication that it should be cached by anyone in the headers (no `Expires:`, no `Cache-Control:`). But I do see that the request is being cached by Cloudflare (the `Age:` header):
```
    HTTP/1.1 404 Not Found
    Date: Mon, 23 Dec 2019 17:55:31 GMT
    Content-Type: application/json
    Transfer-Encoding: chunked
    Connection: keep-alive
    Set-Cookie: __cfduid=d7cd10286300759ded1ba42b1e6a6fcce1577123731;
        expires=Wed, 22-Jan-20 17:55:31 GMT; path=/;
        domain=.weserv.nl; HttpOnly; SameSite=Lax
    Vary: Accept-Encoding
    Access-Control-Allow-Origin: *
    X-Images-Api: 5
    CF-Cache-Status: HIT
    Age: 1153
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
    Expect-CT: max-age=604800, report-uri="https://report-
        uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
    Alt-Svc: h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
    Server: cloudflare
    CF-RAY: 549c34fa08241ee7-SJC
```

Which is somewhat strange behaviour..

**Comment by andrieslouw** [comment]
Proposal @kleisauke : can we do a test with sending `Cache-Control: max-age=900` to Cloudflare for all errors? Probably we need to check this behaviour in our test-enviroment first.

**Comment by andrieslouw** [comment]
We've changed a setting regarding Edge-Cache TTL on Cloudflare's side. Errors should be cached for a shorter time now. @nerg4l : Could you test/confirm if this is working?

**Comment by nerg4l** [comment]
For now I used curl with `i`.

When using for the linked URL I get `cf-cache-status: HIT` and `age: 174847` (around 2 days). However if I test it with the given `https://images.weserv.nl/?url=weserv.nl/doesnotexist.jpg` I get `cf-cache-status: HIT` and an `age` value below 200 and then `cf-cache-status: EXPIRED` and no `age` header as expected. Probably the first one was cached before the modification.

Details below.

Command 1:

```
curl https://images.weserv.nl/\?url\=www.gravatar.com%2Favatar%2F82a206ae2834d1f3ce0affb688ab83d1%3Fs%3D100%26d%3Dwavatar -i
```

Response 1:

```
HTTP/2 404
date: Mon, 23 Dec 2019 19:07:35 GMT
content-type: application/json
set-cookie: __cfduid=d1b64c5491999ca8a5232d841a308e3841577128055; expires=Wed, 22-Jan-20 19:07:35 GMT; path=/; domain=.weserv.nl; HttpOnly; SameSite=Lax
vary: Accept-Encoding
access-control-allow-origin: *
x-images-api: 5
cf-cache-status: HIT
age: 174847
strict-transport-security: max-age=31536000; includeSubDomains; preload
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
alt-svc: h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
server: cloudflare
cf-ray: 549c9e8aeafed105-TXL

{"status":"error","code":404,"message":"The requested URL returned error: 503"}%
```

Command 2:

```
curl https://images.weserv.nl/\?url\=weserv.nl/doesnotexist.jpg -i
```

Result 2 Cache HIT:

```
HTTP/2 404
date: Mon, 23 Dec 2019 19:09:47 GMT
content-type: application/json
set-cookie: __cfduid=d81c53835fd7ff439a16946eb4f2650001577128187; expires=Wed, 22-Jan-20 19:09:47 GMT; path=/; domain=.weserv.nl; HttpOnly; SameSite=Lax
vary: Accept-Encoding
access-control-allow-origin: *
x-images-api: 5
cf-cache-status: HIT
age: 11
strict-transport-security: max-age=31536000; includeSubDomains; preload
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
alt-svc: h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
server: cloudflare
cf-ray: 549ca1c21e10d109-TXL

{"status":"error","code":404,"message":"Will not follow a redirection to itself"}%
```

Result 2 Cache Expire:

```
HTTP/2 404
date: Mon, 23 Dec 2019 19:16:40 GMT
content-type: application/json
set-cookie: __cfduid=d5ca9cb3c6bf39cc600b8ee03697559be1577128600; expires=Wed, 22-Jan-20 19:16:40 GMT; path=/; domain=.weserv.nl; HttpOnly; SameSite=Lax
vary: Accept-Encoding
access-control-allow-origin: *
x-images-api: 5
cf-cache-status: EXPIRED
strict-transport-security: max-age=31536000; includeSubDomains; preload
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
alt-svc: h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
server: cloudflare
cf-ray: 549cabd7ed5ad121-TXL

{"status":"error","code":404,"message":"Will not follow a redirection to itself"}%
```

**Comment by kleisauke** [comment]
Cache has been invalidated for the [particular image](https://images.weserv.nl/?url=www.gravatar.com%2Favatar%2F82a206ae2834d1f3ce0affb688ab83d1%3Fs%3D100%26d%3Dwavatar). If you want, you can send us an [email](mailto:admin@weserv.nl) with the images that are affected by this bug and need to be purged from cache.

**Comment by nerg4l** [comment]
We have around 35000 users with Gravatar images so it would be a bit of a hassle to check all of them, probably I will just modify the URL script by adding `1` as a query parameter.

Thank you for the quick reaction.
