### ISSUE TITLE
404 on specific domain

### ISSUE THREAD

**Issue by danrin** [andrieslouw/imagesweserv#208]
Can you help me determine what might casue this issue? I don't want to bother you too much with issues that are likely to originate with the domain, but any pointer to where this might originate is helpful since i'm running out of ideas:

This throws a 404: https://images.weserv.nl/?url=ssl:www.johan-laurens.nl%2F_carnaval%2F601287.jpg
But also just the domain; https://images.weserv.nl/?url=ssl:www.johan-laurens.nl

A recent nameserver change made me suspect a dns propagation issue but seems the least likely.
Domain owner checked wether weserv (or any specific IP address) was blocked which was not the case.
I checked the ssl, that might be an issue since not all protocols seem to be supported, can you see possible conflicts with the protols nessecary? https://www.ssllabs.com/ssltest/analyze.html?d=www.johan-laurens.nl&hideResults=on
`This server supports weak Diffie-Hellman (DH) key exchange parameters. \
The server supports only older protocols, but not the current best TLS 1.2. \
This server does not support Forward Secrecy with the reference browsers.\
This server does not support Authenticated encryption (AEAD) cipher suites.\
This server supports TLS 1.0. Grade will be capped to B from January 2020. `

**Comment by kleisauke** [comment]
This specific website uses a weak (1024 bits) Diffie-Hellman (DH) key. Centos 8 (the OS that our servers run on) utilizes the `DEFAULT` crypto policy (security level set to 112 bits for OpenSSL). As a result RSA, DSA and DH keys shorter than 2048 bits and ECC keys shorter than 224 bits are prohibited.

I've just rolled out a fix (d3e73b1) to production. Upstream connections will now the use the lowest OpenSSL security level to ensure maximum compatibility with legacy websites. Although it is still recommended that server administrators upgrade/repair their software.

Thanks for reporting!

**Comment by danrin** [comment]
Super, thanks a lot for checking and for adding legacy support. I notified the domain owner of the shortcomings!
