### ISSUE TITLE
In-cache time seems too low

### ISSUE THREAD

**Issue by dwene** [andrieslouw/imagesweserv#217]
Hi!

I'm a big fan of your service. Thank you so much for hosting it!

I've noticed recently that even though the browser has a cache max-age of 1 year, cloudflare seems to only cache the image for 7 days. At least I believe that's what the ct-expires header is indicating.

![image](https://user-images.githubusercontent.com/12628251/74693725-a5729580-51b2-11ea-89d8-f6d4ed2f1c19.png)

Is there any way to request cloudflare cache for longer? I'm noticing that about once per week images load super slowly (when cloudflare returns that ct-hit: MISS) My images are immutable, so it would be nice if there was a longer cloudflare cache.

Thanks!

**Comment by andrieslouw** [comment]
Will need to check this with Cloudflare, thanks for the report!

**Comment by andrieslouw** [comment]
The issue is not related to the `Expect-CT`-header. This header is for Certificate Transparency: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT

**Comment by andrieslouw** [comment]
It may be worthwhile to read our explanation here, especially the MRU-part: https://github.com/weserv/images/issues/213

..and there is not much which I can add on top of that, Cloudflare doesn't guarantee a minimum period of caching, unless you start paying, and our service is free. Please let us know if there are still some questions!
