### ISSUE TITLE
Issues on the 26th?

### ISSUE THREAD

**Issue by raRaRa** [andrieslouw/imagesweserv#218]
I just wanted to check in if there were any issues on the 26th of February (yesterday), that could have caused photos not to show up? Just making sure if it was an issue from my end or if something  actually happened on your end.

Thanks!

**Comment by andrieslouw** [comment]
I do see some spikes and flip-flops towards AMS-IX on the 26th and the 27th. Our provider mentions upgrades on some of the core routers in AMS-IX on these dates. While the traffic was re-routed, I do see that the link to Cloudflare's POP in AMS behaved somewhat strange (reconnected a few times), links to other Cloudflare POP's were unaffected.

But there has been no change in load, traffic or errors, and response times were stable.

**Comment by raRaRa** [comment]
Thank you so much for taking the time to check it out and the detailed answer, very much appreciated! Based on this, it looks more like an issue from my end. 

Thanks again!
