### ISSUE TITLE
Unsupported image format

### ISSUE THREAD

**Issue by marcselman** [andrieslouw/imagesweserv#219]
I've investigated everything I can think of why this image won't work:
https://images.weserv.nl/?url=ssl:www.tomzorg.nl%2Fmedia%2Fimage%2F1_hauptbild-duowave.jpg&w=75&h=65
It'a a JPEG image that opens fine in browsers. I requested the image in C# and checked the headers. They look fine as well.
Do you have any idea why this image does not work with weserv?
Or is there any hidden debug flag I can use that shows more information?

Thanks.

**Comment by andrieslouw** [comment]
Sorry we missed this, looking into it!

**Comment by andrieslouw** [comment]
Has this image changed since opening this issue? As it does seem to be working now. If you have the original around somewhere; let us know!

**Comment by marcselman** [comment]
![image](https://user-images.githubusercontent.com/514683/78531024-fd0da480-77e4-11ea-8065-4134814dd3b9.png)
For me it still does not work.
An update: they have tested it with their staging server and then the issue doesn't occur. So it seems to be a problem on their side.
Still curious to know why weserv says: "Invalid or unsupported image format. Is it a valid image?" though.

**Comment by andrieslouw** [comment]
There is also a problem at our side, there seems to be a difference between our locations.
CDG: https://cdg-images.weserv.nl/?url=ssl:www.tomzorg.nl%2Fmedia%2Fimage%2F1_hauptbild-duowave.jpg&w=75&h=65
ORY: https://ory-images.weserv.nl/?url=ssl:www.tomzorg.nl%2Fmedia%2Fimage%2F1_hauptbild-duowave.jpg&w=75&h=65

CDG seems to fail, ORY works. @kleisauke: Could you check this?

**Comment by kleisauke** [comment]
It seems that `server01.tomzorg.nl` is blocking one of our IPv4 addresses (`51.15.191.75` - `cdg.weserv.nl`) that we use for outgoing traffic.

<details>
  <summary>Details</summary>


```html
<h1>Uw verbinding met de server is geblokkeerd door de firewall.</h1>
<p>Bij vragen of problemen kunt u contact opnemen met de helpdesk van Skyberate en vermeldt daarbij onderstaande gegevens:</p>
<p>Uw IP adres is: <b>51.15.191.75</b></p>
<p>De hostname van de server is: <b>server01.tomzorg.nl</b></p>
```
</details>

A complete list of the IPs we use for outgoing traffic can be found here: https://images.weserv.nl/ips.txt

**Comment by marcselman** [comment]
It looks like they have succeeded in whiltelisting your IP's.
Thanks @kleisauke for identifying the problem.
@andrieslouw That ORY seems to have worked was because that was another IP that was not blocked I suppose.

Thanks guys.
