### ISSUE TITLE
Some images return 403 loaded from a public S3

### ISSUE THREAD

**Issue by AlmogCohen** [andrieslouw/imagesweserv#220]
Hi there! Thanks for the awesome **free** product! (I would actually be willing to pay for such an amazing product)

I've got an S3 bucket with lots of images. For most of them `weserv` works just fine. I recently found that some images refuse to load through `weserv` although a direct call to them works perfectly.

A non working example through `weserv` is [here](https://images.weserv.nl/?url=https://dynamic.wizer.me/ws-thumbnails/1A%20%C2%BFQu%C3%A9%20te%20gusta%20hacer%3F%20interactive%20worksheet%20k0idxoDOuEsi&w=400) while the direct link is working fine [here](https://dynamic.wizer.me/ws-thumbnails/1A%20%C2%BFQu%C3%A9%20te%20gusta%20hacer%3F%20interactive%20worksheet%20k0idxoDOuEsi).

90% of the other images on the website load just fine through `weserv` as can be seen [here](https://images.weserv.nl/?url=https://dynamic.wizer.me/ws-thumbnails/Waves%20And%20Their%20Properties.%20interactive%20worksheet%20iFkiQjn8xhIm&w=300).

Any ideas? I suspect it has something to do with special chars in the URL, but can hardly believe this is something `weserv` haven't seen before.

**Comment by andrieslouw** [comment]
Could be something with URL encoding indeed, Redbot also has problems accessing the resource (after you indicate you're human): https://redbot.org/?uri=https://dynamic.wizer.me/ws-thumbnails/1A%20%C2%BFQu%C3%A9%20te%20gusta%20hacer%3F%20interactive%20worksheet%20k0idxoDOuEsi

Will need to investigate further.

**Comment by AlmogCohen** [comment]
:( Please let me know if I can assist with this in anyway. Not sure I have any expertise in `webserv` stack though... the service is so great that we use this in production...and I'd love to find a solution...

**Comment by AlmogCohen** [comment]
Thanks for the quick comment though!!!

**Comment by kleisauke** [comment]
URI's  (`?url=…`) must be given percent-coded. Try this:
https://images.weserv.nl/?url=https://dynamic.wizer.me/ws-thumbnails/1A%2520%25C2%25BFQu%25C3%25A9%2520te%2520gusta%2520hacer%253F%2520interactive%2520worksheet%2520k0idxoDOuEsi

**Comment by andrieslouw** [comment]
The problem seems to be the `?` in that URL, which is probably missed by most url-encoding implementations. @AlmogCohen: Is this solvable in your code? I'm afraid there is not much we can do at our side, because everything after the second `?` is passed down as a second parameter by most browsers.

**Comment by AlmogCohen** [comment]
Oops! Obviously... It seems to be working...thanks for that! Sorry for the mess :)
