### ISSUE TITLE
Feature request: Saturation

### ISSUE THREAD

**Issue by Tylerian** [andrieslouw/imagesweserv#221]
I would like to ask for image colour saturation. When paired with blur it gives a really good effect for modern image placeholders.

I can even chime in and add a pull request for this feature if you don't have the time to implement it.

**Comment by kleisauke** [comment]
I'll make some time during the next week to start work on this. The implementation is approximately equivalent to a colorspace conversion to LCH (Luminance, Chroma, Hue) then a multiplication of pixels in the L and C channels.

If you'd like to work on this, please base your changes on the [`true-streaming`](https://github.com/weserv/images/tree/true-streaming) branch.

**Comment by Tylerian** [comment]
I was thinking more about a matrix operation as described in [W3 Filter Effects Module Draft](https://www.w3.org/TR/filter-effects-1/#MathJax-Element-2-Frame) so the end result is the same as applying a CSS saturation filter, but I'm open to further discussion on the LCH method.

I've just opened a [pull request](https://github.com/weserv/images/pull/222) where we can further discuss the details of the implementation.

**Comment by kleisauke** [comment]
Closing in favor of #226, thank you for taking the time to submit the PR and issue.
