### ISSUE TITLE
"The image is too large to be downloaded." even after updating imagesweserv.conf 

### ISSUE THREAD

**Issue by morales2k** [andrieslouw/imagesweserv#224]
Greetings!

I'm seeking some help with this configuration. I setup the docker container quite well with all the defaults. I later updated the nginx `imagesweserv.conf` config file to update the `client_max_body_size` and raise it to `600M`. 

I suppose it is active, at the very least, if I go into the container `docker exec -it imagesweserv bash` and I `cat` the file at `/etc/nginx/imagesweserv.conf`  I get my updated version.

However, trying to get a resized thumbnail from a pdf (roughly 170mb filesize) - it yields the following msg:
```json
{"status":"error","code":404,"message":"The image is too large to be downloaded. Max image size: 104857600 bytes"}
```

At least, at this msg the update I made is not reflected. 

After I updated the file in the container, I ran `docker exec nginx -t `  and `docker exec nginx -s reload`  so I believe I am loading the updated conf files. However, I am not seeing this reflected... 

Am I missing anything else!? Where is that max image size coming from and how can I change it? I believe this is no longer an nginx problem, or I'd be seeing an http:413 code?!

**Comment by morales2k** [comment]
SOLVED:

Added to `imagesweserv.conf` 
```
weserv_max_size 600000000
```
Consistent with the `client_max_body_size` of `600M` that I have already set.
Then, I reloaded nginx config `nginx -s reload` and it worked fine after that. 

We had to browse through the code for a while, may be a worthy addition on the docker.md file to explain a bit more about what other configurable options are available. :thinking:

**Comment by andrieslouw** [comment]
Hi, sorry it took a while to respond, glad you found it. You can also use the `M` suffix with this option. I'll leave it to @kleisauke to improve the docker.md with all the options available.

**Comment by morales2k** [comment]
@andrieslouw No worries! Thanks for your work on this! 

Having those options in the readme or some other form of documentation will really help out when running the self-hosted solution. 

Thanks in advance to @kleisauke  for all the effort! :+1:

**Comment by kleisauke** [comment]
The weserv directives are now documented within [ngx_conf/README.md](https://github.com/weserv/images/tree/5.x/ngx_conf). Thanks for the suggestion!
