### ISSUE TITLE
How to override 71 megapixel resolution limit?

### ISSUE THREAD

**Issue by articulite** [andrieslouw/imagesweserv#227]
I'm getting this error.

{"status":"error","code":404,"message":"Image is too large for processing. Width x height should be less than 71 megapixels."}

I've tried building a docker image with modified stream.cpp and thumbnail.cpp files, but when I comment out git clone in the dockerfile to use my modified source this happens:

CMake Error: The source directory "/var/www/imagesweserv" does not appear to contain CMakeLists.txt.

It would be nice if this configuration setting could be easily changed like "weserv_max_size" in imagesweserv.conf. Thanks.

**Comment by kleisauke** [comment]
I'll have a look to make this configurable within the nginx module. In the meantime, you could try to change these constants in the cloned repository:
https://github.com/weserv/images/blob/a9027a3fb65fe9a6c4649572e3ed7bf065c6abfb/src/api/processors/stream.cpp#L21
https://github.com/weserv/images/blob/a9027a3fb65fe9a6c4649572e3ed7bf065c6abfb/src/api/processors/thumbnail.cpp#L14

And modify the `Dockerfile`, like this:
```diff
--- a/Dockerfile
+++ b/Dockerfile
@@ -51,8 +51,8 @@ RUN dnf install -y epel-release \
 RUN groupadd nginx \
     && useradd -r -g nginx -s /sbin/nologin -c "Nginx web server" nginx
 
-# Clone the repository
-RUN git clone --recurse-submodules https://github.com/weserv/images.git /var/www/imagesweserv
+# Copy the contents of this repository to the container
+COPY . /var/www/imagesweserv
 
 WORKDIR /var/www/imagesweserv/build
```

**Comment by articulite** [comment]
Ok cool. That worked. :)

**Comment by kleisauke** [comment]
Resolved with https://github.com/weserv/images/commit/b4e8381cfdfc0423bd998ba785d9ca03e6416a22. These new directives are documented within [ngx_conf/README.md](https://github.com/weserv/images/tree/5.x/ngx_conf). Thanks for the suggestion!

Be careful when setting `weserv_limit_input_pixels` to `0`, do this only for trusted input. There are [PNG decompression bombs available](https://www.bamsoftware.com/hacks/deflate.html) that could burn all the available memory.
