### ISSUE TITLE
instagram 403 error.

### ISSUE THREAD

**Issue by mboveiri** [andrieslouw/imagesweserv#228]
Hi.
instagram image links return `"The requested URL returned error: 403"`.

**Comment by kleisauke** [comment]
We're not aware of any problems with Instagram. For example, this URL:
```
https://images.weserv.nl/?url=https://scontent-ams4-1.cdninstagram.com/v/t51.2885-19/s150x150/43913439_271376060236760_4813838902005596160_n.jpg%3F_nc_ht%3Dscontent-ams4-1.cdninstagram.com%26_nc_ohc%3Dpy41DSV4uywAX-jFzM2%26tp%3D1%26oh%3Ddc9541147c9d56cf4c1addd213d2cd41%26oe%3D60276AE7
```

Just works. Have you properly percent-coded the given URL (`?url=…`)?

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.

**Comment by BZHDeveloper** [comment]
Hello.
this JSON error appears instead of picture data
`{"status":"error","code":404,"message":"The requested URL returned error: 403"}`

**Comment by raRaRa** [comment]
@BZHDeveloper Did you remove any query parameters from the media link? They are required, otherwise you'll get a 403.
