### ISSUE TITLE
Option to use built-in default image

### ISSUE THREAD

**Issue by mercuree** [andrieslouw/imagesweserv#229]
Feature request.
Using built-in default image option can significantly reduce url length.
For example default option:
```html
<img src="//images.weserv.nl/?url=example.org/noimage.jpg&default=ssl:images.weserv.nl%2F%3Furl%3Dimages.weserv.nl/lichtenstein.jpg%26w%3D300">
```
built-in option:
```html
<img src="//images.weserv.nl/?url=example.org/noimage.jpg&builtindefault=1">
```

**Comment by andrieslouw** [comment]
Question: This is something you want to use for self-hosting I suppose? So you want to set it in the config-file?

**Comment by mercuree** [comment]
I meant any image of your choice with appropriate license, that will work with images.weserv.nl hosting too. Is it technically possible?

**Comment by andrieslouw** [comment]
That would be hard, as we need to write an interface to upload, review and address such images.
