### ISSUE TITLE
Docker install: libjpeg-turbo repo not always reachable

### ISSUE THREAD

**Issue by dcangulo** [andrieslouw/imagesweserv#232]
I am running the following command based on the docs.

```
docker build . \
    -t imagesweserv \
    --build-arg NGINX_VERSION=1.17.10
```

But got the following error:

```
Failed to download metadata for repo 'libjpeg-turbo'
Error: Failed to download metadata for repo 'libjpeg-turbo'
The command '/bin/sh -c dnf install -y epel-release     && rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8     && dnf config-manager --set-enabled PowerTools     && dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm     && rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8     && dnf config-manager --set-enabled remi     && dnf install -y --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm     && rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-8      && dnf install -y --setopt=tsflags=nodocs         git         cmake3         vips-full-devel         make         gcc         gcc-c++         openssl-devel         pcre-devel         zlib-devel' returned a non-zero code: 1
```

I am just trying it out, I am using Ubuntu 18.04 ($5 Droplet on DigitalOcean) - NYC 1.

**Comment by andrieslouw** [comment]
Probably some issues with reaching the libjpeg-turbo repo, which is notoriously slow, is there an alternative or mirror @kleisauke ?

**Comment by dcangulo** [comment]
I tried it on my local machine instead, running Deepin 15.11, and did not receive this error. I think this is okay to close?

**Comment by dcangulo** [comment]
I also tried it in another $5 Droplet, but on Debian 9.12 (NYC 3) and it works.

**Comment by kleisauke** [comment]
I'll look into mirroring the libjpeg-turbo RPMS repository. It's currently only available from SourceForge, which occasionally has some connectivity issues.

**Comment by andrieslouw** [comment]
We started a RPMS repo on https://rpms.weserv.nl , but this is mainly internal/testing for now. We will look into the addition of libjpeg-turbo.

**Comment by kleisauke** [comment]
I haven't seen this issue on SourceForge in a while, so it looks like they've fixed their connectivity issues. I'll close.
