### ISSUE TITLE
webp and apple safari  & chrome fallback to jpg

### ISSUE THREAD

**Issue by amgmbs** [andrieslouw/imagesweserv#236]
Congratulations for this amazing service and code!

Would it be possible to add fallback for apple not being able to show webp images?

This is "invisible" on macs

https://images.weserv.nl/?url=images.weserv.nl/lichtenstein.jpg&w=300&h=300&output=webp

Thank you all!

**Comment by andrieslouw** [comment]
Thanks for the suggestion, but please see #214 
Due to the Cloudflare caching it is technically impossible to do so for us.

**Comment by kleisauke** [comment]
Duplicate of #214, closing.
