### ISSUE TITLE
Image not recognized as an image

### ISSUE THREAD

**Issue by gbarnabic** [andrieslouw/imagesweserv#239]
The url for the images I need to rotate appear to be stored as blobs?? in a database.  Anyway I want to be able to rotate this image and images with similar URL's 

https://firebasestorage.googleapis.com/v0/b/glide-prod.appspot.com/o/img-uploads%2FBG27QIXsLLMPz3jpOXMt%2Fd5d1c7.jpeg?alt=media

I have tried pretty much all combinations of the image url with no luck.  Is there any way to pass in this image to be manipulated?

**Comment by kleisauke** [comment]
URI's  (`?url=…`) must be given percent-coded. Try this:
https://images.weserv.nl/?url=https://firebasestorage.googleapis.com/v0/b/glide-prod.appspot.com/o/img-uploads%252FBG27QIXsLLMPz3jpOXMt%252Fd5d1c7.jpeg%3Falt%3Dmedia

**Comment by gbarnabic** [comment]
That works!  Thanks.
