### ISSUE TITLE
Animated gifs with transparent background

### ISSUE THREAD

**Issue by fabian-emilius** [andrieslouw/imagesweserv#240]
I recently noticed some weird artefacts when resizing an animated gif with transparent background.

Example:  https://images.weserv.nl/?h=185&w=185&fit=inside&we&q=50&dpr=2&url=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2FQmZNDGswJPdxrrTkiTfarwSAgRtFh7nMFwsQgUxD5UjeRu%2F24LA_Wizard.gif&n=-1

**Comment by andrieslouw** [comment]
Interesting, thanks for the report, I wonder what's happening here!
Care to take a look @kleisauke ?

**Comment by andrieslouw** [comment]
Fixed in https://github.com/libvips/libvips/pull/1550, I will update production, as it looks a lot better in our staging environment already.

**Comment by andrieslouw** [comment]
Production is on vips 8.10 now, your link should do a lot better now. There are still some small artefacts in the dark background parts, this is something we'll continue to look into.

**Comment by fabian-emilius** [comment]
Mmh cant see any change, but I am also using a self deployed version with the latest master now. Do I have to use any other dev branch?

**Comment by kleisauke** [comment]
The [`5.x` branch](https://github.com/weserv/images/tree/5.x) is the latest one. Here's what I see when comparing this GIF image between libvips 8.9 and 8.10:

| VIPS 8.9 | VIPS 8.10 |
| :---: |  :---: |
| ![before](https://user-images.githubusercontent.com/12746591/90876171-842d7480-e3a2-11ea-84fc-822eafbbdd46.gif) | ![after](https://user-images.githubusercontent.com/12746591/90876193-8d1e4600-e3a2-11ea-9707-7900b65873a0.gif) |

Those artifacts in the background appear to come from ImageMagick (which libvips uses to save GIF files). If you [add `&output=webp`](https://images.weserv.nl/?h=185&w=185&fit=inside&we&q=50&dpr=2&url=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2FQmZNDGswJPdxrrTkiTfarwSAgRtFh7nMFwsQgUxD5UjeRu%2F24LA_Wizard.gif&n=-1&output=webp) to the URL you won't see these artifacts.

I'll try to report this issue upstream.

**Comment by fabian-emilius** [comment]
Yes I already convert it to webp, but sadly Safari does not support webp yet so I generate different urls for these users which are not a minority on my site. So this is actually just for Safari users.

What I noticed is that if I lower the resolution (e.g. 185x185 without dpr 2) the issue is also gone. Maybe it helps

**Comment by kleisauke** [comment]
Upstream bug report: https://github.com/ImageMagick/ImageMagick/issues/2450.

**Comment by fabian-emilius** [comment]
Thanks a lot for your help! Never expected to get all these answers so fast. It’s an awesome tool you have built!

**Comment by fabian-emilius** [comment]
Any updates? There was an answer on the ImageMagick issue. Can this work or not?

**Comment by kleisauke** [comment]
This has been fixed upstream.

We can safely incorporate this fix on our production server as soon as ImageMagick releases a new version (possibly 6.9.11-29) and this new version lands on [Remi's RPM repository](https://rpms.remirepo.net/).

**Comment by kleisauke** [comment]
ImageMagick v6.9.11-29 has landed on Remi's RPM repository and I just updated the production server to this version. This animated GIF image is now resized without artifacts.
