### ISSUE TITLE
DNS blocked after refreshes

### ISSUE THREAD

**Issue by fabian-emilius** [andrieslouw/imagesweserv#241]
I am currently trying to self host this service and get this error quite frequently without changing the domain:

"The hostname of the origin is unresolvable (DNS) or blocked by policy"

The exact same url works sometimes, but most of the time this error is returned. Is there any kind of setting I need to turn off because there are some unexpected rate limits?

URL looks always similar to this: .../?h=185&w=185&fit=inside&we&q=50&url=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2FQmZNDGswJPdxrrTkiTfarwSAgRtFh7nMFwsQgUxD5UjeRu%2F24LA_Wizard.gif&n=-1

I use docker and have not changed the default configuration

**Comment by andrieslouw** [comment]
Please see https://github.com/weserv/images/issues/206, it may be that you have the same issue. Let me know if this helped!

**Comment by fabian-emilius** [comment]
Seems like that was it. Thanks for your fast answer!
