### ISSUE TITLE
sturdier url parsing ?

### ISSUE THREAD

**Issue by roger21** [andrieslouw/imagesweserv#244]
hello

when the image url already has some parameters and such, and worst, some parameters that collide with those of the service it may fails (mostly because the image url parameters are not taken into account and the image grabbing fails)

could it be that the url parameter is mandatorily the last one and all the other parameters behind it are those of the image url

and only the parameters before the url parameters are for the service ?

like for instance : `https://images.weserv.nl/?n=-1&w=600&we&url=https://my.image.host/some/stuff/foobar?type=jpg&size=large&we=we&so=on`

where `https://my.image.host/some/stuff/foobar?type=jpg&size=large&we=we&so=on` is the whole url parameter

?

**Comment by andrieslouw** [comment]
This would cause a lot of issues with people that are already using the public service, and I'm also not sure if it would be possible to do so. Please urlencode your &url=, it will solve your problems.

**Comment by roger21** [comment]
I didn't think of encoding the url because I switched from a previous service that was built differently and didn't need it, but I'm still an idiot for not thinking of encoding the url, thank you
