### ISSUE TITLE
Issue with the maxage param : cache-control seems unaffected

### ISSUE THREAD

**Issue by kbsali** [andrieslouw/imagesweserv#248]
Hi,

I'm trying to lower the max-age of some assets of a web app to 1 day, but no matter what value is given to the `maxage` param, the "real" `max-age` seems to always be set to 31536000 (1 year).
Is this because images.weserv.nl/ is behind Cloudflare?

![2020-10-01_11-06](https://user-images.githubusercontent.com/53676/94790146-2f840d00-03d6-11eb-8b48-55838d8ebc19.png)

Thanks for your help.

**Comment by andrieslouw** [comment]
1m is no valid value I guess, have you tried 1d? If the value is not valid, it will default to 1 year indeed.

**Comment by kbsali** [comment]
Yes, I have tried `maxage=3600` (which in theory should translate to 3600 seconds, right?) and `maxage=1d`, but the end result is always 31536000 (1 year).

**Comment by kleisauke** [comment]
We don't support setting `max-age` duration lower than 1 month (`&maxage=31d`). Only a few valid durations can be specified, see:
https://github.com/weserv/images/blob/ec7dacb970debe626056434f992e2a0843aa4398/src/nginx/util.cpp#L93-L102

Also, the `m` suffix means minutes, here's a list of valid suffixes that can be used:
- `ms`: milliseconds
- `s`: seconds
- `m`: minutes
- `h`: hours
- `d`: days
- `y`: years, 365 days

**Comment by kbsali** [comment]
OK, the doc says
> A value without a suffix means seconds. It is recommended to always specify a suffix. (https://images.weserv.nl/docs/format.html#cache-control)

So I thought I could specify smaller values.
Maybe the doc should be updated accordingly! :) So X months translates to `maxage=X*31d` right? eg. `maxage=62d` for 2 months.

**Comment by kbsali** [comment]
I have tested out and indeed, they max-age header does change when working with 31d or 62d.

Thanks.
