### ISSUE TITLE
Error 522 from Cloudflare Milan (MXP)

### ISSUE THREAD

**Issue by cappuc** [andrieslouw/imagesweserv#253]
Today loading images from Italy, it returns a 522 error from cloudflare Milan CDN location.
I tried with a vpn and it works from other locations I tested.

Test image: https://images.weserv.nl/?url=images.weserv.nl/lichtenstein.jpg&w=300&h=300

![Schermata 2020-11-04 alle 12 20 23](https://user-images.githubusercontent.com/4271608/98105358-2801c900-1e98-11eb-8735-fdb6d60167a6.png)

**Comment by andrieslouw** [comment]
There are issues reported with the Milan, Italy (MXP) DC on https://www.cloudflarestatus.com/

Cloudflare is re-routing this DC currently.

**Comment by andrieslouw** [comment]
Closing this issue, because this was due to Cloudflare, and therw is nothing we can do to further prevent this.
