### ISSUE TITLE
Server is down:  Error 522 

### ISSUE THREAD

**Issue by finesofttech** [andrieslouw/imagesweserv#254]
Server is down since morning, please look into this.
![weserve nl](https://user-images.githubusercontent.com/3335771/98117039-34554880-1ecf-11eb-8394-ed87a9dd88f7.jpg)

**Comment by andrieslouw** [comment]
Could you share your output of: https://images.weserv.nl/cdn-cgi/trace

This can help us identify which Cloudflare location is causing problems.

**Comment by finesofttech** [comment]
Hi @andrieslouw ,
I checked this morning, issue has been resloved. 
Here is output of: https://images.weserv.nl/cdn-cgi/trace
fl=49f101
h=images.weserv.nl
ip=2405:201:4014:2003:bd86:dace:a036:9ffb
ts=1604566887.823
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
colo=MRS
http=http/2
loc=IN
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off

**Comment by finesofttech** [comment]
I have started facing some connectivity issue again. Please suggest some solution
![image](https://user-images.githubusercontent.com/3335771/98666455-14ac9d00-2373-11eb-90f0-23c6a983a237.png)
![image](https://user-images.githubusercontent.com/3335771/98666476-1c6c4180-2373-11eb-941e-46437695ad67.png)

**Comment by kleisauke** [comment]
@finesofttech It seems that you were banned today by our rate limiter at 11:16:04 and automatically unbanned at 12:16:10 (UTC). You can check your current rate limit quota here: https://images.weserv.nl/quota.

**Comment by scharfie** [comment]
I am also experiencing this issue; here's the trace output from https://images.weserv.nl/cdn-cgi/trace

```
fl=137f19
h=images.weserv.nl
ip=73.236.133.142
ts=1605207251.84
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0
colo=PIT
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
```
I also get a 522 trying to load https://images.weserv.nl/quota

**Comment by andrieslouw** [comment]
We have reports of multiple locations with 522-errors, on multiple sites provided through Cloudflare. Thank you all for the reports, it seems there are some issues with some transit-providers.
