### ISSUE TITLE
Unable to load image name with url encoded chinese characters

### ISSUE THREAD

**Issue by IMR707** [andrieslouw/imagesweserv#257]
Hi.
I tried to load an image that has a chinese characters. 

raw url
http://eticket.senheng.com.my/sh_subsidy/uploaded_files/product visual/20181030162815_lb170917008684 副本.jpg

encoded url
http://eticket.senheng.com.my/sh_subsidy/uploaded_files/product%20visual/20181030162815_lb170917008684%20%26%2321103%3B%26%2326412%3B.jpg

cache url
https://images.weserv.nl/?url=http://eticket.senheng.com.my/sh_subsidy/uploaded_files/product%20visual/20181030162815_lb170917008684%20%26%2321103%3B%26%2326412%3B.jpg

And i found out that it does not work. It returns 404, Even though the image does exist when i load the encoded url in my Chrome browser.

**Comment by kleisauke** [comment]
This origin server seems to respond only to the encoded version of the URL. For example, requesting [this URL](http://eticket.senheng.com.my/sh_subsidy/uploaded_files/product%20visual/20181030162815_lb170917008684%20%E5%89%AF%E6%9C%AC.jpg) doesn't work for me.

You could try to percent-encode the already encoded URL (known as double encoding):
https://images.weserv.nl/?url=http://eticket.senheng.com.my/sh_subsidy/uploaded_files/product%2520visual/20181030162815_lb170917008684%2520%2526%252321103%253B%2526%252326412%253B.jpg

**Comment by IMR707** [comment]
Doing double encoding seems to resolve the issue. Although the first time when its caching, it does seem a bit slow, but it does work.

Thank you for the assistance and swift reply.
