### ISSUE TITLE
imgur sudden death

### ISSUE THREAD

**Issue by brontosaurusrex** [andrieslouw/imagesweserv#258]
Since few days ago, links like

    https://images.weserv.nl/?url=https://i.imgur.com/ViPqvAJ.png

are not working anymore, getting error

    {"status":"error","code":404,"message":"The requested URL returned error: 403"}

Any ideas?

**Comment by xSlOom** [comment]
I can confirm this also.

Can we have an update on this ? We have a lot of users using imgur and they can't see their image.

@kleisauke @andrieslouw

**Comment by andrieslouw** [comment]
Looks like ImgUr blocked our service on IP-level. I'm looking into options to resolve this.

**Comment by xSlOom** [comment]
Ugh! I hope you guys can find a solution.

Thanks :)

**Comment by Eldenroot** [comment]
OK, I can confirm this :( all images are not loaded

**Comment by TCBOXA1** [comment]
Along with ImgUr blocking the image proxy it appears that all image formats are being converted to .webp which causes a problem, for example if a user uploads a JPG the link would normally be https://i.imgur.com/mIMeVlU.jpg however this will now redirect to https://m.imgur.com/mIMeVlU?r and break the IMG tag on forums etc.

**Comment by andrieslouw** [comment]
There is a new hotlink protection on imgur it seems. Meanwhile, we have indeed confirmed that the IP's and user-agents we use have been blocked too. So this is multiple levels of complexity, I would suggest everyone to seek different services for hosting the origin images.

**Comment by linkthai** [comment]
Our main uploading hosting is imgur so I have to turn weserv off now, hope there will be some way to fix it :(

**Comment by xSlOom** [comment]
> There is a new hotlink protection on imgur it seems. Meanwhile, we have indeed confirmed that the IP's and user-agents we use have been blocked too. So this is multiple levels of complexity, I would suggest everyone to seek different services for hosting the origin images.

Asking to be unblocked is not a solution ? @andrieslouw It's sad to just move on another service when most of the users we have, are using imgur ..

**Comment by roger21** [comment]
if the `Accept` header of the request of images.weserv.nl is only 

`Accept: image/webp,*/*`

instead of the usual `Accept: text/html,application/xhtml+xml,application/xml;image/webp,*/*;whatever`

it might work

edit: oh ok nvm, i thought it was because it redirects to a web page now instead of the picture

**Comment by marovargovcik** [comment]
I got really spooked today when multiple clients called that images on their sites are not loading. Switched to other image caching and resizing provider for now but I really like weserv. Hopefully this will get resolved and we can switch back.

**Comment by andrieslouw** [comment]
We are testing a fix now. Let us know if there are specific cases still not working, and we will look into these.

**Comment by andrieslouw** [comment]
The fix seems to be holding fine, thank you for the report.

**Comment by roger21** [comment]
is this dead again?

```
https://images.weserv.nl/?url=https://i.imgur.com/zNlBl8p.jpg
https://images.weserv.nl/?url=https%3A%2F%2Fi.imgur.com%2FzNlBl8p.jpg

{"status":"error","code":404,"message":"The requested URL returned error: 403"}
```

**Comment by kleisauke** [comment]
@roger21 See #319.

**Comment by roger21** [comment]
> @roger21 See #319.

ok, thanks
