### ISSUE TITLE
libvips error: vips2webp: unable to encode

### ISSUE THREAD

**Issue by meotimdihia** [andrieslouw/imagesweserv#260]
It seems Weserve can't decode images that have long height.

https://images.weserv.nl/?url=https://i.imgur.com/1SS0EHH.jpg&output=webp&q=75

`{"status":"error","code":400,"message":"libvips error: vips2webp: unable to encode\n"}`

**Comment by kleisauke** [comment]
The maximum pixel dimension of a WebP image is 16383 x 16383 (14-bit unsigned), so this image with a size of 720 x 16889 [cannot be encoded to WebP](https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be).

You could try to encode this image to a different format. Here is a list of the maximum image sizes for the supported formats:
WebP: 16383 x 16383 (14-bit unsigned)
JPEG/TIFF/GIF: 65535 x 65535 (16-bit unsigned)
PNG: 2147483647 x 2147483647 (32-bit signed)

**Comment by meotimdihia** [comment]
Thanks for your answer.
