### ISSUE TITLE
404 error when trying to access http img

### ISSUE THREAD

**Issue by josiaheakle** [andrieslouw/imagesweserv#261]
Using this url: 
https://images.weserv.nl/?url=ssl:www.capitol.tn.gov/senate/members/images/s26.jpg
I get back a 404 error, but I can access the raw image from 
http://www.capitol.tn.gov/senate/members/images/s26.jpg

I am trying to embed this into an https site, and I cannot access the image unless I use http

**Comment by andrieslouw** [comment]
Looks like the site mentioned uses geoblocking. Our servers receive the following message, and I see the same message: 
![Screenshot_20201205-083916](https://user-images.githubusercontent.com/11487455/101237005-bf477f80-36d5-11eb-9ba4-3d1506e16f4f.jpg)

**Comment by josiaheakle** [comment]
@andrieslouw thank you. I ended up making a proxy api for my usecase.
