### ISSUE TITLE
Random 204 HTTP status

### ISSUE THREAD

**Issue by gboudreau** [andrieslouw/imagesweserv#262]
I am seeing random 204 HTTP status codes, instead of 200, when requesting some images.
Here's an example URL that shows this: https://images.weserv.nl/?url=//i.imgur.com/aLTeBxL.jpg

It doesn't seem to be related to the target image's host; I've seen it happen with multiple hosts.
Another example: https://images.weserv.nl/?url=https://image.tmdb.org/t/p/w500/jutsxphSGbnpxpGr23xzbf2ziQZ.jpg

Changing the `url` param in any way (ex adding a `?` character at the end) will show the image, so not sure what is wrong with the broken URLs...

```
$ curl -v 'https://images.weserv.nl/?url=//i.imgur.com/5lTZGrj.jpg'
*   Trying 104.27.158.82...
* TCP_NODELAY set
* Connected to images.weserv.nl (104.27.158.82) port 443 (#0)
...
> GET /?url=//i.imgur.com/5lTZGrj.jpg HTTP/2
> Host: images.weserv.nl
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 204 
< date: Tue, 08 Dec 2020 22:18:59 GMT
< set-cookie: __cfduid=dc0622dd864387c64bc2466130d4bdc661607465939; expires=Thu, 07-Jan-21 22:18:59 GMT; path=/; domain=.weserv.nl; HttpOnly; SameSite=Lax
< access-control-allow-origin: *
< x-images-api: 5
< cf-cache-status: HIT
< age: 4649
< cf-request-id: 06e608cbc60000f12ad486a000000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=Vz9d%2B31VOooHKRiJE8byA2qPKvBWZEnG16AkjaR1w0t9azR7f0fFLwNNrk21nlkqJEyHPBlRXmwCUIzC7sneh2IszHMmhCcgAtZc6WKWP8%2Fy"}],"group":"cf-nel","max_age":604800}
< nel: {"report_to":"cf-nel","max_age":604800}
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< server: cloudflare
< cf-ray: 5fe9dd8c6fc7f12a-IAD
< 
* Connection #0 to host images.weserv.nl left intact
* Closing connection 0
```

**Comment by andrieslouw** [comment]
Some sites overload our servers, in order to protect the service, it will send 204's when it detects huge amounts (100+/sec) of requests originating from the same sites. It is the quickest way to close a connection. However, it looks like Cloudflare cached the 204 in your case. I will take a look on how to solve this.

**Comment by andrieslouw** [comment]
Update: Cloudflare is caching a bit aggressive, monitored this for a few days, and I see what you mean. I tried changing a few parameters, but Cloudflare ain't listening to the "do not cache" headers I tried to sent. Interesting problem..

**Comment by kleisauke** [comment]
Setting the `Cache-Control: no-store, must-revalidate` header to 204 responses fixed this issue. This fix went live on December 21, 2020. I'll close.
