### ISSUE TITLE
Disable default operation on configuration

### ISSUE THREAD

**Issue by sjahn90** [andrieslouw/imagesweserv#263]
Is it possible to disable default action of weserv_default_quality and weserv_default_level ?

I don't want to apply "quality" and "zlib compression" of image as default.

For example.
weserv_default_quality -1 => Don't change quality
weserv_default_level  -1  => Don't change zlib compression

**Comment by andrieslouw** [comment]
I need some additional explanation; because there needs to be a default quality level when outputting to JPEG. Do you mean to take the level of the original image? I'm not sure if this is detectable.

**Comment by sjahn90** [comment]
> I need some additional explanation; because there needs to be a default quality level when outputting to JPEG. Do you mean to take the level of the original image? I'm not sure if this is detectable.

**Comment by sjahn90** [comment]
Yes. I want to keep the level of the original image.

**Comment by kleisauke** [comment]
This is currently not possible. Please see for context:
https://github.com/libvips/libvips/issues/1932 (for JPEG images)
https://github.com/lovell/sharp/issues/2300#issuecomment-661127805 (for PNG images)
