### ISSUE TITLE
500 error fetching images for one domain

### ISSUE THREAD

**Issue by danrin** [andrieslouw/imagesweserv#264]
I'm trying to troubleshoot this with the domain owner, but cant really see beyond your 500 error. I suspect some issue with their CDN but could you check? some example url's:

https://images.weserv.nl/?url=www.arboss.nl%2Fwp-content%2Fuploads%2F2020%2F09%2Fhks-bfs-90.jpg
https://images.weserv.nl/?url=www.arboss.nl%2Fwp-content%2Fuploads%2F2020%2F12%2Fpuma-airtwist-black-low.jpg
https://images.weserv.nl/?url=www.arboss.nl%2Fwp-content%2Fuploads%2F2020%2F11%2FAlbatros-64.750-Impulse-AER55-Black-Blue-Low.jpg

**Comment by andrieslouw** [comment]
Strange, problem is not tied to our IP (servers can access the image), it could be some user-agent filtering, or a different problem. Will take a closer look!

**Comment by kleisauke** [comment]
The above images loads fine for me now, so perhaps this has been resolved upstream?

We were indeed sending upstream HTTP 500 response codes incorrectly as our own internal server error message, commit https://github.com/weserv/images/commit/66099378030ee4be895794a73e4c97aeaafc73db fixes this. For example, this produces the correct error message now:
https://images.weserv.nl/?url=httpstat.us/500

Thanks for reporting this!

**Comment by danrin** [comment]
Sorry for the late reply: it turned out to be an issue with their CDN as suspected. Thanks for improving the error message, that should help in the future!
