### ISSUE TITLE
Error 404 With Jekyll/Github pages Implementation

### ISSUE THREAD

**Issue by Kornosky** [andrieslouw/imagesweserv#267]
I'm attempting to set up an art gallery on my website but I keep getting a 404 error (more specifically:  `{"status":"error","code":404,"message":"The requested URL returned error: 404"}` ) 

Here's one of the failed links generated by my code:
https://images.weserv.nl/?url=www.kornosky.github.io/assets/img/artportfolio/%5Bwww.kornosky.site%5D%5B335%5Dchristopher-kornosky-final.jpg&w=600

And here is the code in question:
`<img src="//images.weserv.nl/?url={{ site.url | replace: 'http://','' | replace: 'https://','' }}{{ file.path | relative_url }}&w=300&h=300&output=jpg&q=50&t=square" alt="{{ filename }}" title="{{ filename }}" />`

From what I understand it's simply sending a request to the images.weserv.nl to resize the image at the address listed and then send it back (simply via a link). At one point it worked fine, so I'm 50% on whether it was something dumb that I've done. But from my limited understanding, everything looks like it should work. 

Any tips or troubleshooting ideas would be greatly appreciated!

**Comment by andrieslouw** [comment]
That's a strange link indeed, on what URL would the original image be viewed?

**Comment by andrieslouw** [comment]
Found it, you have an extra `www.` in your URL, this one works: https://images.weserv.nl/?url=kornosky.github.io%2Fassets%2Fimg%2Fartportfolio%2F%5Bwww.kornosky.site%5D%5B335%5Dchristopher-kornosky-final.jpg&w=600

Seems like `kornosky.github.io` doesn't like to be prefixed by another `www.`

**Comment by Kornosky** [comment]
Thank you so much! I should've been able to catch that. You've saved me hours of hassle. Okay well that's an issue I need to solve as well then, because sometimes when I go back to my home page it gives me a githubpages 404 message (http://www.kornosky.github.io/). But again, thank you so much!

**Comment by andrieslouw** [comment]
Maybe the value for `site.url` is not correct? I'm not entirely sure where the `www.` is coming from..

**Comment by dykuman** [comment]
Hi everyone,

I have similar problem with images.weserv.nl in Jekyll site. I hoste images myself. In Jekyll site some images works good and some doesn't work.  For example: http://pracepodwodne.pl/podwodne.html
Sometimes pictures witch now doesn't work, works but why I don't know?
Thanks for help.

**Comment by kleisauke** [comment]
The images on the above mentioned URL works for me. I'll close, please feel free to re-open if questions remain.
