### ISSUE TITLE
Error 1106 when requesting via Cloudflare Workers

### ISSUE THREAD

**Issue by AggressivelyMeows** [andrieslouw/imagesweserv#268]
The only data being returned from the API is "Error 1106", this includes on other routes such as "/quota". I have a feeling this might be a rate limit issue but i'm unable to get my remaining quota as the API refuses to serve my requests. Another feeling I have is that Workers are using shared IPs to fetch and the IP my worker is on has used too many images recently.

**Comment by AggressivelyMeows** [comment]
An example URL is: "https://media.spns.us/unicorn/smile.png?w=64". The subdomain points to a Worker that appends the S3 bucket to the path and runs it through images.weserv.nl. For 7 months this has worked without a problem, but ever since last night it has stopped working entirely.

**Comment by andrieslouw** [comment]
Sorry, this issue fell off our radar. Could be the rate limiting, will investigate.

**Comment by andrieslouw** [comment]
I guess the best way would be to whitelist CloudFlare Worker IP's from the rate limiter. Error 1106 is definitely due to blocking by rate limiting.

**Comment by andrieslouw** [comment]
Small update: We haven't found a reliable way to detect CloudFlare Worker IP's yet. The ranges are within CloudFlare's own ranges it seems, so it is a bit hard to filter them, as our whole service is behind CloudFlare CDN. We did updated the limits as per #196 .

**Comment by hakimihamdan88** [comment]
facing same issue, 1106 error code

**Comment by AggressivelyMeows** [comment]
An idea could be to implement some kind of authentication so that people who are using serverless APIs can use this service.

**Comment by kleisauke** [comment]
To prevent abuse of our service, whitelisting of CloudFlare Worker IPs will not happen. The use of an authentication mechanism to bypass the rate limiter is also beyond the scope of this project.

It is always possible to use our open source code, without filtering and limitations, on your own server.
