### ISSUE TITLE
Solution for updated images that are still in browser cache?

### ISSUE THREAD

**Issue by GitBoudewijn** [andrieslouw/imagesweserv#272]
Hello,

Love your service. So far I have come across just a single issue:

There's an image that has changed and when I go to the weserv url directly it shows that you also have the updated image in your cache, however in `<img>` tags it still shows the old image. I guess this is because of the browser cache and because you don't use Last-Modified/ETag headers.

In your FAQ it says this:

> You can always clear your browser cache. Unfortunately, it is not possible for us (or our servers) to clear your browser cache.

However, can't you just make an url like https://images.weserv.nl/clearcache which returns a Clear-Site-Data header? (See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data)

This way when this issue occurs you can just request that url to clear the cache.

**Comment by andrieslouw** [comment]
I will try this in our staging enviroment, and if it works like suggested, it would be a simple addition to create this. Thank you for the suggestion!

**Comment by kleisauke** [comment]
This has been implemented with commit https://github.com/weserv/images/commit/73c3b4784f662295ec108b69f7d592f1f86a4394, which has just been rolled out to production.
https://images.weserv.nl/clear-cache

Thanks for reporting this!
