### ISSUE TITLE
Resized animated image has different fps

### ISSUE THREAD

**Issue by fabian-emilius** [andrieslouw/imagesweserv#275]
We use a self hosted version of this software and it seems that the fps change after resizing the image.

Original Image:
https://cloudflare-ipfs.com/ipfs/QmYmPLnTEDwD8CwVSFjgWUpUHWV1DUxrMKWnMeHeHXgLCQ

Resized Image: 
https://images.weserv.nl/?h=370&w=370&fit=inside&we&q=75&output=webp&n=-1&url=https://cloudflare-ipfs.com/ipfs/QmYmPLnTEDwD8CwVSFjgWUpUHWV1DUxrMKWnMeHeHXgLCQ

(uploaded result: https://cloudflare-ipfs.com/ipfs/QmUGwA3zJkyTyeU29R3MY2s1SccTiZ5hgSvSh9FXkDogaY because its not visible on the public endpoint)

The resized image animation is a lot faster than on the original one. On the public endpoint it seems that the source image is too large but it works on our private one.

**Comment by kleisauke** [comment]
Thanks for the report, PR https://github.com/libvips/libvips/pull/2145 should resolve this. For now, you can workaround this by appending [the undocumented](https://github.com/weserv/images/blob/5e1ea90eba7110395300a6e51d0e83d5212c4d0f/src/api/parsers/query.cpp#L68-L70) `&delay=100` parameter to the URL.

**Comment by fabian-emilius** [comment]
Seems like it was merged. Does it has to be updated here as well or will it just work?

**Comment by kleisauke** [comment]
That PR is part of the libvips v8.10.6 release (which will probably be released in a couple of days). It should be automatically integrated into the Docker image after this version lands on [Remi's RPM repository](https://rpms.remirepo.net/).

You could try to compile libvips from the [`8.10` branch](https://github.com/libvips/libvips/tree/8.10) if you want to test this earlier.

**Comment by kleisauke** [comment]
libvips v8.10.6 has been landed on [Remi's RPM repository](https://rpms.remirepo.net/) with commit [`0cc4753`](https://git.remirepo.net/cgit/rpms/lib/vips.git/commit/?id=0cc47534ff96da2eafd8efb9bc07ec6dcabf5c45), so a recompilation of the Docker image should automatically pick this up.

You could also use the prebuilt Docker image available on GitHub's Container Registry:
https://github.com/orgs/weserv/packages/container/package/images
