### ISSUE TITLE
Webp animation is overlapping

### ISSUE THREAD

**Issue by fabian-emilius** [andrieslouw/imagesweserv#278]
The resized image has overlapping frames:

https://images.weserv.nl/?h=370&w=370&fit=inside&we&q=75&output=webp&n=-1&url=https://cloudflare-ipfs.com/ipfs/QmZ2czWvjhiiGoAyL3qSqWN7mSxY5J2ACAmXaPaELodUkh

Original: https://cloudflare-ipfs.com/ipfs/QmZ2czWvjhiiGoAyL3qSqWN7mSxY5J2ACAmXaPaELodUkh

**Comment by kleisauke** [comment]
It looks like `DISPOSE_PREVIOUS` is not handled correctly in the GIF loader of libvips 8.10 (which is based upon giflib). libvips master has switched to libnsgif, which handles this image correctly.

**Comment by fabian-emilius** [comment]
So it will work again if I rebuild the docker image?

**Comment by kleisauke** [comment]
No, you'll have to wait for libvips 8.11 or build libvips from source within the Docker image.

**Comment by fabian-emilius** [comment]
Mmh I do not really get it to work properly when compiling from master. Is there any hope that a fix for this is available soon?

**Comment by kleisauke** [comment]
libvips version 8.11.0-rc1 is now available for testing at [Remi's RPM repository](https://rpms.remirepo.net/) (see https://github.com/remicollet/remirepo/issues/171). To test this, this change in the Dockerfile is needed:
```diff
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -36,10 +36,11 @@ RUN dnf install -y epel-release \
     && dnf config-manager --set-enabled remi \
     && dnf install -y --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm \
     && rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-8  \
-    && dnf install -y --setopt=tsflags=nodocs \
+    && dnf install -y --enablerepo=remi-test --setopt=tsflags=nodocs \
         git \
         cmake \
-        vips-full-devel \
+        vips-devel \
+        vips-magick-im6 \
         make \
         gcc \
         gcc-c++ \
```

fwiw, this new version of libvips has been deployed on April 26th at [images.weserv.nl](https://images.weserv.nl/).

**Comment by kleisauke** [comment]
libvips v8.11.0 has been landed on [Remi's RPM repository](https://rpms.remirepo.net/) with commit [`0654a74`](https://git.remirepo.net/cgit/rpms/lib/vips.git/commit/?id=0654a74c50ca863b464accacc9b0fdafacabf9e5). I've updated the RPM packages names with https://github.com/weserv/images/commit/40cc52cecad6664bbb37dccfad34e2265fb2d492, so a recompilation of the Docker image should automatically pick this up.

You could also use the prebuilt Docker image available on GitHub's Container Registry:
https://github.com/orgs/weserv/packages/container/package/images
