### ISSUE TITLE
Slow responses with 522 errors

### ISSUE THREAD

**Issue by lincolnthree** [andrieslouw/imagesweserv#281]
Hi there!

Thanks again for your amazing service.

As per issue https://github.com/weserv/images/issues/211, I am reporting that we're seeing a lot of 522 errors from `images.weserv.nl` currently. Looks like CloudFlare may be having some issues: https://www.cloudflarestatus.com/?_ga=2.49098022.1024970801.1580152244-f65b9b4d41bec4f33bfa4302bc2d1ac0

Not sure what other information would be useful! Let me know if this is helpful, or what else I can provide.

**Comment by lincolnthree** [comment]
![image](https://user-images.githubusercontent.com/362329/115924477-c46f5600-a44d-11eb-98eb-afde659e2d4b.png)

**Comment by andrieslouw** [comment]
We spotted some abuse of our public service, which caused slow response times for other users, and have taken the necessary steps to resolve this.

**Comment by andrieslouw** [comment]
Everything is stable since we took the measures to prevent abuse. Thank you for reporting!
