### ISSUE TITLE
The hostname of the origin is unresolvable (DNS) or blocked by policy

### ISSUE THREAD

**Issue by gabriel254** [andrieslouw/imagesweserv#286]
https://images.weserv.nl/?url=https://wx1.sinaimg.cn/large/0074wS7Fly1gpz4o4pg2qj30zg0se7wh.jpg&output=webp&w=1080
https://images.weserv.nl/?url=https://wx2.sinaimg.cn/large/0074wS7Fly1gpz4o4pg2qj30zg0se7wh.jpg&output=webp&w=1080
https://images.weserv.nl/?url=https://wx3.sinaimg.cn/large/0074wS7Fly1gpz4o4pg2qj30zg0se7wh.jpg&output=webp&w=1080
https://images.weserv.nl/?url=https://wx4.sinaimg.cn/large/0074wS7Fly1gpz4o4pg2qj30zg0se7wh.jpg&output=webp&w=1080
```json
{
  "status": "error",
  "code": 404,
  "message": "The hostname of the origin is unresolvable (DNS) or blocked by policy."
}
```

`sinaimg.cn` is the image server of [Weibo](https://en.wikipedia.org/wiki/Sina_Weibo), the China's largest social media platform like Twitter. Why is it blocked?

**Comment by andrieslouw** [comment]
Thanks for the report, added it to a whitelist. Sorry for the trouble caused. Should work again!

**Comment by happy-tao** [comment]
[https://images.weserv.nl/?url=https://img9.doubanio.com/view/photo/l_ratio_poster/public/p2626959989.jpg](https://images.weserv.nl/?url=https://img9.doubanio.com/view/photo/l_ratio_poster/public/p2626959989.jpg)

douban, The China's largest movie & tv paltform like imdb. It's block too.

**Comment by baoziii** [comment]
https://images.weserv.nl/?url=https://s1.hdslb.com/bfs/seed/jinkela/footer-v2/images/partner.png
Bilibili, The popular video platform in China also be blocked.

**Comment by gabriel254** [comment]
Thanks, the `sinaimg.cn` is working now. But some popular services like Douban and Bilibili are also blocked. It works fine a few days ago. Maybe there are some bugs in your blacklist system?

> https://images.weserv.nl/?url=https://img9.doubanio.com/view/photo/l_ratio_poster/public/p2626959989.jpg
> 
> douban, The China's largest movie & tv paltform like imdb. It's block too.



> https://images.weserv.nl/?url=https://s1.hdslb.com/bfs/seed/jinkela/footer-v2/images/partner.png
> Bilibili, The popular video platform in China also be blocked.

**Comment by andrieslouw** [comment]
Both are whitelisted, thanks for the report. We've had quite some abuse of our service, and our measures where a bit unconventional. We eventually resorted to using scripts to block a high amount of seemingly randomly generated domains that where misabusing the public service, and thus where evading the OpenDNS blocklists. But using these scripts also caught some legitimate traffic.

**Comment by Jay8023** [comment]
https://images.weserv.nl/?url=https://thumb807.jfcdns.com/thumb/n131032418v38/7ef60fff21348a1f_160_160.png
This address cannot be requested successfully！

**Comment by artjom-lipak** [comment]
Hi, could you please whitelist this domain?

file://images.weserv.nl/?url=https://questory.app/uploads/pr-da-is-dh-ma.jpg

**Comment by ardinusawan** [comment]
@andrieslouw hi please whitelist storj.io

I cannot open this https://cdn.tanggalnya.com/?url=https://link.us1.storjshare.io/raw/jvmch7aj5gmmt7xuzdopt2frjerq/website/promo/promo-17-aug-2022.jpg

![image](https://user-images.githubusercontent.com/7924043/184899442-78846159-1c54-4330-911b-945268305d58.png)

**Comment by andrieslouw** [comment]
@ardinusawan : I don't see any problem with:
https://images.weserv.nl/?url=link.us1.storjshare.io/raw/jvmch7aj5gmmt7xuzdopt2frjerq/website/promo/promo-17-aug-2022.jpg

Are you sure you're using https://images.weserv.nl/ ? Because many other websites use our source-code 😄

**Comment by ardinusawan** [comment]
> @ardinusawan : I don't see any problem with:
> 
> https://images.weserv.nl/?url=link.us1.storjshare.io/raw/jvmch7aj5gmmt7xuzdopt2frjerq/website/promo/promo-17-aug-2022.jpg
> 
> 
> 
> Are you sure you're using https://images.weserv.nl/ ? Because many other websites use our source-code 😄

I use docker-compose to deploy on my server and adding dns: 1.1.1.1 in it seems resolve the issue. Thanks for checking 🙏

**Comment by XuLLlHuK** [comment]
Hi!
Recently we've got the same problem with "The hostname of the origin is unresolvable (DNS) or blocked by policy." error with domain freerooms.7811178.ru (https://images.weserv.nl/?url=https://freerooms.7811178.ru/...)
I didn't find any cause on hosting or in CMS (WordPress). One or two weeks ago it worked fine.
Maybe we got somehow into your blacklist.
Could you please help to find the reason out?
Thank you in advance!

**Comment by PhotoPaul** [comment]
Hello @andrieslouw ,
I'm also facing the same problem with https://tbp-video.s3.amazonaws.com

An example would be: https://wsrv.nl/?h=720&url=https://tbp-video.s3.amazonaws.com/localized/ell/poster/john_13-21/06_Greek_John_Poster_001.jpg

The original images are quite large, but once the thumbnails are generated and cached I'm not expecting major traffic.

Can you please whitelist it as well?
Thank you.

**Comment by eyezahhhh** [comment]
Having the same issue with [https://cosmetica.cc](https://cosmetica.cc).
One such image is [https://cosmetica.cc/page/splash/Eyezah-Bottom-2.jpg](https://cosmetica.cc/page/splash/Eyezah-Bottom-2.jpg).
If you could whitelist my domain that would be great, thanks!
