### ISSUE TITLE
The hostname of the origin is unresolvable (DNS) or blocked by policy

### ISSUE THREAD

**Issue by darkboy245** [andrieslouw/imagesweserv#287]
https://images.weserv.nl/?url=//www.forums.gamers-israel.co.il/core/images/default/default_avatar_large.png

First time trying to use weserv on my site, would appreciate the help!

**Comment by andrieslouw** [comment]
There are two problems, first you should remove the `//` in the `?url=`:
https://images.weserv.nl/?url=www.forums.gamers-israel.co.il/core/images/default/default_avatar_large.png

But then we get a 403 error from `www.forum.gamers-israel.co.il`. It looks like they also use CloudFlare, which is blocking our server. This should be solved by the owner of `www.forum.gamers-israel.co.il` by allowing our service IP's: https://images.weserv.nl/ips.txt

**Comment by fivefilters** [comment]
I've noticed a bunch of *.wp.com subdomains which host images for WordPress sites (e.g. i0.wp.com, i1.wp.com, i2.wp.com) are also blocked by images.weserve.nl - used to work a couple of weeks ago. I don't know if that's a block on your end or if it's wp.com refusing access. Happy to provide full URLs if you need them.

**Comment by andrieslouw** [comment]
@fivefilters : We've had problems with users bypassing our blocklist(s) by abusing the [WordPress Photon](https://developer.wordpress.com/docs/photon/) service. This is also against the TOS of WordPress, so we blocked `i0/i1/i2.wp.com` to prevent this. You can use Photon or you can use `images.weserv.nl`. There is no reason to use both, but if you want to use both, you can use the source code provided.

**Comment by fivefilters** [comment]
@andrieslouw Thanks for the reply. I didn't realise they belonged to a similar service to yours - I assumed they hosted images for the WordPress.com service. I checked the URLs that weren't loading and they are self-hosted WordPress blogs, so they're probably using the Jetpack service. I'll look into special handling of those URLs then, or hosting your code ourselves.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
