### ISSUE TITLE
imgbb.com & postimages.org not working

### ISSUE THREAD

**Issue by TCboxa** [andrieslouw/imagesweserv#288]
https://postimages.org/
https://imgbb.com/
Both stopped working yesterday and 404, other image hosts are working. I think they may have been blocked again.

An example image hosted on https://imgbb.com/ that won't display is here https://i.ibb.co/7C88jYr/vlcsnap-2021-05-01-14h25m58s386.png

**Comment by andrieslouw** [comment]
Sorry, both are flagged for pornography by OpenDNS. We block this category on our public service. You can use our source code to host your own version without blocking.

See:
https://domain.opendns.com/postimg.org
https://domain.opendns.com/ibb.co

**Comment by xSlOom** [comment]
I was about to ask for postimage but found this!

Thank you for the clarification.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
