### ISSUE TITLE
Image fetching from WordPress Photon (i*.wp.com) blocked

### ISSUE THREAD

**Issue by danrin** [andrieslouw/imagesweserv#290]
Hi,
I noticed a 404 on url's from wp's hosted service, but when the image is requested directly from the customer domain it does work. Can you check what goes wrong, other than maybe policy on their end? other services seem to be able to fetch the images fine on from that domain, so i was thinking maybe the url itself poses a problem here. 
url that doesnt work: https://images.weserv.nl/?url=ssl:i0.wp.com%2Fwww.bybenedicte.nl%2Fwp-content%2Fuploads%2F2020%2F04%2Fp0581_2.jpeg%3Ffit%3D1000%2C1500%26ssl%3D1&w=75&h=65
same url but 'directly', which works: https://images.weserv.nl/?url=ssl:www.bybenedicte.nl%2Fwp-content%2Fuploads%2F2020%2F04%2Fp0581_2.jpeg%3Ffit%3D1000%2C1500%26ssl%3D1&w=75&h=65

**Comment by andrieslouw** [comment]
Explanation in #287:

> We've had problems with users bypassing our blocklist(s) by abusing the [WordPress Photon](https://developer.wordpress.com/docs/photon/) service. This is also against the TOS of WordPress, so we blocked `i0/i1/i2.wp.com` to prevent this. You can use Photon or you can use `images.weserv.nl`. There is no reason to use both, but if you want to use both, you can use the source code provided.

_Originally posted by @andrieslouw in https://github.com/weserv/images/issues/287#issuecomment-830845525_

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
