### ISSUE TITLE
self certificate

### ISSUE THREAD

**Issue by hakimihamdan88** [andrieslouw/imagesweserv#294]
I just installed on ubuntu docker, and any idea how to install self certificate on docker?

**Comment by andrieslouw** [comment]
Please see https://certbot.eff.org/docs/install.html and look on that page for `Docker`, it should explain how to do this using free (self) certificates from LetsEncrypt.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
