### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by aletuba** [andrieslouw/imagesweserv#296]
I have been using the service for a long time, however since yesterday I keep getting a 404 error: {"status":"error","code":404,"message":"The requested URL timed out."}

Here's one of the failed links: https://images.weserv.nl/?url=https://www.apartamentosnoklabin.com.br/fotos_imoveis/2017/2018.12.04-16.36.56-6.jpg

Any tips or troubleshooting ideas would be greatly appreciated!

**Comment by andrieslouw** [comment]
It seems the server behind `apartmentos___.com.br` had some temporary problems. Looks fine now.
