### ISSUE TITLE
Error 404 

### ISSUE THREAD

**Issue by laurencebedford** [andrieslouw/imagesweserv#297]
https://images.weserv.nl/?url=https://www.innvictus.com/medias/IN-FY7393-1.png?context=bWFzdGVyfGltYWdlc3wxODIwfGltYWdlL3BuZ3xpbWFnZXMvaDZmL2gwMC8xMDIwMzg0OTM5MjE1OC5wbmd8M2RiZDY5YTY0ZmI1MmY5ZmE1M2U4OTFlYmJjZDEzYzJiMzExNWE3MTlmMmZkNzdiOWY2ZGE3ZjM2M2VmZmJiMw

I get an error 404 when using that URL

**Comment by andrieslouw** [comment]
You should urlencode the url, or at least `?` to `%3F`: https://images.weserv.nl/?url=https://www.innvictus.com/medias/IN-FY7393-1.png%3Fcontext=bWFzdGVyfGltYWdlc3wxODIwfGltYWdlL3BuZ3xpbWFnZXMvaDZmL2gwMC8xMDIwMzg0OTM5MjE1OC5wbmd8M2RiZDY5YTY0ZmI1MmY5ZmE1M2U4OTFlYmJjZDEzYzJiMzExNWE3MTlmMmZkNzdiOWY2ZGE3ZjM2M2VmZmJiMw

Even better: https://images.weserv.nl/?url=https%3A%2F%2Fwww.innvictus.com%2Fmedias%2FIN-FY7393-1.png%3Fcontext%3DbWFzdGVyfGltYWdlc3wxODIwfGltYWdlL3BuZ3xpbWFnZXMvaDZmL2gwMC8xMDIwMzg0OTM5MjE1OC5wbmd8M2RiZDY5YTY0ZmI1MmY5ZmE1M2U4OTFlYmJjZDEzYzJiMzExNWE3MTlmMmZkNzdiOWY2ZGE3ZjM2M2VmZmJiMw

But the origin has blocked non-browsers as a form of DDoS protection. See for example: https://redbot.org/?uri=https%3A%2F%2Fwww.innvictus.com%2Fmedias%2FIN-FY7393-1.png%3Fcontext%3DbWFzdGVyfGltYWdlc3wxODIwfGltYWdlL3BuZ3xpbWFnZXMvaDZmL2gwMC8xMDIwMzg0OTM5MjE1OC5wbmd8M2RiZDY5YTY0ZmI1MmY5ZmE1M2U4OTFlYmJjZDEzYzJiMzExNWE3MTlmMmZkNzdiOWY2ZGE3ZjM2M2VmZmJiMw#

**Comment by kleisauke** [comment]
All the above URLs seem to work now, I'll close this issue.
