### ISSUE TITLE
OpenDNS tag filtering on rejected tags?

### ISSUE THREAD

**Issue by adamjudd** [andrieslouw/imagesweserv#303]
Hi all,

I just wanted to clarify on how the OpenDNS tag filtering works with weserv. I understand it's doing some automatic blocking of requests with specific tags (like pornography) to minimise potential for weserv being blocked itself by other systems. Does your blocking take into account the status of the tag? For example, if the tag has a `Rejected` status, is that then ignored for the purposes of your blocking?

Also, is there a current list for what tags domains are being blocked for?

Thanks!

**Comment by andrieslouw** [comment]
Please see https://github.com/weserv/images/issues/285#issuecomment-828176654

As far as I know, tags with status "Unapproved" or "Rejected" are not blocked.

**Comment by adamjudd** [comment]
@andrieslouw - thank you for confirming!
