### ISSUE TITLE
Status Code 404 With Message 'The requested URL returned error: 503'

### ISSUE THREAD

**Issue by kokog4mi** [andrieslouw/imagesweserv#304]
HI!
What can be the problem why I'm getting 404 status code trying to use this image link:
https://images.weserv.nl/?url=https://img.pccomponentes.com/articles/24/249924/serike-tk0l.jpg
Original image : https://img.pccomponentes.com/articles/24/249924/serike-tk0l.jpg
I also tried 'http' instead 'https'
Thanks.

**Comment by kleisauke** [comment]
This origin website has blocked non-browsers as a form of DDoS protection. Here's a part of the response:
```html
          <div class="attribution">
            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
            <br />
            <span class="ray_id">Ray ID: <code>68b771cb9f501f95</code></span>
          </div>
```
This can also be verified using REDbot:
https://redbot.org/?uri=https://img.pccomponentes.com/articles/24/249924/serike-tk0l.jpg

There's not much we can do about this unfortunately. Embedding this image within a website will not work either unless a user has visited this website before. Please report this to the origin website if it continues to be a problem.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
