### ISSUE TITLE
I use faulty by pass. please help me

### ISSUE THREAD

**Issue by triiieubuiii** [andrieslouw/imagesweserv#307]
I use faulty by pass. please help me
![Capture](https://user-images.githubusercontent.com/88609051/133063317-11859a80-c85f-4750-ae3b-87d5e12a29c7.JPG)

**Comment by andrieslouw** [comment]
All Truyen* domains are blocked by our proxy, due to heavy abuse and DMCA requests. This is the reason you see 204.
