### ISSUE TITLE
Shorter URLs?

### ISSUE THREAD

**Issue by GitBoudewijn** [andrieslouw/imagesweserv#308]
Sometimes the URL can get really long, especially when you use `&default=images.weserv.nl/...`.

So maybe you could have _weserv.nl_ and/or _i.weserv.nl_ as an alias for _images.weserv.nl_?

**Comment by andrieslouw** [comment]
Good suggestion!

@kleisauke: Candidate could be `wsrv.nl` or `i.wsrv.nl`, that domain is not in use for any other project anymore.

**Comment by GitBoudewijn** [comment]
That would be even better!

I was going to suggest doing like Photon and having _i0.wsrv.nl_, _i1.wsrv.nl_ and _i2.wsrv.nl_ or just allowing any subdomain but apparently with HTTP2 that doesn't have any benefit anymore. Maybe you could just have subdomains redirect to _wsrv.nl_ or _i.wsrv.nl_ (like Imgur does).

**Comment by kleisauke** [comment]
https://wsrv.nl/ is available for this purpose and is preferred over https://images.weserv.nl/ within the docs. I'll close.
