### ISSUE TITLE
Add Timing-Allow-Origin header

### ISSUE THREAD

**Issue by GitBoudewijn** [andrieslouw/imagesweserv#311]
It would be nice if images had a `Timing-Allow-Origin: *` response header.

See here for an explanation:

https://developer.akamai.com/blog/2018/06/13/how-add-timing-allow-origin-headers-improve-site-performance-measurement

**Comment by andrieslouw** [comment]
Thank you, will check this!

**Comment by kleisauke** [comment]
This has been implemented with commit https://github.com/weserv/images/commit/8ef0fb99021e1aa8bcd7bfcbd2a0b7e41c1bcf4c, which has just been rolled out to production. Thanks for reporting this!
