### ISSUE TITLE
Imgur issue ?

### ISSUE THREAD

**Issue by xSlOom** [andrieslouw/imagesweserv#319]
Hello,

We  are facing (again) an issue with Imgur.

Weserv is giving an error 429. Can you take a look at why it doesn't work ? 

Example of picture: https://images.weserv.nl/?h=30&url=https://i.imgur.com/jSy8UOD.jpg

Thank you!

**Comment by andrieslouw** [comment]
Imgur is rate-limiting requests nowadays, and our public service only runs on a handful of IP-adresses. There is not much we can do about this.

You could host the service yourself.

**Comment by xSlOom** [comment]
Ok thanks for the information !
