### ISSUE TITLE
Check accepted user-agent content types

### ISSUE THREAD

**Issue by gradyskyi** [andrieslouw/imagesweserv#321]
Great service! 
It would be wonderful to add some optional parameter, witch will check acceptable user-agent content types for format converting.
So if I set "&output=webp&**accept=true**", for example, service will check **Accept** user-agent header for **webp** format, and if user-agent doesn't support requested format, service will ignore **output=webp** parameter.
Thanks!

**Comment by kleisauke** [comment]
Due to Cloudflare's caching it's technically impossible to change the output depending on the type browser. Please use the `<picture>`-tag as explained in https://github.com/weserv/images/issues/214.
