### ISSUE TITLE
using a WordPress plugin: Podcast Feed Player Widget & Shortcode, and the thumbnails were saved as massive PNGs

### ISSUE THREAD

**Issue by 3cstudio** [andrieslouw/imagesweserv#324]
... now, I have replaced all Featured Images that were once massive PNG files for MUCH smaller JPEGs, but it appears those PNG images are still cached by WeServ -- I really need to clear those cached files, as the images must have clearly exceeded an unknown quota and no longer show on: AntiochPodcast.org -- can anyone advise as to how to do this? I have found no documentation (other than "the option to clear cached images is a potential feature for the future") and the plugin developer has not responded to inquiries for a month+... Your thoughts and advice is much appreciated!
Steve C.
3Cstudio

**Comment by kleisauke** [comment]
If you want, you can send us an [email](mailto:admin@weserv.nl) with the images that are affected and need to be purged from cache.

**Comment by 3cstudio** [comment]
Oh? Send an email of the image file names, or the images themselves? And should I use WeTransfer.com to send them (as they were many & large!) if you need the actual image files themselves? To give you further insight, here is a sampling of the imagery that was replaced (larger PNG files for reduced size JPEGs):
-- Episode 57: https://antiochpodcast.org/podcast/episode-57-an-antioch-encore-institutional-reconciliation/
-- here's the PNG mage formerly associated with that episode: https://antiochpodcast.org/wp-content/uploads/2019/06/Screen-Shot-2019-06-20-at-10.35.19-AM.png (2MB)
-- it's since been replaced with the much smaller JPEG: https://antiochpodcast.org/wp-content/uploads/2021/10/057.jpg (245KB)

So, as you can see, there are nearly 100 images that were originally uploaded as the WordPress Featured Image for episodes before I realized the client was doing that and the WeServ caching quota had apparently been exceeded. Please clarify what you would like for me to send you -- list of images / names that should be purged from cache, or actual image files that can be deleted from cached lists. I'll get either setup sent to admin@weserv.nl straightaway... 
Thanks so much for your assistance!
Steve

**Comment by kleisauke** [comment]
Thanks for the details! It looks like this is not a caching issue, the above mentioned page is using both WordPress Photon and images.weserv.nl, which cannot be used simultaneously. See #290 for more details.

**Comment by 3cstudio** [comment]
Ahhhh.... that makes sense! Thank you, @kleisauke  -- I went into the WP admin area and turned off the Jetpack (from WordPress) feature for: Performance & Speed > Enable site accelerator > Speed up image load times (thinking that must be where Photon comes into use: https://jetpack.com/support/site-accelerator/) . . . but this didn't resolve the issue.  Might there be a propagation period or cache-clearing timeframe involved, and I should wait a day or so? Thanks again for your input!

**Comment by kleisauke** [comment]
The images on the above mentioned URL works for me now. I'll close, please feel free to re-open if questions remain.
