### ISSUE TITLE
GIF to WebP causes increased file size

### ISSUE THREAD

**Issue by Sir-Will** [andrieslouw/imagesweserv#328]
When using the image server to convert a GIF to WebP, I have noticed that the WebP file is larger than the original GIF.

What causes the increased file size? Shouldn't it be smaller?

Example:
  https://images.weserv.nl/?url=https://i.ibb.co/ch2v7wk/1b9770514b2c82f47bf60baf1bc007c6.gif&n=-1&output=webp
  https://i.ibb.co/ch2v7wk/1b9770514b2c82f47bf60baf1bc007c6.gif

**Comment by kleisauke** [comment]
WebP images can be optimized by setting the quality (`&q=`) parameter.  For example, adding `&q=60` to the first URL will make the WebP image smaller than the GIF image in size. By default a quality of `80` is used, which usually produces excellent results.

Perhaps the provided GIF image was optimized with something like [Gifsicle](https://github.com/kohler/gifsicle)?

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.

**Comment by Sir-Will** [comment]
I ended up converting them to mp4, as I wasn't able to get the gif smaller than a mp4.
