### ISSUE TITLE
Lots of 204 responses

### ISSUE THREAD

**Issue by ebaynaud** [andrieslouw/imagesweserv#330]
Hi there, thanks a lot for your awesome work.

Starting today, I keep getting 204 responses when loading images from my app pages (app.alobees.com):

![Screenshot 2022-02-07 at 18 55 50](https://user-images.githubusercontent.com/1921301/152844717-8e3ae499-e29c-4f04-be45-9a62d6ac45b9.png)

If I open the image URL directly in the browser, the image displays well and refreshing the initial page, I get a 200 and it now shows better:

![Screenshot 2022-02-07 at 18 56 40](https://user-images.githubusercontent.com/1921301/152844867-57b8a3b5-6713-4bdd-b61f-1cc17f910cef.png)

But all other images still get 204. Any idea?

**Comment by andrieslouw** [comment]
Our automated system to block abuse flagged some traffic, and made rules that blocked a bit too much. I'll spare you the details, but somewhere a regular expression got a bit too inclusive, and your request payload was matching this.

The 204 is send by this system as a last resort to prevent users from hogging resources, it's the fastest way of telling the client to keep going and ignore the response, but normal use should not trigger this.

Should be fixed now, could you verify this?

**Comment by ebaynaud** [comment]
Yes it looks ok now, thank you so much for your reactivity.

**Comment by andrieslouw** [comment]
No problem, thanks for the report!
