### ISSUE TITLE
The hostname of the origin is unresolvable (DNS) or blocked by policy

### ISSUE THREAD

**Issue by artjom-lipak** [andrieslouw/imagesweserv#331]
Hi, could you please whitelist this domain?

https://images.weserv.nl/?url=https://questory.app/uploads/pr-da-is-dh-ma.jpg

{"status":"error","code":404,"message":"The hostname of the origin is unresolvable (DNS) or blocked by policy."}

**Comment by kleisauke** [comment]
It looks like the resolved IPv4 address of `questory.app` is unreachable by our servers.
```bash
$ nslookup questory.app
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   questory.app
Address: 141.136.43.13
Name:   questory.app
Address: 2a02:4780:a:542:0:2fc2:28f:1

$ ping -w 5 141.136.43.13
ping -w 5 141.136.43.13
PING 141.136.43.13 (141.136.43.13) 56(84) bytes of data.

--- 141.136.43.13 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4070ms
````

Our IP addresses that we use for outbound traffic (listed [here](https://images.weserv.nl/ips.txt)) are most likely blocked by this web host. Although, this domain resolves also to a IPv6 address which seems to work fine.
```bash
$ ping6 -w 5 2a02:4780:a:542:0:2fc2:28f:1
PING 2a02:4780:a:542:0:2fc2:28f:1(2a02:4780:a:542:0:2fc2:28f:1) 56 data bytes
64 bytes from 2a02:4780:a:542:0:2fc2:28f:1: icmp_seq=1 ttl=55 time=23.9 ms
64 bytes from 2a02:4780:a:542:0:2fc2:28f:1: icmp_seq=2 ttl=55 time=23.9 ms
64 bytes from 2a02:4780:a:542:0:2fc2:28f:1: icmp_seq=3 ttl=55 time=23.9 ms
64 bytes from 2a02:4780:a:542:0:2fc2:28f:1: icmp_seq=4 ttl=55 time=24.1 ms
64 bytes from 2a02:4780:a:542:0:2fc2:28f:1: icmp_seq=5 ttl=55 time=23.10 ms

--- 2a02:4780:a:542:0:2fc2:28f:1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4004ms
rtt min/avg/max/mdev = 23.879/23.957/24.140/0.219 ms
```

Browsers typically use a DNS failover implementation whenever this occurs (see https://serverfault.com/a/852421).

I just implemented something similar with commit d9b0cefa98f6c689e8210dad4d8ae49fc7965280, which has just been rolled out to production. The above image now loads properly for me.

**Comment by wuizard** [comment]
Hello @kleisauke ..
I've just found that, today The page always shown cloudflare 522 connection timeout page

for example, when i call this link https://images.weserv.nl/?url=https://questory.app/uploads/pr-da-is-dh-ma.jpg . it shows 522 too.

**Comment by eldario** [comment]
We have the same problems.
In response, we get **522**.

**For example**:
https://images.weserv.nl/?url=avatars.githubusercontent.com/u/47894183

**Single image**:
https://avatars.githubusercontent.com/u/47894183

**Comment by finesofttech** [comment]
I am also facing same issue here in India, always showing cloudflare "Error 504, Gateway time out"
Please fix the issue.

**Comment by andrieslouw** [comment]
There are some issues indeed, we're looking into them.

**Comment by wuizard** [comment]
Hi @andrieslouw  .. just want to confirm that is working fine now .. Thank you for you and your team quick response.

**Comment by eldario** [comment]
@andrieslouw 

Thank you very much, everything works!

**Comment by aoaostar** [comment]
@kleisauke 
I have the same problem with my domain name.
https://images.weserv.nl/?url=https://pic.v8cdn.cc/5556c6963001291.jpg
https://images.weserv.nl/?url=https://i.v8cdn.cc/i/5556c6967001291.jpg

**Comment by andrieslouw** [comment]
@aoaostar 
Due to multiple, and continuing, abuse of our service from many randomly generated cheap domains, we blocked all .cc .club .date .fun .pw .top .xxx .xyz domains on our public service. I'm really sorry for this, but the abuse was continuously using over 2 Gbit/s of our bandwidth, which we provide for free. Please consider changing domains to a normal TLD, or hosting the service yourself.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
