### ISSUE TITLE
204 Response when loading images from website

### ISSUE THREAD

**Issue by DouweHof** [andrieslouw/imagesweserv#332]
Hey,

Recently we started to get signals of images that were not loading on our websites. The weird thing is that accessing the image source url directly from the browser, everything works fine. The image is then also cached, after which it can be loaded by the webpage. After looking through the issues on this repo, I found this to be similar to issue #330. 

Here is a screenshot of the request data when trying to load the image from the website:
<img width="748" alt="Screenshot 2022-02-23 at 17 20 17" src="https://user-images.githubusercontent.com/48027557/155361251-7c8295ec-b051-4e86-8792-dfc14b71cf66.png">

And here is a screenshot of the request data when accessing the url same source url directly from the browser:
<img width="748" alt="Screenshot 2022-02-23 at 17 21 30" src="https://user-images.githubusercontent.com/48027557/155361423-b3fdf242-200c-4d78-920e-0f972201281a.png">

**Comment by andrieslouw** [comment]
Repetition of #330 
@kleisauke is looking into it now

**Comment by kleisauke** [comment]
Should be fixed now, could you verify this?

**Comment by DouweHof** [comment]
I've given it a quick look, everything seems to be fine now. Thanks for looking into it so quickly, it is very appreciated!
