### ISSUE TITLE
"Without enlargement" (`&we`) allow enlargement for vectors

### ISSUE THREAD

**Issue by Rongronggg9** [andrieslouw/imagesweserv#333]
In most cases, we need to resize an image without enlargement is just because the enlargement does not bring any improvement. However, if the original image is a vector image (e.g., SVG, PDF), that's a whole different story.

What about adding a new param `allow-vectors` or `only-raster` to `&we`, resizing any raster images without enlargement, but in the meantime allowing vector images to be enlarged?

**Comment by kleisauke** [comment]
We do not plan to add dedicated option values to our API that could produce a different image based on the image type, as that would certainly over-complicate things and cause confusion (even if it is opt-in).

Aside from this being an uncommon use case, is there a reason why you can't just omit the `&we` option when resizing vector-based images?

**Comment by Rongronggg9** [comment]
> We do not plan to add dedicated option values to our API that could produce a different image based on the image type, as that would certainly over-complicate things and cause confusion (even if it is opt-in).

OK. I agree with you.

> why you can't just omit the &we option when resizing vector-based images?

If you just get tons of external URLs, but no more information about these images, sometimes it is hard to guess their format from the URLs. The only way is to fetch their response headers to get the Content-Type, which slightly increases the server loads.

**Comment by kleisauke** [comment]
Closing for the reasons stated above.

Feel free to implement this feature and running the source code yourself.
