### ISSUE TITLE
document how to pass in urls with ? / & marks

### ISSUE THREAD

**Issue by abubelinha** [andrieslouw/imagesweserv#334]
Original image url (from IIIF server):
https://merovingio.c2rmf.cnrs.fr/fcgi-bin/iipsrv.fcgi?FIF=PIA03883.pyr.tif&WID=800&CVT=jpeg

I guess this fails because there is a "`?`" in the original url?
https://images.weserv.nl/?url=merovingio.c2rmf.cnrs.fr/fcgi-bin/iipsrv.fcgi?FIF=PIA03883.pyr.tif&WID=800&CVT=jpeg

```
// 20220310130335
// https://images.weserv.nl/?url=merovingio.c2rmf.cnrs.fr/fcgi-bin/iipsrv.fcgi?FIF=PIA03883.pyr.tif&WID=800&CVT=jpeg

{
  "status": "error",
  "code": 404,
  "message": "Invalid or unsupported image format. Is it a valid image?"
}

```

**Comment by kleisauke** [comment]
Users are expected to URL-encode the given URL, or at least `?` to `%3F` and `&` to  `%26`, for example:
https://images.weserv.nl/?url=merovingio.c2rmf.cnrs.fr/fcgi-bin/iipsrv.fcgi%3FFIF=PIA03883.pyr.tif%26WID=800%26CVT=jpeg

**Comment by abubelinha** [comment]
Great!!
I was suspecting something like this, but I asked because I couldn't find it in the FAQ/docs.  Now I see other similar issues (#220, #175, ...) 

I suggest adding it to [FAQs](https://images.weserv.nl/faq/) or as a note next to the [main example in docs](https://images.weserv.nl/docs/#how-it-works).

**Comment by kleisauke** [comment]
Indeed, we should probably note this in the docs.

**Comment by abubelinha** [comment]
I edited the title and reopen just to remember adding this to docs.
Feel free to close if you prefer.

**Comment by abubelinha** [comment]
I edited the title and reopen the issue as a reminder of adding this to docs.
Feel free to close it if you prefer.

**Comment by kleisauke** [comment]
Documentation has been updated to note this.
https://wsrv.nl/docs/introduction.html#how-it-works
