### ISSUE TITLE
Add Pricing info

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#34]
# Add Pricing info [2813884] #

**Submitted by tlianza on 1-5-2012 0:00:00**  
**1 votes on UserVoice prior to migration**  

Your service matches exactly what I'm looking for, but I'm unclear if it's a business I can rely on, or a project that's for fun. If the former, what is the pricing/terms? If the latter, is the code open source by chance?

## Response ##
**by Andries Louw Wolthuizen on 15-7-2012 0:00:00**

The image proxy is free for use to anyone, and we offer it as-is, it’s just basic image resizing, available to anyone, easy to use. We try to keep everyone as happy as we can.
We, as a company, make websites, web applications and mobile applications, so the image proxy is used by us and our customers a lot. By making it freely available, we gain some experience with different user cases, and our customers appreciate it too! It’s a service towards our customers, and relations of our customers. We partner with other companies in our industry, and they see the image proxy as a timesaving solution in their projects too. It’s saving us traffic (through compression), and offloading our main servers, because customers don’t have to use poor self-written scripts for image resizing, instead, they can direct it to images.weserv.nl, which is dedicated to the task. Operating costs of the image proxy are very low for us, the traffic is already paid for (we operate our own gigabit uplinks). We intend to keep the service running for many years to come.
Try it for yourself, if you experience problems or if it doesn’t meet expectations, mail us.
If you’re however interested in running the source code yourself, and use the service internally, please e-mail me on postmaster at weserv dot nl. The code isn’t open source, as in, open for everyone, but we do let company’s run it internally, which is evaluated on a case-by-case basis. The whole system is written in PHP, uses an file-based caching system, and on top of that utilizes normal HTTP reverse proxy’s to perform well under excessive load.
I hope to have answered your question.

#### Comment by Andries Louw Wolthuizen (Webmaster, Images.weserv.nl - Image cache & resize proxy) on 1-5-2012 17:23:00 ####
The image proxy is free for use to anyone, and we offer it as-is, it’s just basic image resizing, available to anyone, easy to use. We try to keep everyone as happy as we can.
We, as a company, make websites, web applications and mobile applications, so the image proxy is used by us and our customers a lot. By making it freely available, we gain some experience with different user cases, and our customers appreciate it too! It’s a service towards our customers, and relations of our customers. We partner with other companies in our industry, and they see the image proxy as a timesaving solution in their projects too. It’s saving us traffic (through compression), and offloading our main servers, because customers don’t have to use poor self-written scripts for image resizing, instead, they can direct it to images.weserv.nl, which is dedicated to the task. Operating costs of the image proxy are very low for us, the traffic is already paid for (we operate our own gigabit uplinks). We intend to keep the service running for many years to come.
Try it for yourself, if you experience problems or if it doesn’t meet expectations, mail us.
If you're however interested in running the source code yourself, and use the service internally, please e-mail me on postmaster at weserv dot nl. The code isn't open source, as in, open for everyone, but we do let company's run it internally, which is evaluated on a case-by-case basis. The whole system is written in PHP, uses an file-based caching system, and on top of that utilizes normal HTTP reverse proxy's to perform well under excessive load.
I hope to have answered your question.

#### Comment by Anonymous on 23-8-2015 1:47:00 ####
thanks

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/2813884)**

**Comment by abubelinha** [comment]
I am a bit confused about these comments. 
Are you talking about https://github.com/weserv/images or is this issue a different thing?:
> The code isn’t open source

Really?  In other answers you say different things:
https://images.weserv.nl/faq/#is-the-code-open-source
> The whole system is written in PHP

- C++ 92.5%
- Perl 3.7%
 - CMake 2.3%
 - Dockerfile 1.2%
 - Other 0.3%

Where is the PHP stuff?

**Comment by kleisauke** [comment]
@abubelinha  Did you notice that this original migrated issue is almost 10 years old? See [`CHANGELOG.md`](https://github.com/weserv/images/blob/5.x/CHANGELOG.md) for things that have changed since then.

**Comment by abubelinha** [comment]
Sorry and thanks, that explains it all.
