### ISSUE TITLE
Add http basic auth

### ISSUE THREAD

**Issue by maffinca69** [andrieslouw/imagesweserv#341]
There are images that are not accessible from the outside and can be accessed either from a specific network or under authorization. For example, https://user:password@google.com/example.png
Now in response to such a request we get an error:
```
{
  "status": "error",
  "code": 400,
  "message": "Unable to parse URI"
}
```

Will basic auth support be added in the future? Parse login and password and put them in headers

**Comment by giautm** [comment]
You should sent the request with headers, it should be passed to the upstream.

**Comment by maffinca69** [comment]
@giautm Where exactly should this be added (what config file)?
If I pass the headers in my request, it doesn't work either and the error remains the same

**Comment by andrieslouw** [comment]
Is there anyone still using HTTP basic auth?
You could use something like `proxy_set_header Authorization "Basic base64encodeduserpass";`, but make sure to check the manuals and code-examples on this. It's not something we'd support in our public proxy.
