### ISSUE TITLE
dynasty-scans.com blocked

### ISSUE THREAD

**Issue by SwiftWinds** [andrieslouw/imagesweserv#344]
Example URL: https://images.weserv.nl/?url=https://dynasty-scans.com/system/releases/000/036/409/114.png&w=300

I know that weserv images relies on OpenDNS domain tagging. Looking at [the OpenDNS entry for dynasty-scans](https://domain.opendns.com/dynasty-scans.com) and it seems that the only accepted tag is "Anime/Manga/Webcomic." Why is this grounds for dynasty-scans.com to be blacklisted?

**Comment by andrieslouw** [comment]
Normally all urls are parsed by https://community.opendns.com/domaintagging/

To prevent our public service from being blocked or attacked by DMCA's, we block these categories:

- Adware
- Anime/Manga/Webcomic
- Gambling
- Hate/discrimination
- Nudity
- Pornography
- Proxy's (to mitigate the risk of redirect-loops)
- Sexuality
- Tasteless

Please use the source code provided here to host your own solution if you're blocked.

**Comment by SwiftWinds** [comment]
Alright, thank you for clarifying :)
