### ISSUE TITLE
How to add HTTPS support

### ISSUE THREAD

**Issue by dayeggpi** [andrieslouw/imagesweserv#345]
Hi team,

I followed the install steps from https://github.com/weserv/images/blob/5.x/docker/README.md
and install via docker worked like a charm.

However, I can only access it via http.
Could you please explain to a noobie how to add such support ?

I use Ubuntu 20.04 TLS, with OpenLiteSpeed.

**Comment by kleisauke** [comment]
Duplicate of #116
