### ISSUE TITLE
How to block domains

### ISSUE THREAD

**Issue by dayeggpi** [andrieslouw/imagesweserv#346]
Hi team,

I followed the install steps from https://github.com/weserv/images/blob/5.x/docker/README.md
and install via docker worked like a charm.

However, I would like to protect myself from people using my server for their images...
Could you please explain to a noobie how to only allow specific domains or block specific domains for the "url" parameter?

I use Ubuntu 20.04 TLS, with OpenLiteSpeed.

**Comment by kleisauke** [comment]
Duplicate of #314
