### ISSUE TITLE
I got 403 with imgur

### ISSUE THREAD

**Issue by giszh86** [andrieslouw/imagesweserv#348]
I use imgur, and get 403,
![image](https://user-images.githubusercontent.com/8955999/176340598-ee382ac4-f8a5-48bb-a7b3-0cb9de5c6d0e.png)

https://images.weserv.nl/?url=https://i.imgur.com/ejXJlrZ.jpeg
https://images.weserv.nl/?url=http://i.imgur.com/ejXJlrZ.jpeg

**Comment by kleisauke** [comment]
Duplicate of #319
