### ISSUE TITLE
webp not right format

### ISSUE THREAD

**Issue by kesar** [andrieslouw/imagesweserv#349]
Hi, we are getting issues loading a webp image, isnt supported? docs says that webp should be fine.

Thanks!

![image](https://user-images.githubusercontent.com/1288106/176415037-54f746ba-0330-48f0-9c9e-b3e5acbfe605.png)

https://everipedia-storage.s3.amazonaws.com/ProfilePicture/lang_en/pickle-finance-cryptocurrency/mainphoto_medium.webp

https://images.weserv.nl/?url=https://everipedia-storage.s3.amazonaws.com/ProfilePicture/lang_en/pickle-finance-cryptocurrency/mainphoto_medium.webp

**Comment by kleisauke** [comment]
It looks like this WebP image is uploaded gzip-compressed to Amazon S3.
```bash
$ curl -s -D - -o /dev/null https://everipedia-storage.s3.amazonaws.com/ProfilePicture/lang_en/pickle-finance-cryptocurrency/mainphoto_medium.webp | grep "Content-Encoding"
Content-Encoding: gzip
$ curl -H "Accept-Encoding: identity" -s -D - -o /dev/null https://everipedia-storage.s3.amazonaws.com/ProfilePicture/lang_en/pickle-finance-cryptocurrency/mainphoto_medium.webp | grep "Content-Encoding"
Content-Encoding: gzip
```

Our requests are sent without the `Accept-Encoding` header, which implies that we want the default encoding, i.e. `identity`. The caveat here is that the [RFC2616 sec 14.3](https://datatracker.ietf.org/doc/html/rfc2616#section-14.3) allows the server to assume any available encoding is acceptable.

We only support gzip-compressed SVG images (i.e. `*.svgz` and `*.svg.gz`), there's no plan to support other gzip-compressed images. Note that it's recommended to not use gzip for images or other binary files, as they are already compressed; using gzip on them won't provide any additional benefit, and can actually make them larger.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
