### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Smorvel** [andrieslouw/imagesweserv#352]
https://images.weserv.nl/?url=http://joyreactor.cc/apple-touch-icon.png
For some reason I get 404 eror

**Comment by kleisauke** [comment]
Duplicate of #339

**Comment by Smorvel** [comment]
@kleisauke ok, so why this https://images.weserv.nl/?url=http://joyreactor.com/apple-touch-icon.png also doesen't work? domain is .com

**Comment by kleisauke** [comment]
Please see https://github.com/weserv/images/issues/285#issuecomment-828176654.
