### ISSUE TITLE
Docker image - understanding caching system

### ISSUE THREAD

**Issue by lashawnta-pf** [andrieslouw/imagesweserv#354]
I have your docker image working on AWS, but it's not clear to me where the caching is happening.   All of the redis refences are commented out.   With the docker image are will still sending our images to a caching system managed on your side or somehow on our side as I didn't configure anything related to caching?  Please advise.  Just want to be able to explain for legal purposes.

**Comment by kleisauke** [comment]
Nothing will be sent to our servers if you decide to host this project yourself. By default the Docker image uses nginx's `proxy_cache` directive to handle image caching, this can be disabled using the [`imagesweserv-no-cache.conf`](https://github.com/weserv/images/blob/6dcca50caea32dfbb71336980a7826b483b80229/ngx_conf/imagesweserv-no-cache.conf) config. For example:
```Dockerfile
FROM ghcr.io/weserv/images:5.x

RUN cp ngx_conf/imagesweserv-no-cache.conf /etc/nginx/imagesweserv.conf
```

**Comment by kleisauke** [comment]
Also see: #205.

**Comment by lashawnta-pf** [comment]
@kleisauke thank you for kindly repeating the answer to what you have already answered.  My apologies for missing that.
