### ISSUE TITLE
Imageresizer working incorrect, when we use additional arg in query_string

### ISSUE THREAD

**Issue by rockbesst** [andrieslouw/imagesweserv#358]
We using weserv resizer as docker container to resize images for website. And we send requests to resizer with query_string like this:
?v=1666706784000&w=200&h=176&fit=cover&il
v= is our specific parameter for another reason. 
When v= is the first parameter, all working correctly, but when I move parameter v= to another position, for example "?w=200&h=300&v=1666706784000&fit=cover&il", resizer will crop image to 4:3 with height 176. I think, this crop is some default operation, but I don't understand why parameter v= breaking resizer's logic. Is this a bug, or I did something wrong?

**Comment by giautm** [comment]
if `?v=` is a part of `url` param, I think you should encode the URL with `encodeURLComponent` function before passing it to the resize service.

**Comment by kleisauke** [comment]
This has been fixed with commit https://github.com/weserv/images/commit/0955dc1cec0b28e6c3d74c63f5c7da97507f0208, which has just been rolled out to production. Thanks for reporting this!
