### ISSUE TITLE
Gray scale JPEG image is turned into a PNG with inverted colors after caching

### ISSUE THREAD

**Issue by sasensi** [andrieslouw/imagesweserv#370]
First, thanks a lot for this service which I'm a huge fan of an which I use regularly.

This is the third time that I notice a weird behavior with some kinds of images so I decided to report it in case there is something to fix about it.
The first two times, I didn't gather the input image so I'm only able to provide one now but I know that it happened other times in the past with other images.

So here are:
- the source image
  https://cipmarseille.fr/images/auteurs/2043_auteur_20120511174919.jpg
![ko](https://user-images.githubusercontent.com/11247504/221830347-3d20d3e3-6043-4d9c-a001-eda594b5f826.jpg)
- the cached image
  https://images.weserv.nl/?url=https://cipmarseille.fr/images/auteurs/2043_auteur_20120511174919.jpg
![ko-cached](https://user-images.githubusercontent.com/11247504/221830639-03e8582f-10d7-4b84-aa07-65cfad3c68eb.png)
As you can see, this happen even without using any of the available query parameters (which I use for my real use case).
So there are 2 surprising things:
   - the image is a PNG while the input was a JPEG
   - the colors are inverted and the background is transparent

I don't know much about image format and neither about the processing that you apply on them by default.
But I had a quick look at two input files (one which is working and this one) with `exiftool`.
And I noticed that, among other differences, this image was referenced as a gray scale one so I wonder if this could be a clue ?

In the past, in order to workaround this, I opened and resaved the file in a software like Photoshop.
I guess that this changed the meta data and somehow fix the issue.

Hoping that you can help me with this.
Thanks in advance.

**Comment by andrieslouw** [comment]
@kleisauke: Care to investigate? Maybe a funky color-profile? Not sure if it's libvips or some third-party lib.

**Comment by andrieslouw** [comment]
I've been informed that it indeed is libvips, and that a fix is being worked on since your report. We'll update if there's more info.

**Comment by andrieslouw** [comment]
In the meantime, `&output=jpg` will mitigate the issue: https://images.weserv.nl/?url=https://cipmarseille.fr/images/auteurs/2043_auteur_20120511174919.jpg&output=jpg

**Comment by sasensi** [comment]
@andrieslouw, awesome, thank you for your updates and advices.

**Comment by kleisauke** [comment]
This has been fixed with libvips 8.14.2 (see https://github.com/libvips/libvips/discussions/3361 for details), which has just been rolled out to production. Thanks for reporting this!

**Comment by sasensi** [comment]
Thank you very much for the fix.
