### ISSUE TITLE
IP list for weserv.nl

### ISSUE THREAD

**Issue by Buffele** [andrieslouw/imagesweserv#372]
Hi,

is there somewhere a list of current active ips of weserv.nl image resize servers?

Would love to have a list of these so we can whitelist these IPs.

Background: We ban all cloud / hosting ASNs, which also results in weserv being banned on our platform.

An updated list like cloudflare does it would be really handy.

Example: https://www.cloudflare.com/ips-v4

**Comment by andrieslouw** [comment]
Yes, please use https://images.weserv.nl/ips.txt or https://wsrv.nl/ips.txt

**Comment by Buffele** [comment]
Thanks, I have whitelisted these IPs.

Would be handy to have that link in the FAQ. Was searching there and didn't find it.

**Comment by andrieslouw** [comment]
Indeed, agree, that should be somewhere in the FAQ.

**Comment by kleisauke** [comment]
FAQ has been updated to note this.
https://wsrv.nl/faq/#what-ip-addresses-does-wsrv-nl-use-to-fetch-my-images
