### ISSUE TITLE
Error with code 400 and message: libvips error: icc_transform: unable to load or find any compatible input profile

### ISSUE THREAD

**Issue by sasensi** [andrieslouw/imagesweserv#373]
Hi,

First thank you for the awesome work on this service !
I love it and use it on many website that I created.
I recently found this failing case:
```
https://wsrv.nl/?url=https://images.navigart.fr/1000/3L/08/3L08501.jpg
```
Which, instead of returning an image, return the following error
```json
{"status":"error","code":400,"message":"libvips error: icc_transform: unable to load or find any compatible input profile\n"}
```
The source image is here:
```
https://images.navigart.fr/1000/3L/08/3L08501.jpg
```

---

I don't know what is happening but it might be linked to the recent update of `libvips` in order to solve this issue: https://github.com/weserv/images/issues/370
I say that because, it seems that the same url was working fine until recently.

**Comment by kleisauke** [comment]
This has been fixed upstream with commit https://github.com/libvips/libvips/commit/cbe65cc060d62887ae505087a9ff49c78650dd97 and occurs only with greyscale images with an incompatible embedded ICC profile.

We'll do some A/B testing on that commit next week.

**Comment by kleisauke** [comment]
Fix has been rolled out to production.

**Comment by sasensi** [comment]
Awesome, thank you very much !
