### ISSUE TITLE
error 403 requested url not found

### ISSUE THREAD

**Issue by raramuridesign** [andrieslouw/imagesweserv#374]
Hi @andrieslouw 
Could you please let us know why this is showing this error?
ERROR: 
{"status":"error","code":404,"message":"The requested URL returned error: 403"}

URL: 
https://wsrv.nl/?w=1200&h=800&fit=cover&q=90&url=bibc.co.za/images/assets/496e9e222dc96ce8a9cf72e32a58bf38.jpg

I think I've seen others with the same issue, but it would be great if you could let us know the issue.
Thanks
M.

**Comment by raramuridesign** [comment]
I am requesting from the hosting company to whitelist the IP's and we have also whitelisted at Cloudflare.
Anything else we can look at ?
M.

**Comment by raramuridesign** [comment]
Closing, as it seems to be ok once whitelisting on CF

**Comment by julptk** [comment]
same here sir https://wsrv.nl/?url=https://cosmicscans.com/wp-content/uploads/2023/05/gotl14-01.webp&w=300&output=jpg

where the problem?

**Comment by kleisauke** [comment]
> same here sir https://wsrv.nl/?url=https://cosmicscans.com/wp-content/uploads/2023/05/gotl14-01.webp&w=300&output=jpg
> 
> where the problem?

@julptk If an upstream server responds with a 403 error, it is typically an indication of a block, and unfortunately, there is limited action we can take in such cases. If this problem persists, we kindly request you to report it to the upstream source.

Furthermore, it is generally discouraged to hijack issues raised by others on GitHub.
