### ISSUE TITLE
Preserve EXIF?

### ISSUE THREAD

**Issue by edent** [andrieslouw/imagesweserv#375]
Is there a setting which will let me preserve the EXIF metadata of a cached image?

I'm not using any resizing or format conversion. Just `https://images.weserv.nl/?url=example.com/photo.jpg&output=jpg`

Are there any options which will let users see the original, unaltered file - albeit cached through your service?

Thanks!

**Comment by andrieslouw** [comment]
We strip all EXIF and other data, and never pass files bit-by-bit. This is due to privacy and security concerns. If you want to proxy the original file, without modifications, please use something like Cloudflare.
