### ISSUE TITLE
DNS blocked by policy

### ISSUE THREAD

**Issue by julptk** [andrieslouw/imagesweserv#376]
hello, i need help, how to solve this problem? https://images.weserv.nl/?w=300&q=70&url=https://svr8.imgkc5.my.id/wp-content/img/V/Vinland-Saga/099/004.jpg

**Comment by andrieslouw** [comment]
The ccTLD `my.id` was being blocked by anti-abuse scripts, fixed it. It will take a while for caching to clear this.

**Comment by julptk** [comment]
and this one sir sorry i0.wp.com

**Comment by andrieslouw** [comment]
> and this one sir sorry i0.wp.com

Please see https://github.com/weserv/images/issues/287#issuecomment-830845525

**Comment by julptk** [comment]
thank you sir

**Comment by julptk** [comment]
help again sir 🙏

v1.gambar.xyz
tukangambar.xyz
cdnkomiku.xyz

**Comment by kleisauke** [comment]
> v1.gambar.xyz
> tukangambar.xyz
> cdnkomiku.xyz

Please see https://github.com/weserv/images/issues/339#issuecomment-1096952128
