### ISSUE TITLE
The hostname of the origin is unresolvable (DNS) or blocked by policy.

### ISSUE THREAD

**Issue by redpanda-gr** [andrieslouw/imagesweserv#380]
Hello Weserv team!

First of all, thank you for your services. It's a lifesaver for companies with small budget on server resources.
We have a site (freetips247.com) and we use your service a lot.
Since this morning, our content editors report that the new images cannot be displayed.
I saw the next response from your server
`{"status":"error","code":404,"message":"The hostname of the origin is unresolvable (DNS) or blocked by policy."}`
Example:
`https://images.weserv.nl/?output=webp&h=270&url=https://www.freetips247.com/images/560x420_phone-11-7.webp`
Is it something that we can resolve from our part or you have to add our domain in your white list?

Thank you!

**Comment by andrieslouw** [comment]
It looks like a real DNS issue, as it is not on any blocklist as far as I can see, I'll investigate this.

**Comment by andrieslouw** [comment]
To prevent our public service from being blocked or attacked by DMCA's, we block these categories:
- Adware
- Anime/Manga/Webcomic
- Gambling
- Hate/discrimination
- Nudity
- Pornography
- Proxy's (to mitigate the risk of redirect-loops)
- Sexuality
- Tasteless

It appears that the data from OpenDNS is a bit lagging, as some servers report blocking the domain, and some don't. It looks like your domain has recently been included with the "Gambling" tag if I check the logs on OpenDNS.

It may take a while, but the category should also appear here: https://community.opendns.com/domaintagging/search/?q=freetips247.com

That's where you can object to this classification.

**Comment by redpanda-gr** [comment]
Thank you for the information!
Sorry for the delay, I was waiting for the site managers to inform me about the matter.
They informed me that the site belongs to the area of ​​affiliation / advertising to promote betting companies. We can also send you the relevant permit from the Greek state.

We have already put the corresponding information in OpenDNS to which domain the site belongs.
What else would you like from us to certify that we are an affiliate site and not Gambling?

Thank you very much!

**Comment by andrieslouw** [comment]
For now I added a manual exclusion to our list. It can take a few minutes for it to take effect (due to caching).

**Comment by redpanda-gr** [comment]
Thank you very much!!!
Everything is going perfect now!!!
