### ISSUE TITLE
Any cons of using free services like this?

### ISSUE THREAD

**Issue by lubiah** [andrieslouw/imagesweserv#381]
Hi,
Sorry if my question seems unreasonable, I just wanted to know if there are any great disadvantages in using services like this. I am currently using ImageKit and I want to switch to this service so I just want to know if there any cons which I can know of. 
Thank you

**Comment by andrieslouw** [comment]
Compared to ImageKit, we don't handle videos. And we're free, and open source, so you can just grab our code, and host it yourself, or modify it to suit your needs better.

The public service on wsrv.nl is limited to prevent abuse, so there are certain categories of websites it won't work on, and we have (high) rate-limits, but those are hardly triggered. But if you grab our code, you can do whatever you want, without any limits.

**Comment by lubiah** [comment]
Alright, thanks for the response
