### ISSUE TITLE
.xyz: The hostname of the origin is unresolvable (DNS) or blocked by policy

### ISSUE THREAD

**Issue by BlueTree242** [andrieslouw/imagesweserv#383]
Hello, i am having issues trying to get images to work on this service (trying to put images on modrinth which uses this service).

My domain is `discordsrvutils.xyz` and i read some issues and my website has nothing to be flagged for.

Example image : https://wsrv.nl/?url=https%3A%2F%2Fdiscordsrvutils.xyz%2Fimg%2Ffeatures%2FFeature-1.png&n=-1
Original URL: https://discordsrvutils.xyz/img/features/Feature-1.png

Notes:
- The site is hosted on replit, but i decided to enable cloudflare proxy a few minutes ago in case replit IPs are flagged, but that did not work.

**Comment by andrieslouw** [comment]
Unfortunately we blocked TLD's like .xyz from the public service.

Please see https://github.com/weserv/images/issues/339#issuecomment-1096952128:
> Due to multiple, and continuing, abuse of our service from many randomly generated cheap domains, we blocked all .cc .club .date .fun .pw .top .xxx .xyz domains on our public service. I'm really sorry for this, but the abuse was continuously using over 2 Gbit/s of our bandwidth, which we provide for free. Please consider changing domains to a normal TLD, or hosting the service yourself.

**Comment by BlueTree242** [comment]
Bruh this domain is $14.5 per month which is actually more expensive than the com version...

**Comment by raramuridesign** [comment]
@BlueTree242 try this service if this does not work
https://statically.io/
or if you are on cloudflare, pay for cloudflare images.  https://developers.cloudflare.com/images/
;-)

wsrv is a free service... and is provided with limitations. 
M.

**Comment by BlueTree242** [comment]
I actually just realized i can do a very easy workaround, i can add another domain to the site, a sub domain to my personal domain which seems to not be flagged. Thank you!

**Comment by andrieslouw** [comment]
Thanks, and sorry we need to be so strict, we have tried blocking each and every .xyz domain giving trouble, but it was like whack-a-mole. Somehow, someone, somewhere gets these domains real cheap, as they all looked randomly generated (same with the other extensions).
