### ISSUE TITLE
Some jpgs are not converted to the progressive format

### ISSUE THREAD

**Issue by Dirk-27** [andrieslouw/imagesweserv#385]
In #50 the progressive image feature is explained.

The example image

https://images.weserv.nl/?url=upload.wikimedia.org/wikipedia/commons/e/e0/JPEG_example_JPG_RIP_050.jpg&il

works also when we serve the image from our server.

But when we use https://cdn.vrdoro.com/data/vrdoro/images/11/D2DA86F06A753397A10995708417CC49.jpeg as

https://images.weserv.nl/?url=cdn.vrdoro.com/data/vrdoro/images/11/D2DA86F06A753397A10995708417CC49.jpeg?il

throttling the network we see that it is not progressive.

What is wrong here?

**Comment by kleisauke** [comment]
The `?` character in a URL signifies the start of the query string. Additional parameters after that have to start with `&`.
```diff
-https://images.weserv.nl/?url=cdn.vrdoro.com/data/vrdoro/images/11/D2DA86F06A753397A10995708417CC49.jpeg?il
+https://images.weserv.nl/?url=cdn.vrdoro.com/data/vrdoro/images/11/D2DA86F06A753397A10995708417CC49.jpeg&il
```

**Comment by Dirk-27** [comment]
Oh, sorry! Thats ok than!
