### ISSUE TITLE
webP output is always lossy and cannot be requested as lossless

### ISSUE THREAD

**Issue by haynzz** [andrieslouw/imagesweserv#386]
This seems to be the default behavior of libvips and you need to explicitly pass `lossless` as a parameter.
Currently there is not option to pass this param.

`&q=100` does not yield the same results.

This is especially relevant for animated webP as their lossy versions are rarely appealing to the eye.

**Comment by kleisauke** [comment]
Would adding a new parameter to control this (e.g. `&ll`) work for you?

Let's mark this as an enhancement, I think it should be straightforward to add code-wise.

**Comment by haynzz** [comment]
I think that would be the suitable solution.

**Comment by kleisauke** [comment]
This has been implemented with commit 0674c39993f2508343be6a8493feb93ae10e8bf3, which has just been rolled out to production. Thanks for reporting this!

Documentation will be updated later to reflect this.

**Comment by haynzz** [comment]
Wow! This was quick. 
I did not expect this.
Can you help me find out which Release has this change now?

**Comment by kleisauke** [comment]
@haynzz You can find it in the latest pre-built Docker image at [`ghcr.io/weserv/images:5.x`](https://github.com/weserv/images/pkgs/container/images), which is automatically built from the [`5.x`](https://github.com/weserv/images/tree/5.x) branch.

A new Git tag for this feature has not been published yet; it's currently blocked on true streaming support.
https://github.com/weserv/images/blob/36ea05803d81573d996d8c6068247940c48c0490/src/api/CMakeLists.txt#L80-L86

**Comment by kleisauke** [comment]
Documentation has been updated.
https://wsrv.nl/docs/format.html#lossless-compression
