### ISSUE TITLE
[issue] Invalid or unsupported image format. Is it a valid image

### ISSUE THREAD

**Issue by raramuridesign** [andrieslouw/imagesweserv#388]
Hi Team
@andrieslouw @kleisauke 

We have been using the CDN system for sometime but recently there has been some images which return the following error

**_Invalid or unsupported image format. Is it a valid image_**

Here is an example of a url with an issue
https://wsrv.nl/?v=1&w=70&h=45&fit=cover&q=90&url=betweenity.online/images/assets/flags/MR.svg

If we load the direct image, you see it here
https://betweenity.online/images/assets/flags/MR.svg

The errors are random (although I am unsure if this is an error on our side, or from wsrv.nl

Would you be able to guide us as to how we can resolve this error?

Thanks in advance
M

**Comment by kleisauke** [comment]
It looks like this upstream server is serving Brotli-compressed SVG images.
```console
$ curl --http1.1 -sD - -o /dev/null 'https://betweenity.online/images/assets/flags/MR.svg' | grep "Content-Encoding"
Content-Encoding: br
$ curl -H "Accept-Encoding: identity" --http1.1 -sD - -o /dev/null 'https://betweenity.online/images/assets/flags/MR.svg' | grep "Content-Encoding"
Content-Encoding: br
```

Our requests are sent without the `Accept-Encoding` header, which implies that we want the default encoding, i.e. `identity`. The caveat here is that the [RFC2616 sec 14.3](https://datatracker.ietf.org/doc/html/rfc2616#section-14.3) allows the server to assume any available encoding is acceptable.

We only support gzip-compressed SVG images (i.e. `*.svgz` and `*.svg.gz`), there are no foreseeable plans to support Brotli-compressed SVG images.

**Comment by raramuridesign** [comment]
@kleisauke Thanks. 
We have decided to replace the flags with PNG flags, so we do not run into this issue.
Appreciate the feedback.
M.
