### ISSUE TITLE
Percentage in query parameters

### ISSUE THREAD

**Issue by mateusz28011** [andrieslouw/imagesweserv#391]
Hi,
encoded percentage in the query parameters is ignored.

Original
`https://wsrv.nl/?url=https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_1280.jpg&cw=50%&ch=50%&cx=0&cy=0&precrop`

Encoded
`https://wsrv.nl/?url=https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_1280.jpg&cw=50%25&ch=50%25&cx=0&cy=0&precrop`

**Comment by kleisauke** [comment]
This has been fixed with commit fd7a184ef6d2f650cb3d1f99c10fadc4eacfef69, which has just been rolled out to production.
