### ISSUE TITLE
discord blocked

### ISSUE THREAD

**Issue by Buffele** [andrieslouw/imagesweserv#395]
Hello!

Is it intended that we can't resize images with this service and let it display in discord previews?

**Comment by kleisauke** [comment]
It wouldn't surprise me, given that Discord has blocked our User-Agent in the past, see: #223.

There's not much we can do for this. Please report this to Discord if it continues to be a problem.

**Comment by Buffele** [comment]
Okay, that's a bummer, since discord support is non-existant, there is nothing much we can do here.

Thanks for the quick response and support!
