### ISSUE TITLE
WordPress plugin

### ISSUE THREAD

**Issue by neo22s** [andrieslouw/imagesweserv#397]
Hello! not a question and I did not know where else to write, I have developed a simple wordpress plugin, it's not yet at the wordpress marketplace..

100% free and open source I hope can help someone to use this awesome service, thanks!!

https://garridodiaz.com/free-image-cdn-for-wordpress/

**Comment by sekedus** [comment]
Please publish to WordPress plugin directory.

**Comment by neo22s** [comment]
I have tried but there's a 90 days waiting period...

**Comment by neo22s** [comment]
Finally available at the directory... https://wordpress.org/plugins/free-image-cdn/

**Comment by neo22s** [comment]
thanks for the support!
