### ISSUE TITLE
Rate Limit Redirect

### ISSUE THREAD

**Issue by onkoe** [andrieslouw/imagesweserv#398]
Hi there! Thanks for the excellent service! I've been using this project on my blog, so my poor little server doesn't have to worry about sending images worldwide! 

However, I'm concerned about the rate-limiting - once an IP hits the rate limit, does that mean the server effectively blocks them from seeing images? 

If so, does `wsrv.nl` redirect the users to the original link, or does it just not load the image? Ideally, I'd like to always provide the original link as an option, but I understand if it is not possible to fulfill this request.

Once again, thank you for the awesome project!! 🤩️

**Comment by kleisauke** [comment]
Once a  IP-address hits the rate limit it will response with the `429 Too Many Requests` HTTP status code. After that, the IP will be blocked at Cloudflare for 1 hour and response with the `403 Forbidden` HTTP status code.

The limit is 2500/10m and is based on the sophisticated [generic cell rate algorithm](https://en.wikipedia.org/wiki/Generic_cell_rate_algorithm) which provides a rolling time window and doesn't depend on a background drip process, so it's unlikely that a typical visitor will be rate-limited unless they abuse the service. Moreover, the rate-limit only applies to uncached requests.

You can check your current rate limit quota here: https://wsrv.nl/quota.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
