### ISSUE TITLE
Netlify Blocked by Policy..?

### ISSUE THREAD

**Issue by onkoe** [andrieslouw/imagesweserv#399]
Hi! I ended up testing out your service on my blog! While it works with other images, I can't get it to play happily with my Netlify-hosted blog. 

Images load as an invisible box, but when viewing [this image](https://barretts.club/images/milkv-duo-expand-fs/all-done.png), for example, I get the following: 

```json
{
    "status": "error",
    "code": 404,
    "message": "The hostname of the origin is unresolvable (DNS) or blocked by policy."
}
```

The URL used to view the image is: `https://wsrv.nl/?url=https://barretts.club/images/milkv-duo-expand-fs/all-done.png`

Is it correct that Netlify is being blocked? If so, could you please unblock it? Otherwise, I may need to correct my link. Sorry if that's the case! 🫣️

**Comment by onkoe** [comment]
Also, as it turns out, I can get the fallback images to load on the webpage if I remove the `//` prefix shown in the documentation. See [this page](https://barretts.club/posts/milkv-duo-expand-fs/) to believe... :)

However, I'm not sure why it's blocked "manually." Any ideas?

**Comment by kleisauke** [comment]
Unfortunately we blocked TLD's like .club from the public service.

Please see https://github.com/weserv/images/issues/339#issuecomment-1096952128:
> Due to multiple, and continuing, abuse of our service from many randomly generated cheap domains, we blocked all .cc .club .date .fun .pw .top .xxx .xyz domains on our public service. I'm really sorry for this, but the abuse was continuously using over 2 Gbit/s of our bandwidth, which we provide for free. Please consider changing domains to a normal TLD, or hosting the service yourself.

**Comment by onkoe** [comment]
Thanks for the quick response! Is there any chance you could whitelist my blogging site, `barretts.club`, amongst all the noise?

If that’s infeasible or otherwise difficult, I completely understand. Thank you for the great service! ☺️

**Comment by kleisauke** [comment]
@onkoe Whitelisted as requested, have fun!

As an aside, I like your blog post at https://barretts.club/posts/i-got-a-milkv-duo/. I'm still looking for a cheap RISC-V board that supports the latest RISC-V Vector (RVV) extension spec (version 1.0) because emulating that within QEMU is incredibly slow. :)

**Comment by onkoe** [comment]
Aww, thank you! From what I can tell, the Duo only supports RVV 0.7.1 on its big core, and other boards are still limited with RVV support overall.

Oh well! I did find one (less cheap) [development board](https://www.analoglamb.com/product/kendryte-k230-risc-v-development-board-canmv-k230/) that has RVV 1.0 for about $50. That’s a lot for many projects, but if we're starting to see it ship to consumers, we'll probably get a more general design sometime soon! 

Anyways, thanks for your help on this issue. Super happy to use the service! ☺️

**Comment by onkoe** [comment]
whoops forgot to close this. here you go! :)
