### ISSUE TITLE
Input image exceeds pixel limit. Width x height should be less than 71000000

### ISSUE THREAD

**Issue by Dirk-27** [andrieslouw/imagesweserv#400]
How can we avoid this error on our own weserv-server?

Is there a way to increase the limit?

Kind regards

Dirk

**Comment by kleisauke** [comment]
You can remove this limit by doing this within the [ngnix configuration](https://github.com/weserv/images/blob/5.x/ngx_conf/imagesweserv.conf):
```nginx
weserv_limit_input_pixels 0;
weserv_limit_output_pixels 0;
```

For example, using Docker:
```Dockerfile
FROM ghcr.io/weserv/images:5.x

RUN sed -i '1iweserv_limit_input_pixels 0;\nweserv_limit_output_pixels 0;' \
    /etc/nginx/imagesweserv.conf
```
```bash
docker build -t weserv/images .
docker run -d -p 8080:80 --shm-size=1gb --name=weserv weserv/images
```

But please do this only for trusted input, there are [PNG decompression bombs available](https://www.bamsoftware.com/hacks/deflate.html) that could burn all the available memory.

**Comment by Dirk-27** [comment]
Thanks, we check this and I come back.

**Comment by Dirk-27** [comment]
Thank you very much. It works!
