### ISSUE TITLE
How to disable cache

### ISSUE THREAD

**Issue by MistyMeteor** [andrieslouw/imagesweserv#404]
The setting of the cache control parameter can only range from 1d (1 day) to 1y (1 year). When I set it to 0d, the return value is default value one year. How can I change cache-control HTTP-header to no cache, to disable cache?

**Comment by kleisauke** [comment]
Hello, did you see https://github.com/weserv/images/issues/292#issuecomment-873653028?
> We don't want to have shorter max-ages than 1 day, as it would be unfeasible to host the free service without any caching.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
