### ISSUE TITLE
404 error every few times

### ISSUE THREAD

**Issue by shusakurainosh** [andrieslouw/imagesweserv#406]
404 error occurs, cause unknown.
Since 3 days ago, 404 errors have been occurring frequently on several images in the following pages. All of these errors occur in URLs starting with "https://images.weserv.nl/?w=100&url=".
A detailed log is attached here.

Please let us know if you or Cloudflare is experiencing any problems.

```

not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2023/05/th_taishibo-herasu4_re.jpeg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2022/08/AdobeStock_50767979.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2023/06/th_syouga1.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2023/05/th_tonyu2-1.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2023/07/th_fukkin-joshi5.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2022/09/DSC03279.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2022/10/s-3903.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2022/06/Suitstopnash.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2023/06/th_anti-aging.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2023/05/th_cheat-day5-1.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2023/01/th_bihada8.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2022/07/232809.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2023/04/chokatsu6-e1684893406875.jpeg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2022/09/s-3704.jpg
  not found (404): https://images.weserv.nl/?w=100&url=https://nosh.jp/magazine/wp-content/uploads/2022/07/15.jpg

```

![スクリーンショット 2024-02-01 18 15 46](https://github.com/weserv/images/assets/111726386/71f05fbb-7fc0-47cc-95b7-9c8633d10b12)
![スクリーンショット 2024-02-01 18 16 23](https://github.com/weserv/images/assets/111726386/f39e8e2e-8745-4bf8-9a50-9bf76a0998fb)

**Comment by kleisauke** [comment]
It looks like this upstream server is blocking all non-Japanese IP addresses (also known as geo-blocking).
https://redbot.org/?uri=https://nosh.jp/magazine/wp-content/uploads/2023/05/th_taishibo-herasu4_re.jpeg
https://tools.keycdn.com/performance?url=https://nosh.jp/magazine/wp-content/uploads/2023/05/th_taishibo-herasu4_re.jpeg
![Screenshot](https://github.com/weserv/images/assets/12746591/016dfa05-5b35-4808-9adc-a1a59d3622f6)

There's not much we can do for this. Please report this to this website if it continues to be a problem.

> 404 error occurs, cause unknown.

Note that all upstream errors are [remapped to 404](https://github.com/weserv/images/blob/2047d411069e95ef421de87c5e05aa90d49ed9a7/src/api/utils/status.cpp#L59-L63), the JSON response always contains more details.
```json
{"status":"error","code":404,"message":"The requested URL returned error: 403"}
```
