### ISSUE TITLE
width parameter does not work

### ISSUE THREAD

**Issue by math-GH** [andrieslouw/imagesweserv#408]
It works fine (with `h` for height):
`https://wsrv.nl/?url=www.01net.com%2Fapp%2Fuploads%2F2024%2F01%2FHonor-Magic-V2-photos-test-18.jpg&h=300`

It does not work (with `w` for width):
`https://wsrv.nl/?url=www.01net.com%2Fapp%2Fuploads%2F2024%2F01%2FHonor-Magic-V2-photos-test-18.jpg&w=300`

error: `{"status":"error","code":404,"message":"The requested URL returned error: 403"}`

but the documentation says that this parameter is valid: https://images.weserv.nl/docs/size.html#width

**Comment by raramuridesign** [comment]
@math-GH If you remove the encoded forward slash in this format it works
```
https://wsrv.nl/?url=www.01net.com/app/uploads/2024/01/Honor-Magic-V2-photos-test-18.jpg&w=100
```
ie this 
```
%2Fa
```

**Comment by math-GH** [comment]
Thanks for you quick help.

It is very weird:

`https://wsrv.nl/?url=www.01net.com/app/uploads/2024/01/Honor-Magic-V2-photos-test-18.jpg&w=100`

it works.

but 

`https://wsrv.nl/?url=www.01net.com/app/uploads/2024/01/Honor-Magic-V2-photos-test-18.jpg&h=100`

does not work.

If I combine `w` and `h`, whether
`https://wsrv.nl/?url=www.01net.com%2Fapp%2Fuploads%2F2024%2F01%2FHonor-Magic-V2-photos-test-18.jpg&h=300&w=300`

nor 

`https://wsrv.nl/?url=www.01net.com/app/uploads/2024/01/Honor-Magic-V2-photos-test-18.jpg&w=300&h=300` 

does work.

**Comment by kleisauke** [comment]
If an upstream server responds with a 403 error, it is typically an indication of a block, and unfortunately, there is limited action we can take in such cases. If this problem persists, we kindly request you to report it to the upstream source.

**Comment by math-GH** [comment]
ah ok. Now I got it. Thanks!
