### ISSUE TITLE
Question: Legal concerns of running an open image resizing proxy

### ISSUE THREAD

**Issue by jonatan-holmgren** [andrieslouw/imagesweserv#409]
Hello. Great service, but aren't there legal concerns of both downloading and serving whatever legally questionable content? I want to host this myself but I'd like to get a clearer picture first.

**Comment by andrieslouw** [comment]
Thanks, yes, there are some legal concerns. DMCA is the one impacting us the most, for this reason we use OpenDNS to block questionable categories. See https://github.com/weserv/images/issues/285#issuecomment-828176654

In addition, we can add certain domains to this blocklist. You could also do it vice-versa, and use lists to only allow specific domains.

**Comment by jonatan-holmgren** [comment]
Is there a list of explicitly blocked domains you guys use? If you can't provide that for security-through-obscurity reasons but I'm curious about doing something similar in the future. Thanks.

**Comment by andrieslouw** [comment]
I can tell we actively block:
```
api.facebook.com
graph.facebook.com
```
And these cheap top TLD's, which are often used for abuse:
```
buzz
cc
club
date
fun
pw
top
xxx
xyz
```

We also sometimes generate lists of specific domains, but this is based on traffic patterns and keywords. They have to to with the categories we actively block using OpenDNS domain tagging. This is only done in case OpenDNS is not quick enough to tag domains.

**Comment by jonatan-holmgren** [comment]
Are you quering some api or just doing DNS-based blocking? I'm curious to implement such functionality myself

**Comment by kleisauke** [comment]
> Are you quering some api or just doing DNS-based blocking?

See https://wsrv.nl/faq/#are-there-any-limitations and https://github.com/weserv/images/issues/314#issuecomment-950368503. I'll close, please feel free to re-open if questions remain.
