### ISSUE TITLE
Getting 404, on some sizes of images

### ISSUE THREAD

**Issue by nilsmakeable** [andrieslouw/imagesweserv#410]
We are seeing 
`{"status": "error",
"code": 404,
"message": "The hostname of the origin is unresolvable (DNS) or blocked by policy."
}`
On requests on some image sizes. If we change the image size the image appears as expected. 

In the nginx error.log on we see the following lines

- [error] 7#0: wrong ident 51546 in DNS response for firebasestorage.googleapis.com, expect 61389
- [error] 7#0: wrong ident 56714 in DNS response for firebasestorage.googleapis.com, expect 19598
- [error] 7#0: wrong ident 24211 in DNS response for firebasestorage.googleapis.com, expect 24813
- [error] 7#0: wrong ident 24632 in DNS response for firebasestorage.googleapis.com, expect 7164
- [error] 7#0: wrong ident 41805 in DNS response for firebasestorage.googleapis.com, expect 61819
- [error] 7#0: wrong ident 38646 in DNS response for firebasestorage.googleapis.com, expect 38720

This issue seems a bit above my experience with nginx, any pointers would be appreciated.

**Comment by kleisauke** [comment]
Sounds like the DNS server is not properly configured. Is this with Docker? If so, see: https://github.com/weserv/images/issues/206#issuecomment-1752740666.

**Comment by kleisauke** [comment]
@nilsmakeable Were you able to make any progress with this?

**Comment by nilsmakeable** [comment]
@kleisauke 
It was in docker, but it was configured correctly, and I had seen the above mentioned thread earlier.

I ended up adding a default url on the script generation our urls with a cache break parameter to avoid the intermittend errors. since then we haven't seen any problems. Which means I haven't been given any more time to look into a better / more correct solution.

**Comment by kleisauke** [comment]
I'll close this issue for now, please feel free to re-open if there's still a problem.
