### ISSUE TITLE
Raising the frame limit for GIFs

### ISSUE THREAD

**Issue by IThundxr** [andrieslouw/imagesweserv#412]
Currently the limit for gif's through wsrv.nl is 320 pages (frames), which i feel is quite low and makes me unable to use this gif on any site using wsrv.nl, https://bloom.host/assets/images/Comp_2.gif

Would it be possible to maybe bump the frame limit to 400 or something along the lines of that? Generally the gifs i've come across are pretty heafty in terms of frames and generally exceed the 320 frame limit that is currently set for gifs

Thanks,
IThundxr

**Comment by kleisauke** [comment]
Limit has just been increased to 400 frames as requested, have fun!

**Comment by IThundxr** [comment]
Thanks!
