### ISSUE TITLE
I am confused how can I use it for s3 images?

### ISSUE THREAD

**Issue by milanpoudelwebdeveloper** [andrieslouw/imagesweserv#413]
is it same as adding https://wsrv.nl/?url=s3 image url....?  I am getting 404 this way

**Comment by kleisauke** [comment]
Images on public S3 buckets can be reached via `<bucket-name>.s3.<region>.amazonaws.com`, for example:
https://wsrv.nl/?url=https://libvips-packaging.s3.eu-west-1.amazonaws.com/zebra.jpg

Private S3 buckets requires HTTP basic authentication which is not something we'd support on our public service (see #341). If you're able to host your own solution, you can support this by doing something like this within the [ngnix configuration](https://github.com/weserv/images/blob/5.x/ngx_conf/imagesweserv.conf):
```nginxconf
location /s3/ {
    weserv filter;

    # The S3 bucket we use
    proxy_pass http://libvips-packaging.s3.amazonaws.com/;
    proxy_set_header Host libvips-packaging.s3.amazonaws.com;

    # Authorization should not be needed on public buckets
    proxy_set_header Authorization '';

    # Header configuration
    proxy_hide_header x-amz-id-2;
    proxy_hide_header x-amz-request-id;
    proxy_hide_header x-amz-meta-server-side-encryption;
    proxy_hide_header x-amz-server-side-encryption;
    proxy_hide_header Set-Cookie;
    proxy_ignore_headers Set-Cookie;

    # Intercept proxy errors
    proxy_intercept_errors on;

    # Enable the upstream persistent connection
    proxy_http_version 1.1;
    proxy_set_header Connection '';
}
```
```console
$ curl -s -o /dev/null -w "%{http_code}" http://localhost/s3/zebra.jpg?w=512
200
```

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
