### ISSUE TITLE
External access problems

### ISSUE THREAD

**Issue by degarb** [andrieslouw/imagesweserv#418]
It was a snap installing wsl on  window 11, ubuntu, docker. even weserv.

However, I disabled the firewall, and properly added a virtual server on the router 8080 in and 8080 over to the reserved ip of the windows 11 laptop.

Still, I can easily get the localhost:8080 to convert external images in the browser, while using my external ip doesnt work.

I also tried the dyndns.   

I don't have ssl certificate but tried http://ipaddress.

What ever port I put weserv on is blocked, according to tools.   I tried disabling the router firewall.  Virtual servers work for other thins like my http server on the other machine.   I  don't know what could be blocking the port. windows sees weserve listening on the ports I have tried. I cant get through even on sister machines on the router.

localhost weserv works fine.    I have spent 9 hours on this, I am stumped. Ai is stumped.

**Comment by degarb** [comment]
Spectrum is not blocking the port.  I veriied this from search, from changing to another port used by another program after I disabled the program and rule.

**Comment by degarb** [comment]
I think I found the solution: Cmd : netsh interface portproxy add v4tov4 listenport=8080 listenaddress=0.0.0.0 connectport=8080 connectaddress=172.20.226.103   to forward port to silly internal one I found in by ifconfig

This informations will be needed in docs for people running it on windows, wsl (ubuntu or other)

The reason I want to run locally, is my fear weserv.nl will go away.  I need way to back this up on the windows machine.

On a side note, weserv is used by me for years, and has helped me load a weather image page that would normally eat up scores of meg in like 700kb, which has allowed me smaller cell bill and faster page loading, and able to pull a weather rad in windy conditions or weak cell conditions that otherwise wouldn't pull.

Thanks.  



I am hazy on all install instruction, since this took so long.

I had 3 notebooks of notes.  This is the latest:  https://docs.google.com/document/d/1fyFTsgl4wELQI4hFKvA_c4-Q2IhHPInBVUMKcNeAKvQ/edit?usp=sharing

I

**Comment by andrieslouw** [comment]
Regarding our future; we've been online since 2007, and are not planning to go away. Thanks for testing, trying and sharing, that's precisely the reason we share our code: So others can use, learn, improve, and share their findings. That's the spirit of open-source, and the internet in general!

**Comment by kleisauke** [comment]
Glad to hear you found a solution to this. I'll close this issue for now, please feel free to re-open if there's still a problem.
