### ISSUE TITLE
How can I crop the format without using URL splicing?

### ISSUE THREAD

**Issue by skrleo** [andrieslouw/imagesweserv#420]
Sometimes the image link is too long. If you use url splicing, the link will be too long.

I would like to use this link format：

Originally: `https://wsrv.nl/?url=wsrv.nl/lichtenstein.jpg&w=300&h=300&fit=cover&mask=circle`

Changed to: `https://wsrv.nl/lichtenstein.jpg&w=300&h=300&fit=cover&mask=circle`

I have to say that your project is amazing, thank you very much for your contribution

**Comment by kleisauke** [comment]
Hello, did you see https://github.com/weserv/images/issues/387#issuecomment-1699748390?
```
https://wsrv.nl/static/lichtenstein.jpg?w=300&h=300&fit=cover&mask=circle
```

**Comment by kleisauke** [comment]
@skrleo Were you able to make any progress with this?

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
