### ISSUE TITLE
Site: AniDB.net | The hostname of the origin is unresolvable (DNS) or blocked by policy.

### ISSUE THREAD

**Issue by FredMT** [andrieslouw/imagesweserv#422]
I believe AniDB's images do not work with weserv.

`{
  "status": "error",
  "code": 404,
  "message": "The hostname of the origin is unresolvable (DNS) or blocked by policy."
}`

URL :- https://wsrv.nl/?url=https://cdn.anidb.net/images/main/279759.jpg

![chrome_l82xPKVUoZ](https://github.com/weserv/images/assets/125679913/2869d948-a0e2-4e83-9f3c-a2f59812c2cf)

**Comment by andrieslouw** [comment]
Please see https://github.com/weserv/images/issues/285#issuecomment-828176654

Anidb.net is tagged as Anime/Manga/Webcomic, and as such is blocked from the public service.

**Comment by FredMT** [comment]
Understood, thanks!
