### ISSUE TITLE
Whitelist http to https domain

### ISSUE THREAD

**Issue by edmundsiah81** [andrieslouw/imagesweserv#426]
Hi,
may I request whitelist of domain as it block when I am passing my http image

**Comment by kleisauke** [comment]
Please can you provide a sample URL that allows someone else to reproduce. Note that we block questionable categories on our public service due to legal concerns. See: https://github.com/weserv/images/issues/285#issuecomment-828176654.

**Comment by edmundsiah81** [comment]
Hi,

http://des.aspial.sg/PMS/pmm_maxi/photo/99472-01-05-3D%20VIEW.jpg

Above is a URL that's belong to an image.

**Comment by kleisauke** [comment]
It looks like the DNS record for this domain name is either incorrect or missing. Are you sure it's a public-facing website?
https://redbot.org/?uri=http://des.aspial.sg/PMS/pmm_maxi/photo/99472-01-05-3D%20VIEW.jpg
https://tools.keycdn.com/performance?url=http://des.aspial.sg/PMS/pmm_maxi/photo/99472-01-05-3D%2520VIEW.jpg
![Screenshot](https://github.com/weserv/images/assets/12746591/b846268d-43e0-4ca6-ad82-2add187e8619)

There's not much we can do for this. Please report this to this website if it continues to be a problem.

**Comment by edmundsiah81** [comment]
Hi Kleis,

Thanks for the help, I will clarify with the website administrator.

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.
