### ISSUE TITLE
Support for Heic (Heif)

### ISSUE THREAD

**Issue by QuadStingray** [andrieslouw/imagesweserv#427]
Have you any plans to support convert Heic format to one of your target conversion formats?

Current Response when I convert a Heic File to PNG:

```json
{
  "status": "error",
  "code": 400,
  "message": "libvips error: source: bad seek to 2198796\nsource: bad seek to 2198796\nheif: Unsupported feature: Unsupported codec (4.3000)\n"
}
```

**Comment by kleisauke** [comment]
We do support HEIC to PNG conversion, as detailed in our [news article](https://wsrv.nl/news/2019/09/01/introducing-api-5.html#support-for-loading-heic-images).

For self-hosted instances, this functionality requires the use of the [`weserv/rpms`](https://github.com/weserv/rpms) packages. Please refer to https://github.com/weserv/rpms/issues/1#issuecomment-1317204593 for detailed instructions on how to use these RPM packages.

**Comment by QuadStingray** [comment]
Thanks for your help! 
It works.
