### ISSUE TITLE
PNG output file is heavier than PNG input 

### ISSUE THREAD

**Issue by adamJLev** [andrieslouw/imagesweserv#429]
Hi there, first of all thanks for developing and maintaining this awesome open source project. 🙏🏼

I noticed that sometimes after the resizing the PNG output file is actually larger than before.
For example:

Input - 2.5 MB png:
https://dv0xp0uwyoh8r.cloudfront.net/stacks/bbe18111-3568-42ca-93f6-830cab15cb5c/media

Output - 4.4MB png:
https://wsrv.nl/?output=png&url=https://dv0xp0uwyoh8r.cloudfront.net/stacks/bbe18111-3568-42ca-93f6-830cab15cb5c/media

I dont know what kind of png compressions are available that could help here, but it feels somewhat like a bug that the output is like 56% larger. 
Thoughts?

**Comment by adamJLev** [comment]
Sorry about that, I didn't realize the input file is actually a jpeg! I should've tripled checked first :) closing

**Comment by kleisauke** [comment]
FWIW, https://wsrv.nl/docs/format.html#adaptive-filter could be helpful in this case. With that, the image in question is  3.2MiB in size.

**Comment by adamJLev** [comment]
thats great to know, thank you!
