### ISSUE TITLE
Domain blocked

### ISSUE THREAD

**Issue by 8times4** [andrieslouw/imagesweserv#431]
Hey there!

Recently our domain has been seemingly blocked, possibly by the automated script I'd assume? (it used to work yesterday)
We have a NextJS imageLoader that routes site images through wsrv.nl, that mainly consists of R2 uploaded evidences from users.

Would it be possible for you to check what happened? 

Thanks!
- 8x4

**Comment by kleisauke** [comment]
Unfortunately we blocked TLD's like .xyz from the public service.

Please see https://github.com/weserv/images/issues/339#issuecomment-1096952128:
> Due to multiple, and continuing, abuse of our service from many randomly generated cheap domains, we blocked all .cc .club .date .fun .pw .top .xxx .xyz domains on our public service. I'm really sorry for this, but the abuse was continuously using over 2 Gbit/s of our bandwidth, which we provide for free. Please consider changing domains to a normal TLD, or hosting the service yourself.

**Comment by 8times4** [comment]
ah 

> Unfortunately we blocked TLD's like .xyz from the public service.
> 
> Please see [#339 (comment)](https://github.com/weserv/images/issues/339#issuecomment-1096952128):
> 
> > Due to multiple, and continuing, abuse of our service from many randomly generated cheap domains, we blocked all .cc .club .date .fun .pw .top .xxx .xyz domains on our public service. I'm really sorry for this, but the abuse was continuously using over 2 Gbit/s of our bandwidth, which we provide for free. Please consider changing domains to a normal TLD, or hosting the service yourself.

ah gotcha, thank you!
