### ISSUE TITLE
Consider adding a way to sort/normalize query strings for better cache ratios

### ISSUE THREAD

**Issue by adamJLev** [andrieslouw/imagesweserv#435]
First of all thanks for this amazing open source project 🙏🏼

So often times frontend apps / clients build the image transform URLs using `URLSearchParams.toString`  https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams or similar.

but this outputs query string in non deterministic order, which reduces the effectiveness of the nginx proxy caching builtin to weserv. E.g. `?a=1&b=2` and `?b=2&a=1` are equivalent but result in multiple cache entries.

Might be interesting for this project to implement something like this, so that the `proxy_cache_key` can include a sorted version of the url params:
https://github.com/wandenberg/nginx-sorted-querystring-module

**Comment by kleisauke** [comment]
You could use [`URLSearchParams.sort()`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/sort) to sort all name-value pairs, which may improve cache hit rates.

Cloudflare also offers a `Normalize URLs to origin` option, but this could lead to unexpected behavior for users who expect that _any_ change in the URL will prevent caching for URLs that have not been visited before.
https://developers.cloudflare.com/rules/normalization/settings/#:~:text=Normalize%20URLs%20to%20origin

**Comment by adamJLev** [comment]
yeah I've been doing the FE `.sort()` which is helpful, and I didnt know about the CF setting! that will  really help.

thank you
