### ISSUE TITLE
How to compile so that I can have the bin/weserve-cli

### ISSUE THREAD

**Issue by Tahakun** [andrieslouw/imagesweserv#438]
Hello, I used to use an older version, and when I tried updating to the latest version, when I ssh into the container there's not bin folder inside `/var/www/imagesweserv` (I'm using the Dockerfile inside the repo)

It used to be in this directory `/var/www/imagesweserv/bin/imagesweserv-cli`
Was the imagesweserv-cli removed in the last version ? or do I need to pass some arguments to make so it creates the binary

**Comment by kleisauke** [comment]
The CLI tool is only available if you build with `-DBUILD_TOOLS=ON`.
https://github.com/weserv/images/blob/947dbc4ef817509620f678d9186cb6c097957687/docker/Dockerfile#L33
https://github.com/weserv/images/blob/947dbc4ef817509620f678d9186cb6c097957687/CMakeLists.txt#L21

> It used to be in this directory `/var/www/imagesweserv/bin/imagesweserv-cli`

Note that it was renamed to `weserv-cli` after commit bc4809a5d16a89563912c45e5c9069e55a2fcced.

**Comment by Tahakun** [comment]
Thanks
