### ISSUE TITLE
Blocking of Facebook and Threads.net?

### ISSUE THREAD

**Issue by edent** [andrieslouw/imagesweserv#439]
I use weserv for serving my OpenGraph images.  When I try to share pages on Facebook and Threads.net, the images aren't displayed.  They are displayed on other services.

Using the [Facebook OGP debugger](https://developers.facebook.com/tools/debug/) I receive an error that the image is corrupted.

> could not be processed as an image. It may be corrupted or may have an invalid format.

![could not be processed as an image. It may be corrupted or may have an invalid format.](https://github.com/user-attachments/assets/68b0af84-2983-4f61-a8e9-a9bef1e49aac)

I've tried both JPG and WebP formats - the error remains.

Is weserv blocking Meta from retrieving the images?

FB report https://developers.facebook.com/community/threads/564775512695053/

Possibly related to #310

**Comment by edent** [comment]
Looks like you're returning HTTP 403 https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fimages.weserv.nl%2F%3Furl%3Dopenbenches.org%2Fimage%2Fe2725d861dc6902da7069f9e8e1f02ab13994fa6%2F%26w%3D600%26q%3D60%26output%3Dwebp%26il

I assume that's intentional?

**Comment by kleisauke** [comment]
Did you see https://github.com/weserv/images/issues/165#issuecomment-438777292?

> This response code could be due to a robots.txt block. Please allowlist facebookexternalhit on your sites robots.txt config to utilize Facebook scraping
