### ISSUE TITLE
How can I solve this error?

### ISSUE THREAD

**Issue by wg6uq8** [andrieslouw/imagesweserv#440]
local install
IP address blocked by policy .
The hostname of the origin is unresolvable (DNS) or blocked by policy.

**Comment by kleisauke** [comment]
By default, access to loopback, link-local, multicast and private IP addresses is denied.
https://github.com/weserv/images/blob/4133e2ff4745a2a70ca12e3113a5306e9e941efd/ngx_conf/nginx.conf#L119-L133

For self-hosted instances, you can remove those `weserv_deny_ip` nginx directives from your `nginx.conf`. For example, in Docker:
```Dockerfile
# Usage: 
# docker build -t weserv/images .
# docker run -d -p 8080:80 --shm-size=1gb --name=weserv weserv/images
FROM ghcr.io/weserv/images:5.x

RUN sed -i '/weserv_deny_ip/d' /etc/nginx/nginx.conf
```

**Comment by wg6uq8** [comment]
Thank you so much
