### ISSUE TITLE
CNAME to allow for nicer URLs

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#46]
# CNAME to allow for nicer URLs [3519776] #

**Submitted by Marcus Greenwood on 5-1-2013 0:00:00**  
**4 votes on UserVoice prior to migration**  

It would be cool if we could do the following.
1. CNAME our own subdomain e.g. images.mydomain.com -> images.weserv.nl
2. Then reference images like so: http://images.mydomain.com/path/to/myimage.png?width=64
This would effectively be the same as http://images.weserv.nl/?url=mydomain.com/path/to/myimage.png&width=64
Of course the caveat being that we would have to setup our own cloudflare/cloudfront/etc on our subdomain to handle the caching.

## Response ##
**by Andries Louw Wolthuizen on 16-6-2013 0:00:00**

We offer this proxy only on the images.weserv.nl domain, and we offer it as-is. However, if you want to use it under your own (sub)domain, please see the response on your other question:
/archive/suggestion-3519754-allow-us-to-host-on-our-own-server
The goal of this proxy is reaching out to starting websites that don’t have the skills nor resources to script and host something themselves.
We, as a company, make websites, web applications and mobile applications, so the image proxy is used by us and our customers a lot. It’s saving us traffic (through compression), and offloading our main servers, because customers don’t have to use poor self-written scripts for image resizing, instead, they can direct it to images.weserv.nl, which is dedicated to the task.
But, we don’t want to serve the whole internet, aside from the amount of traffic (we already handle a couple of million requests each day, which is great), our opinion is that when sites grow, they probably want to host their own solution. This solution will probably integrate better with their site(s), and will offer many advantages we just can’t.
By making this service freely available (as it is currently, and will be), we gain some experience with different user cases, and our customers appreciate it.
We like to hear your thoughts on this, if you have the resources to build something like you described, we happily point our users towards you if they want something alike. But we don’t expect to offer such features ourself.

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/3519776)**

**Comment by andrieslouw** [comment]
See https://github.com/andrieslouw/imagesweserv/issues/45
