### ISSUE TITLE
Format conversion

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#62]
# Format conversion [5097964] #

**Submitted by Seb on 30-11-2013 0:00:00**  
**1 votes on UserVoice prior to migration**  

As I strictly need progressive jpg images, without knowing input format, please add format conversion.
Parameter &of=png, default to input format if not set.
Please note I only need png2jpg.
Thank you and congrats for this wonderful service!

## Response ##
**by Andries Louw Wolthuizen on 8-12-2013 0:00:00**

Added output=. Please help testing this feature.
Possible values:
&output=jpg
&output=png
&output=gif
If you specify none, it will keep the origin image format.
Commits: https://github.com/andrieslouw/imagesweserv/commit/b29abf59670fe70846e76cfb64a0a65368648513 https://github.com/andrieslouw/imagesweserv/commit/526a59c6df1cad3ceaeb269bd0caf3a669593c96

#### Comment by Seb on 8-12-2013 17:25:00 ####
Thx a lot!

#### Comment by Anonymous on 24-9-2015 16:59:00 ####
What about output to webp?

#### Comment by Luuk Lamers on 10-8-2016 10:59:00 ####
It would be nice if in the future WebP were added. Maybe with different headers for browsers that don't support it to fallback to jpg
something like
&output=webp-jpg
&output=webp-png

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/5097964)**

**Comment by andrieslouw** [comment]
See https://github.com/andrieslouw/imagesweserv/issues/68 for follow-up on WEBP output.

**Comment by swordfox** [comment]
It would be good if it could server webp automatically if the request contains the header `accept: image/webp`

KeyCDN does it well:
https://www.keycdn.com/blog/webp-caching

Cheers

**Comment by raiyansarker** [comment]
Is there any update on respecting webp format if webp is present on accept header?

**Comment by kleisauke** [comment]
Due to Cloudflare's caching it's technically impossible to change the output depending on the type browser. Please use the `<picture>`-tag as explained in https://github.com/weserv/images/issues/214.

**Comment by raiyansarker** [comment]
Ok, now I get it, as the cached request won't go to origin, unless you use worker. Thanks for the fast reply!
