### ISSUE TITLE
support webp format

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#68]
# support webp format [5856116] #

**Submitted by sinz on 29-4-2014 0:00:00**  
**2 votes on UserVoice prior to migration**  

we need webp support as google started to implement this on blogspot

## Response ##
**by Andries Louw Wolthuizen on 3-5-2014 0:00:00**

Partial support for WEBP has been implemented. We’re not outputting WEBP towards browsers, and all WEBP-files are internally converted to PNG-images.
Still, this thing is somewhat beta, because the libraries that we depend on are in early stages of supporting WEBP-files.

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/5856116)**

**Comment by andrieslouw** [comment]
See https://github.com/andrieslouw/imagesweserv/issues/62

**Comment by andrieslouw** [comment]
Full support implemented, for output see: https://images.weserv.nl/#output-output
