### ISSUE TITLE
Allow blur transformation (with radius parameter)

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#69]
# Allow blur transformation (with radius parameter) [5873014] #

**Submitted by Guillaume Lecomte on 2-5-2014 0:00:00**  
**6 votes on UserVoice prior to migration**  

CSS3 "filter: blur(px)" has a tendency to slow down the entire page.
As a workaround I use the javascript StackBlur library but it would really be a nice feature to delegate that to an images server with proper caching.

## Response ##
**by Andries Louw Wolthuizen on 4-2-2016 0:00:00**

Blur-like transformations are planned for the V3 of the API, which enables more features. Currently it isn’t exactly clear when this will be implemented. I will update this idea when I’ve more info.

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/5873014)**

**Comment by andrieslouw** [comment]
&blur= has been implemented, see: https://images.weserv.nl/#effects
