### ISSUE TITLE
Wider image format support

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#70]
# Wider image format support [5877622] #

**Submitted by Andries Louw Wolthuizen on 3-5-2014 0:00:00**  
**4 votes on UserVoice prior to migration**  

In an effort to support more image formats (such as TIFF, WEBP, PDF-thumbnails, etc), we're testing with delegating some file-formats to a new library. Please be advised that we're "officially" only supporting GIF, JPEG, PNG and BMP files.
All non GIF/JPEG-files are internally converted to PNG-files, and outputted as such.

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/5877622)**

**Comment by andrieslouw** [comment]
Fixed in current version.
