### ISSUE TITLE
Are there any way to remove a pic from the cache manually?

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#74]
# Are there any way to remove a pic from the cache manually? [7077457] #

**Submitted by Marcsello on 10-2-2015 0:00:00**  
**2 votes on UserVoice prior to migration**  

I wrote a very simple photobook application which generates thumbnails using this service, but some of the images messed up for the first time, so I re uploaded them at the same name, but weserv still serve the old one due to cached, are there any way to update the cached one.
I've read that the server removes the pic within 14 days if not requested. since my server stores the thumbnails to, it wont request it anymore from here. So after 14 day it will update it anyway. I'm just wondering are there any way to force it to delete?
The photobook: http://marcsello.com/content/150pony/photobook.php
It request thumbnial when new pic uploaded, or the old thumb removed over FTP

## Response ##
**by Andries Louw Wolthuizen on 4-2-2016 0:00:00**

Update:
This feature is planned, but it needs additional code to delete images from the different caches. Currently it isn’t exactly clear when this will be implemented. I will update this idea when I have more info.
Original answer:
It’s very hard to delete individual thumbnails; we don’t keep track of the individual url’s requested (or any other userdata).
Please try to use some differentiator in your url’s for future testing; caching is done at quite high level, so even using something like images.weserv.nl/?test=12345&url=… should work.
I hope this answers your question!

#### Comment by Marcsello on 10-2-2015 21:44:00 ####
Thank you so much, you didn't had to rebuild the whole cache for me. I was just wondering about the possibilities. And yea It solved, thank you.
I've added another parameter to the url which contains the upload time of the original file, for further requests.
Now all my ponies looking nice, thank you :)

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/7077457)**

**Comment by andrieslouw** [comment]
See https://github.com/andrieslouw/imagesweserv/issues/14

**Comment by andrieslouw** [comment]
See https://github.com/andrieslouw/imagesweserv/issues/14 for follow-up, will mark this as duplicate.
