### ISSUE TITLE
support SVG image format

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#75]
# support SVG image format [7236402] #

**Submitted by R+pixnet on 17-3-2015 0:00:00**  
**5 votes on UserVoice prior to migration**  

## Response ##
**by Andries Louw Wolthuizen on 4-2-2016 0:00:00**

I added (early) SVG support, it will output as PNG by default, example:
https://images.weserv.nl/?url=dev.w3.org/SVG/tools/svgweb/samples/svg-files/rg1024_green_grapes.svg&w=300
Commit:
https://github.com/andrieslouw/imagesweserv/commit/5bf30b236f721e86510d0e9c0cb1b5334cb182d0
SVG-images are vector based, and the proxy works with bitmaps only. We don’t proxy files bit-for-bit, instead, the first frame of every image get’s processed towards a bitmap, which we eventually recode into (for example) an JPEG-file.
I’m afraid a lot of the quality gets lost. I’m also not sure about the need for resizing if you already have vector based images.

#### Comment by R+pixnet on 17-3-2015 9:59:00 ####
ex:
http://images.weserv.nl/?url=assets.codepen.io/assets/logos/codepen-logo.svg&encoding=base64

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/7236402)**

**Comment by andrieslouw** [comment]
Fixed in current version.

**Comment by adin234** [comment]
can this proxy an svg+xml?

`http://svgshare.com/i/1de.svg`
![GitHub Logo](http://svgshare.com/i/1de.svg)

`https://images.weserv.nl/?url=svgshare.com/i/1de.svg`
![GitHub Logo](https://images.weserv.nl/?url=svgshare.com/i/1de.svg)
