### ISSUE TITLE
Add support for icon (.ico) files

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#76]
# Add support for icon (.ico) files [7550209] #

**Submitted by Jacob H on 13-4-2015 0:00:00**  
**2 votes on UserVoice prior to migration**  

This would be useful for shortcut icons, such as http://www.google.co.uk/favicon.ico

## Response ##
**by Andries Louw Wolthuizen on 17-5-2015 0:00:00**

I’ve implemented .ico support, but this is only for .ico files as source.
Example: http://images.weserv.nl/?url=www.google.nl/favicon.ico&h=12&w=12
(The url on .co.uk is currently wrongly cached by the proxy)
I will need to look into exporting as a .ico file.

#### Comment by Jacob H on 17-5-2015 16:04:00 ####
Thank you! This will be very useful.

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/7550209)**

**Comment by andrieslouw** [comment]
Needs https://github.com/jcupitt/php-vips/issues/34 for milestone v3.0.0

**Comment by andrieslouw** [comment]
https://github.com/jcupitt/php-vips/issues/34 has been fixed, need to wait for libvips 8.5 to appear in repo's.

**Comment by andrieslouw** [comment]
Needs https://github.com/jcupitt/php-vips-ext/issues/7 to implement in production.

**Comment by andrieslouw** [comment]
https://github.com/jcupitt/php-vips-ext/issues/7 is fixed, PECL has been updated, libvips updated to 8.5.2 in production thanks to https://git.remirepo.net/cgit/rpms/lib/vips.git/commit/?id=69047e379be1e5abfc0998178c997e1ca6aae13f
