### ISSUE TITLE
Add image filename in HTTP Header.

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#78]
# Add image filename in HTTP Header. [8072553] #

**Submitted by LI-NA on 22-5-2015 0:00:00**  
**3 votes on UserVoice prior to migration**  

There are no file name in HTTP header.
This mean, when downloading image to "Save This Image", it's filename is default of browser.
But in mobile, it's file name likes 'download.bin'! It is not iamge extensions!
Please add image filename in http header for support mobile and old browser.
Thanks.

## Response ##
**by Andries Louw Wolthuizen on 4-2-2016 0:00:00**

Added the needed header in the code. Supports only gif, png & jpg. Feature will roll-out for new resizes first, so some images may not work because of caching.
Commit:
https://github.com/andrieslouw/imagesweserv/commit/0866ca9dfbe44890584b3e22560eb8d8fdeab0f8

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/8072553)**

**Comment by andrieslouw** [comment]
Fixed in current version.
