### ISSUE TITLE
How to setup proxy server on APACHE server ? any tutorial ?

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#8]
# How to setup proxy server on APACHE server ? any tutorial ? [13031043] #

**Submitted by Darpa on 18-3-2016 0:00:00**  
**1 votes on UserVoice prior to migration**  

how to setup source (github) of proxy on apache based linux server, shared hosting ?

## Response ##
**by Andries Louw Wolthuizen on 18-3-2016 0:00:00**

Hi Darpa,
There is no support on self hosting the code; the service is provided as-is. If your usercase is so specific, you would be experienced enough to do so. Take a look on our GitHub page. All the code is in index.php. Tutorials on setting up webservers can be found online.
Bugs can be reported, and our team will look into it, however, we cannot support self hosted installations. There is no security or access control involved, if you want this, please code it yourself.
If you don’t trust yourself, please use the online service we provide on images.weserv.nl as-is, it is free to use.
I’m sorry that we cannot provide additional support on this matter.
Greetings,
Andries Louw Wolthuizen

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/13031043)**

**Comment by andrieslouw** [comment]
See #87
