### ISSUE TITLE
Background setting

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#81]
# Background setting [9558300] #

**Submitted by Nick @ www.merq.org on 31-8-2015 0:00:00**  
**7 votes on UserVoice prior to migration**  

I've problems with transparent images. Could you please have a look?
Image 1: https://images.weserv.nl/?url=www.briefklick.de%2Ffavicon.ico&w=64&h=64&t=square&output=gif
Image 2: https://images.weserv.nl/?url=www.vavideo.de%2Ffavicon.ico&w=64&h=64&t=square&output=gif
Now I set the output on gif. But the second image is not showing correctly.
For testing:
Image 1 is working with output in PNG only. Image 2 is working with output in GIF only.
Please add an option how to handle transparent backgrounds. And / or to define the background color &bg=FFFFFF.
Thanks!

## Response ##
**by Andries Louw Wolthuizen on 4-2-2016 0:00:00**

There are some changes now, which should solve some of the cases (but not all unfortunately). At least output as PNG should work now.
Commit:
https://github.com/andrieslouw/imagesweserv/commit/2010cfce95e6cddda12533bfc722c647af4f1298

**[Original UserVoice Submission](https://imagesweserv.uservoice.com/forums/144259-images-weserv-nl-general/suggestions/9558300)**

**Comment by andrieslouw** [comment]
See https://github.com/andrieslouw/imagesweserv/issues/80

**Comment by andrieslouw** [comment]
Implemented, see https://images.weserv.nl/#background-bg
