### ISSUE TITLE
Image without parameters bigger than original

### ISSUE THREAD

**Issue by uok** [andrieslouw/imagesweserv#82]
Thanks for this great tool (and also moving to github)

Today I noticed that if you forget to set parameters the size of the new image is bigger than the original, e.g. 
```
(5969 bytes) https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
(8787 bytes) https://images.weserv.nl/?url=ssl%3Awww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F1x%2Fgooglelogo_color_272x92dp.png 
```
In this case sending the unprocessed data from original image could help saving bandwidth and computing time

**Comment by kleisauke** [comment]
Hello, that logo will probably have been `pngcrush`ed. `pngcrush` tries combinations of compression level and row filter settings to see which produces the smallest output.

With commit 79f7f22 (on the [3.x branch](https://github.com/andrieslouw/imagesweserv/tree/3.x)) and the logo you have provided the new image size on our test environment is `6714 bytes` (an increase of 12.48%). If we set `zlib compression level` to 9 the new image size is `6317 bytes` (an increase of 5.83%).

I will investigate whether it is possible to return the original image when no parameters are specified and if the new image size is greater than the original image size.

**Comment by uok** [comment]
Thanks for the fast response and compression settings! I think those two checks would be a good improvement. 

The same goes for a JPG image which is not transformed: if new dimensions (height, width) are the same as the old ones you usually end up with a much larger image because of decompressing and compressing afterwards (e.g. with standard quality setting of 85). Here a comparison of new data size to original data size would also be a good idea.

**Comment by kleisauke** [comment]
We decided to not implement this feature. There are 2 reasons for this:
- When we first completely process the image, then comparing the original image with the processed image, and then perhaps return the original image again, it all takes longer than simply return the processed image.
- We're stripping all metadata (EXIF, XMP, IPTC) from the output image. Also, we're doing auto-orient based on the EXIF `Orientation` tag. It can lead to confusion when a user expects that his original image is completely stripped and auto-oriented but instead his original image is returned.

Feel free to implement this feature and running the source code yourself.
