### ISSUE TITLE
Cloudflare IP Ban

### ISSUE THREAD

**Issue by leongersen** [andrieslouw/imagesweserv#83]
Someone at my company decided to scrape some of our websites, hitting the weserv server an excessive amount of times. I guess some rate limit kicked in and -rightfully- banned our IP. Is there a way to get unbanned?

I yelled at my collegue and he won't do it again.

**Comment by andrieslouw** [comment]
Please grab a coffee, bans only last for one hour, and should be lifted automatically (like magic!). If it happens more often, we could relax the limits a bit, if you let me know what you're trying to do in advance.

And yelling at your colleagues is never appropriate, maybe you could put them on coffee-duty for a week or so ;-)

**Comment by leongersen** [comment]
Ah, great news, all is well again. I wouldn't dare to *actually* yell, I just look really disappointed and hope the message sticks. Thanks!

**Comment by noahbody-knows** [comment]
What is the actual limit, by the way?  I've been playing with a Greasemonkey script to add cover thumbnails to a book site, and it tends to trip the ban within a few pages (at a couple hundred thumbnails per page).

One rather surprising thing about it is that loading *the same images* from a different IP results in a ban for that second IP, even though it seems those images should already be being cached by CloudFlare and not counted towards the limits at that point?  Or is that not how it works?

**Comment by andrieslouw** [comment]
The limit is around 700 images per 3 minutes. CloudFlare works a bit like magic, because the caching is done per datacenter. With around 100+ datacenters, it could be that your second IP is hitting another datacenter.

**Comment by kleisauke** [comment]
We've refined our rate limiter in API version 5. It's now easy to check show your current rate limit quota:
https://images.weserv.nl/news/2019/09/01/introducing-api-5/#improved-rate-limiter
