### ISSUE TITLE
Cache control for weather images 

### ISSUE THREAD

**Issue by degarb** [andrieslouw/imagesweserv#86]
I wish to use the proxy to shave 600k in weather images. 

Cache age can be no more than 60 minutes old.  I tried adding & cache controls. But I reload and the weather image still is pulling from the cache.

**Comment by andrieslouw** [comment]
We will not adjust the cache age, it'll simply cause too much load on our servers, and the service needs to remain free to use for anyone. Please use the script, modify it, and host it for yourself. I'm sorry, but we previously tried such options, but they're really hard to sustain.
