### ISSUE TITLE
Easy installing - Docker

### ISSUE THREAD

**Issue by degarb** [andrieslouw/imagesweserv#87]
I have only installed phonifier php before. And managed to write my own index.php, for my simple webpage that uses simple if/then and date variables to avoid javascript, which I hate with a passion.

I read readme, wiki.  Really no step by step directions for installing on my server. My goal to shave a half gig off my monthly cell bill: I check up to 120 weather images daily.  I need good compression.  So, either steps are missing, or I just download all directories and ftp upload to my paid host?  Don't see how my host could cache, so I would prefer to turn cache off.   No idea how. ... I never had any luck installing php on my windows home webserver. Never ever got any linux server running at home.  Also, linux cannot do autohotkey, and has zero replacement. I also need home computers to run playon for free cable.  So linux at home is out.

I was looking for a step by step guide to installing weserv, not hints.

**Comment by andrieslouw** [comment]
Step-by-step instructions are not available (yet), but I mostly understand that you would like an easy-to-setup way of running our code.

We will look if we can make a docker image from our repo for this purpose. Docker images should run regardless of operating system, and facilitate the ease of setup required by you.

Please allow us some time to experiment with docker, as there is some time investment required on our side to do the right things. When finished, we'll try to include some instructions to get it working.

By the way, while Images.weserv.nl uses CentOS (Linux) on its servers, this isn't necessary. For this script you'll only need Nginx and PHP, both of which run fine on Windows too. You could even virtualize Linux, by means of VMWare (or Cygwin, or WSL on Windows 10), if you really want Linux to run this script.

**Comment by andrieslouw** [comment]
Please take a look at our new Docker tutorial: https://github.com/andrieslouw/imagesweserv/blob/3.x/DOCKER.md

**Comment by degarb** [comment]
Awesome!  I will.

Thank you, thank you for the email.

Best regards, Dennis Garber 330-957-[redacted]

Mobile voice transcription a courtesy of Google Inc.-- causing accidents
since 2008 to make way for the Google driverless car of the future. .
