### ISSUE TITLE
Add support for smart crop

### ISSUE THREAD

**Issue by kleisauke** [andrieslouw/imagesweserv#90]
Support for smart crop has landed in the new [libvips 8.5](http://jcupitt.github.io/libvips/2017/03/16/What's-new-in-8.5.html). This cropping method searches the image for edges, skin tones and areas of saturated colour, and attempts to position the crop box over the most significant feature.

If libvips 8.5 appears in [Remi's RPM repository](https://git.remirepo.net/cgit/rpms/lib/vips.git/) (and if it has been updated on our server), we need to uncomment the following lines: [index.php#L668-L676](https://github.com/andrieslouw/imagesweserv/blob/85bfacbfbdd94aca6916d346412ed996d5da6639/public/index.php#L668-L676), [Size.php#L615](https://github.com/andrieslouw/imagesweserv/blob/85bfacbfbdd94aca6916d346412ed996d5da6639/src/Manipulators/Size.php#L615).

**Comment by andrieslouw** [comment]
Still needs some documentation & examples to be marked as completed, code is running in production.

**Comment by kleisauke** [comment]
Implemented, see: https://images.weserv.nl/#crop-smartcrop

I'll leave this enhancement open to give it some publicity.
