### ISSUE TITLE
Issue affecting 0.03% of JPEG-resizes

### ISSUE THREAD

**Issue by andrieslouw** [andrieslouw/imagesweserv#91]
Since 11th of April 2017 we see issues occuring at 0.03% of the resize operations on JPEG-images.

The issue has been fixed upstream, and will be implemented soon. Please bear with us while we fix things.

**Comment by andrieslouw** [comment]
See https://github.com/jcupitt/libvips/issues/639

**Comment by andrieslouw** [comment]
Similar to https://github.com/jcupitt/libvips/issues/261

**Comment by andrieslouw** [comment]
https://github.com/jcupitt/libvips/issues/639 has been solved, waiting for push to production enviroment.

**Comment by andrieslouw** [comment]
Pushed to production, still not fixed, https://github.com/jcupitt/libvips/issues/639 has been reopened

**Comment by kleisauke** [comment]
This issue has been solved in libvips v8.5.4 which is running in production. Sorry for any inconvenience caused.
