### ISSUE TITLE
Image doesn't seem to load with il parameter on jpg

### ISSUE THREAD

**Issue by ImaCrea** [andrieslouw/imagesweserv#92]
Hi dear folks,
we absolutely love your service at http://mailta.pe 

But lately there's been an image that we haven't been able to load from your server correctly.
We always get this error:

> Error 404: Server couldn't parse the ?url= that you were looking for, error it got: The requested URL returned error: 0 cURL error 28: Operation timed out after 10000 milliseconds with 2555760 out of 5230623 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

This happens when trying to request: https://images.weserv.nl/?url=www.mailta.pe/img/guestPic257.jpg&w=1400&t=fit&il
I tried also with a jpg file, same error.

What's even more weird is that if I request https://images.weserv.nl/?url=www.mailta.pe/img/guestPic257.jpg&w=1400&t=fit well... it works!

I have tried with another file, in PNG for example, not working either. It's strange as every other images we're using with your service are working, see with https://images.weserv.nl/?url=www.mailta.pe/img/guestPic256.jpg&w=1400&t=fit&il for example.

Don't know what to do :/ please help 🙏

**Comment by andrieslouw** [comment]
The error you're mentioning has to do with transfer speed. The image could not be downloaded from the origin (mailta.pe) within 10 seconds. It looks like mailta.pe had an upload speed of 2.0 Mbit/s (2555760 bytes = 19.5 megabits in 10 seconds). It is possible that this error won't show each time. You would require around 4.5 Mbit/s at least for that image to load within 10 seconds, so you'll need sufficient bandwidth. Another solution would be to host this proxy yourself, or do some resizing in advance, to get smaller (filesize) images.

**Comment by andrieslouw** [comment]
If no further assistance is required, I'll close this issue. The image still seems to large to load quickly from your servers, please increase your bandwidth, or shrink this image.

**Comment by vvavepacket** [comment]
@andrieslouw 

Do you know by any chance where in this software we can configure to increase timed out? 10 seconds is not enough for me. Thank you.

**Comment by andrieslouw** [comment]
@vvavepacket:

The time-out cannot be changed for the public service on https://images.weserv.nl/ to prevent abuse. 10 seconds at 1 Gbit/s (max. transfer speed of public service) should be enough to load images around ~1GByte with the public service. If the transfer speed is below 1 Gbit/s you should check the bandwidth of the origin server (Amazon S3 is known to be slow for example).

If you use the source-code on your own server, the time-out can be changed here:

https://github.com/andrieslouw/imagesweserv/blob/b0366867fe5a200be5ffe3ca3693b3a727d6f0dc/config.example.php#L16-L17
