### ISSUE TITLE
Face detection based cropping

### ISSUE THREAD

**Issue by Kikobeats** [andrieslouw/imagesweserv#97]
Hey,

I love this projects. Thanks for offering free and open source!

Do you think tha could be more or less easy implement face detection for cropping?

References:
- http://cloudinary.com/documentation/image_transformations#face_detection_based_cropping
- https://29a.ch/2014/04/03/smartcrop-content-aware-image-cropping

**Comment by kleisauke** [comment]
There is a smart crop feature available (which is similar to your second reference). 
See: https://images.weserv.nl/#crop-smartcrop and https://github.com/andrieslouw/imagesweserv/issues/90.

This cropping method searches the image for edges, skin tones and areas of saturated colour, and attempts to position the crop box over the most significant feature.

It's not a `face-detection` based crop, but perhaps it's enough for your use-case.

**Comment by Kikobeats** [comment]
Thanks for your comment!

Could be nice add `question` tag for this issue for help people in the future 👍
